from cishouseholds.pipeline.validation_schema import validation_schemas

d_schema = validation_schemas["cis_digital_validation_schema"]


lookup = {
    "PHM-FUP-INT-003": "participant_first_name_confirmation",
    "PHM-FUP-INT-004": "participant_first_name_on_behalf_of_confirmation",
    "PHM-FUP-INT-006": "cohort_type",
    "PHM-FUP-SAM-001": "swab_taken",
    "PHM-FUP-SAM-002": "swab_not_taken_reason",
    "PHM-FUP-SAM-003": "swab_barcode_confirmation",
    "PHM-FUP-SAM-004": "swab_sample_barcode_user_entered",
    "PHM-FUP-SAM-005": "swab_taken_date",
    "PHM-FUP-SAM-006": "swab_taken_time_hour",
    "PHM-FUP-SAM-007": "swab_taken_time_minute",
    "PHM-FUP-SAM-008": "swab_taken_am_pm",
    "PHM-FUP-SAM-009": "swab_returned",
    "PHM-FUP-SAM-010": "swab_return_date",
    "PHM-FUP-SAM-011": "swab_return_future_date",
    "PHM-FUP-SAM-012": "blood_taken",
    "PHM-FUP-SAM-013": "blood_not_taken_reason",
    "PHM-FUP-SAM-014": "blood_not_taken_could_not_reason_1",
    "PHM-FUP-SAM-015": "blood_not_taken_could_not_reason_2",
    "PHM-FUP-SAM-016": "blood_not_taken_could_not_reason_3",
    "PHM-FUP-SAM-017": "blood_not_taken_could_not_reason_4",
    "PHM-FUP-SAM-018": "blood_not_taken_could_not_reason_5",
    "PHM-FUP-SAM-019": "blood_not_taken_could_not_other",
    "PHM-FUP-SAM-020": "questionnaire_started_no_incentive",
    "PHM-FUP-SAM-021": "test_kit_info_end_of_survey",
    "PHM-FUP-SAM-022": "blood_barcode_confirmation",
    "PHM-FUP-SAM-023": "blood_barcode_user_entered",
    "PHM-FUP-SAM-024": "blood_taken_date",
    "PHM-FUP-SAM-025": "blood_taken_time_hour",
    "PHM-FUP-SAM-026": "blood_taken_time_minute",
    "PHM-FUP-SAM-027": "blood_taken_am_pm",
    "PHM-FUP-SAM-028": "blood_returned",
    "PHM-FUP-SAM-029": "blood_return_date",
    "PHM-FUP-SAM-030": "blood_return_future_date",
    "PHM-FUP-WE-001": "aged_16_or_over",
    "PHM-FUP-WE-002": "work_status_digital",
    "PHM-FUP-WE-003": "work_status_employment",
    "PHM-FUP-WE-004": "work_status_unemployment",
    "PHM-FUP-WE-005": "work_status_education",
    "PHM-FUP-WE-006": "work_in_additional_paid_employment",
    "PHM-FUP-WE-007": "work_main_job_changed",
    "PHM-FUP-WE-008": "work_main_job_title",
    "PHM-FUP-WE-009": "work_main_job_role",
    "PHM-FUP-WE-010": "work_sector",
    "PHM-FUP-WE-011": "work_sector_other",
    "PHM-FUP-WE-012": "work_health_care_area",
    "PHM-FUP-WE-013": "work_nursing_or_residential_care_home",
    "PHM-FUP-WE-014": "work_direct_contact_patients_or_clients",
    "PHM-FUP-WE-015": "work_location",
    "PHM-FUP-WE-016": "work_not_from_home_days_per_week",
    "PHM-FUP-WE-017": "education_in_person_days_per_week",
    "PHM-FUP-WE-018": "transport_to_work_or_education",
    "PHM-FUP-WE-019": "ability_to_socially_distance_at_work_or_education",
    "PHM-FUP-HST-001": "think_have_covid_symptom_runny_nose_or_sneezing",
    "PHM-FUP-HST-002": "think_have_covid_symptom_loss_of_smell",
    "PHM-FUP-HST-003": "think_have_covid_symptom_loss_of_taste",
    "PHM-FUP-HST-004": "think_have_covid_symptom_sore_throat",
    "PHM-FUP-HST-005": "think_have_covid_symptom_cough",
    "PHM-FUP-HST-006": "think_have_covid_symptom_shortness_of_breath",
    "PHM-FUP-HST-007": "think_have_covid_symptom_noisy_breathing",
    "PHM-FUP-HST-008": "think_have_covid_symptom_abdominal_pain",
    "PHM-FUP-HST-009": "think_have_covid_symptom_nausea_or_vomiting",
    "PHM-FUP-HST-010": "think_have_covid_symptom_diarrhoea",
    "PHM-FUP-HST-011": "think_have_covid_symptom_loss_of_appetite",
    "PHM-FUP-HST-012": "no_symptoms_list_1",
    "PHM-FUP-HST-013": "think_have_covid_symptom_loss_of_appetite",
    "PHM-FUP-HST-014": "think_have_covid_symptom_muscle_ache",
    "PHM-FUP-HST-015": "think_have_covid_symptom_fatigue",
    "PHM-FUP-HST-016": "think_have_covid_symptom_fever",
    "PHM-FUP-HST-017": "think_have_covid_symptom_more_trouble_sleeping",
    "PHM-FUP-HST-018": "think_have_covid_symptom_memory_loss_or_confusion",
    "PHM-FUP-HST-019": "think_have_covid_symptom_difficulty_concentrating",
    "PHM-FUP-HST-020": "think_have_covid_symptom_anxiety",
    "PHM-FUP-HST-021": "think_have_covid_symptom_low_mood",
    "PHM-FUP-HST-022": "no_symptoms_list_2",
    "PHM-FUP-HST-023": "think_have_covid_symptom_onset_date",
    "PHM-FUP-HST-024": "illness_lasting_over_12_months",
    "PHM-FUP-HST-025": "illness_reduces_activity_or_ability",
    "PHM-FUP-HST-026": "ever_smoked_regularly",
    "PHM-FUP-HST-027": "currently_smokes_or_vapes",
    "PHM-FUP-HST-028": "currently_smokes_or_vapes_cigarettes",
    "PHM-FUP-HST-029": "currently_smokes_or_vapes_cigars",
    "PHM-FUP-HST-030": "currently_smokes_or_vapes_pipes",
    "PHM-FUP-HST-031": "currently_smokes_or_vapes_vapes",
    "PHM-FUP-HST-032": "currently_smokes_or_vapes_hookah",
    "PHM-FUP-HST-033": "cis_covid_vaccine_received",
    "PHM-FUP-HST-034": "cis_covid_vaccine_type",
    "PHM-FUP-HST-035": "cis_covid_vaccine_type_other",
    "PHM-FUP-HST-036": "cis_covid_vaccine_number_of_doses",
    "PHM-FUP-HST-037": "cis_covid_vaccine_date",
    "PHM-FUP-HST-038": "flu_vaccination_received",
    "PHM-FUP-HST-039": "flu_vaccination_received_date",
    "PHM-FUP-HST-040": "been_outside_uk",
    "PHM-FUP-HST-041": "been_outside_uk_last_country",
    "PHM-FUP-HST-042": "been_outside_uk_last_return_date",
    "PHM-FUP-C19-001": "PHM_think_had_respiratory_infection",
    "PHM-FUP-C19-002": "PHM_think_had_respiratory_infection_type_covid",
    "PHM-FUP-C19-003": "PHM_think_had_respiratory_infection_type_flu",
    "PHM-FUP-C19-004": "PHM_think_had_respiratory_infection_type_other",
    "PHM-FUP-C19-005": "PHM_think_had_respiratory_infection_type_dont_know",
    "PHM-FUP-C19-006": "think_had_covid_onset_date",
    "PHM-FUP-C19-007": "think_had_covid_symptom_runny_nose_or_sneezing",
    "PHM-FUP-C19-008": "think_had_covid_symptom_loss_of_smell",
    "PHM-FUP-C19-009": "think_had_covid_symptom_loss_of_taste",
    "PHM-FUP-C19-010": "think_had_covid_symptom_sore_throat",
    "PHM-FUP-C19-011": "think_had_covid_symptom_cough",
    "PHM-FUP-C19-012": "think_had_covid_symptom_shortness_of_breath",
    "PHM-FUP-C19-013": "think_had_covid_symptom_noisy_breathing",
    "PHM-FUP-C19-014": "think_had_covid_symptom_abdominal_pain",
    "PHM-FUP-C19-015": "think_had_covid_symptom_nausea_or_vomiting",
    "PHM-FUP-C19-016": "think_had_covid_symptom_diarrhoea",
    "PHM-FUP-C19-017": "think_had_covid_symptom_loss_of_appetite",
    "PHM-FUP-C19-018": "think_had_covid_symptom_list_1_none",
    "PHM-FUP-C19-019": "think_had_covid_symptom_headache",
    "PHM-FUP-C19-020": "think_had_covid_symptom_muscle_ache",
    "PHM-FUP-C19-021": "think_had_covid_symptom_fatigue",
    "PHM-FUP-C19-022": "think_had_covid_symptom_fever",
    "PHM-FUP-C19-023": "think_had_covid_symptom_more_trouble_sleeping",
    "PHM-FUP-C19-024": "think_had_covid_symptom_memory_loss_or_confusion",
    "PHM-FUP-C19-025": "think_had_covid_symptom_difficulty_concentrating",
    "PHM-FUP-C19-026": "think_had_covid_symptom_anxiety",
    "PHM-FUP-C19-027": "think_had_covid_symptom_low_mood",
    "PHM-FUP-C19-028": "think_had_covid_symptom_list_2_none",
    "PHM-FUP-C19-029": "PHM_think_had_flu_onset_date",
    "PHM-FUP-C19-030": "think_had_flu_symptom_runny_nose_or_sneezing",
    "PHM-FUP-C19-031": "think_had_flu_symptom_loss_of_smell",
    "PHM-FUP-C19-032": "think_had_flu_symptom_loss_of_taste",
    "PHM-FUP-C19-033": "think_had_flu_symptom_sore_throat",
    "PHM-FUP-C19-034": "think_had_flu_symptom_cough",
    "PHM-FUP-C19-035": "think_had_flu_symptom_shortness_of_breath",
    "PHM-FUP-C19-036": "think_had_flu_symptom_noisy_breathing",
    "PHM-FUP-C19-037": "think_had_flu_symptom_abdominal_pain",
    "PHM-FUP-C19-038": "think_had_flu_symptom_nausea_or_vomiting",
    "PHM-FUP-C19-039": "think_had_flu_symptom_diarrhoea",
    "PHM-FUP-C19-040": "think_had_flu_symptom_loss_of_appetite",
    "PHM-FUP-C19-041": "think_had_flu_symptom_list_1_none",
    "PHM-FUP-C19-042": "think_had_flu_symptom_headache",
    "PHM-FUP-C19-043": "think_had_flu_symptom_muscle_ache",
    "PHM-FUP-C19-044": "think_had_flu_symptom_fatigue",
    "PHM-FUP-C19-045": "think_had_flu_symptom_fever",
    "PHM-FUP-C19-046": "think_had_flu_symptom_more_trouble_sleeping",
    "PHM-FUP-C19-047": "think_had_flu_symptom_memory_loss_or_confusion",
    "PHM-FUP-C19-048": "think_had_flu_symptom_difficulty_concentrating",
    "PHM-FUP-C19-049": "think_had_flu_symptom_anxiety",
    "PHM-FUP-C19-050": "think_had_flu_symptom_low_mood",
    "PHM-FUP-C19-051": "think_had_flu_symptom_list_2_none",
    "PHM-FUP-C19-052": "PHM_think_had_other_infection_onset_date",
    "PHM-FUP-C19-053": "think_had_other_infection_symptom_runny_nose_or_sneezing",
    "PHM-FUP-C19-054": "think_had_other_infection_symptom_loss_of_smell",
    "PHM-FUP-C19-055": "think_had_other_infection_symptom_loss_of_taste",
    "PHM-FUP-C19-056": "think_had_other_infection_symptom_sore_throat",
    "PHM-FUP-C19-057": "think_had_other_infection_symptom_cough",
    "PHM-FUP-C19-058": "think_had_other_infection_symptom_shortness_of_breath",
    "PHM-FUP-C19-059": "think_had_other_infection_symptom_noisy_breathing",
    "PHM-FUP-C19-060": "think_had_other_infection_symptom_abdominal_pain",
    "PHM-FUP-C19-061": "think_had_other_infection_symptom_nausea_or_vomiting",
    "PHM-FUP-C19-062": "think_had_other_infection_symptom_diarrhoea",
    "PHM-FUP-C19-063": "think_had_other_infection_symptom_loss_of_appetite",
    "PHM-FUP-C19-064": "think_had_other_infection_symptom_list_1_none",
    "PHM-FUP-C19-065": "think_had_other_infection_symptom_headache",
    "PHM-FUP-C19-066": "think_had_other_infection_symptom_muscle_ache",
    "PHM-FUP-C19-067": "think_had_other_infection_symptom_fatigue",
    "PHM-FUP-C19-068": "think_had_other_infection_symptom_fever",
    "PHM-FUP-C19-069": "think_had_other_infection_symptom_more_trouble_sleeping",
    "PHM-FUP-C19-070": "think_had_other_infection_symptom_memory_loss_or_confusion",
    "PHM-FUP-C19-071": "think_had_other_infection_symptom_difficulty_concentrating",
    "PHM-FUP-C19-072": "think_had_other_infection_symptom_anxiety",
    "PHM-FUP-C19-073": "think_had_other_infection_symptom_low_mood",
    "PHM-FUP-C19-074": "think_had_other_infection_symptom_list_2_none",
    "PHM-FUP-C19-075": "other_covid_infection_test",
    "PHM-FUP-C19-076": "test_type_positive_result",
    "PHM-FUP-C19-077": "other_covid_infection_test_results",
    "PHM-FUP-C19-078": "other_covid_infection_test_positive_date",
    "PHM-FUP-C19-079": "other_covid_infection_test_negative_date",
    "PHM-FUP-C19-080": "last_28_days_unable_usual_activites",
    "PHM-FUP-C19-081": "last_28_days_unable_usual_activites_due_to_respiratory_infection",
    "PHM-FUP-C19-082": "last_28_days_off_work_education_due_to_health",
    "PHM-FUP-C19-083": "last_28_days_off_work_education_due_to_health_respiratory_infection",
    "PHM-FUP-C19-084": "last_28_days_GP_appointment_health_reasons",
    "PHM-FUP-C19-085": "last_28_days_GP_appointment_health_reasons_respiratory_infection",
    "PHM-FUP-C19-086": "last_28_days_pharmacist_111",
    "PHM-FUP-C19-087": "last_28_days_pharmacist_111_respiratory_infection",
    "PHM-FUP-C19-088": "last_28_days_urgent_care",
    "PHM-FUP-C19-089": "last_28_days_urgent_care_respiratory_infection",
    "PHM-FUP-C19-090": "last_28_days_admitted_to_hospital",
    "PHM-FUP-C19-091": "last_28_days_admitted_to_hospital",
    "PHM-FUP-C19-092": "think_have_long_covid",
    "PHM-FUP-C19-093": "think_have_long_covid_symptom_reduced_ability",
    "PHM-FUP-C19-094": "think_have_long_covid_symptom_headache",
    "PHM-FUP-C19-095": "think_have_long_covid_symptom_eyesight_sore_eyes",
    "PHM-FUP-C19-096": "think_have_long_covid_symptom_tinnitus_hearing_problems",
    "PHM-FUP-C19-097": "think_have_long_covid_symptom_ear_pain",
    "PHM-FUP-C19-098": "think_have_long_covid_symptom_runny_nose_or_sneezing",
    "PHM-FUP-C19-099": "think_have_long_covid_symptom_nasal_congestion",
    "PHM-FUP-C19-100": "think_have_long_covid_symptom_sore_throat",
    "PHM-FUP-C19-101": "think_have_long_covid_symptom_cough",
    "PHM-FUP-C19-102": "think_have_long_covid_symptom_shortness_of_breath",
    "PHM-FUP-C19-103": "think_have_long_covid_symptom_noisy_breathing",
    "PHM-FUP-C19-104": "think_have_long_covid_symptom_chest_pain",
    "PHM-FUP-C19-105": "think_have_long_covid_symptom_palpitations",
    "PHM-FUP-C19-106": "think_have_long_covid_symptom_list_1_none",
    "PHM-FUP-C19-107": "think_have_long_covid_symptom_nausea_or_vomiting",
    "PHM-FUP-C19-108": "think_have_long_covid_symptom_abdominal_pain",
    "PHM-FUP-C19-109": "think_have_long_covid_symptom_diarrhoea",
    "PHM-FUP-C19-110": "think_have_long_covid_symptom_loss_of_appetite",
    "PHM-FUP-C19-111": "think_have_long_covid_symptom_muscle_ache",
    "PHM-FUP-C19-112": "think_have_long_covid_symptom_joint_pain",
    "PHM-FUP-C19-113": "think_have_long_covid_symptom_mobility_problems",
    "PHM-FUP-C19-114": "think_have_long_covid_symptom_loss_of_taste",
    "PHM-FUP-C19-115": "think_have_long_covid_symptom_loss_of_smell",
    "PHM-FUP-C19-116": "think_have_long_covid_symptom_memory_loss_or_confusion",
    "PHM-FUP-C19-117": "think_have_long_covid_symptom_difficulty_concentrating",
    "PHM-FUP-C19-118": "think_have_long_covid_symptom_list_2_none",
    "PHM-FUP-C19-119": "think_have_long_covid_symptom_more_trouble_sleeping",
    "PHM-FUP-C19-120": "think_have_long_covid_symptom_anxiety",
    "PHM-FUP-C19-121": "think_have_long_covid_symptom_low_mood",
    "PHM-FUP-C19-122": "think_have_long_covid_symptom_fatigue",
    "PHM-FUP-C19-123": "think_have_long_covid_symptom_fever",
    "PHM-FUP-C19-124": "think_have_long_covid_symptom_general_pain",
    "PHM-FUP-C19-125": "think_have_long_covid_symptom_vertigo_or_dizziness",
    "PHM-FUP-C19-126": "think_have_long_covid_symptom_allergies_intolerances",
    "PHM-FUP-C19-127": "think_have_long_covid_symptom_hair_loss",
    "PHM-FUP-C19-128": "think_have_long_covid_symptom_pins_needles_numbness",
    "PHM-FUP-C19-129": "think_have_long_covid_symptom_rashes_itchy_skin",
    "PHM-FUP-C19-130": "think_have_long_covid_symptom_list_3_none",
    "PHM-FUP-C19-131": "think_have_long_covid_symptom_worse_after_effort",
    "PHM-FUP-CON-001": "other_household_member_hospital_last_28_days",
    "PHM-FUP-CON-002": "care_home_last_28_days",
    "PHM-FUP-CON-003": "hours_a_day_with_someone_else_at_home_number",
    "PHM-FUP-CON-004": "hours_a_day_with_someone_else_at_home_string",
    "PHM-FUP-CON-005": "physical_contact_under_18_years",
    "PHM-FUP-CON-006": "physical_contact_18_to_69_years",
    "PHM-FUP-CON-007": "physical_contact_over_70_years",
    "PHM-FUP-CON-008": "social_distance_contact_under_18_years",
    "PHM-FUP-CON-009": "social_distance_contact_18_to_69_years",
    "PHM-FUP-CON-010": "social_distance_contact_over_70_years",
    "PHM-FUP-CON-011": "times_hour_or_longer_another_home_last_7_days",
    "PHM-FUP-CON-012": "times_hour_or_longer_another_person_your_home_last_7_days",
    "PHM-FUP-CON-013": "times_shopping_last_7_days",
    "PHM-FUP-CON-014": "times_socialise_last_7_days",
    "PHM-FUP-CON-015": "times_indoor_exercise_last_28_days",
    "PHM-FUP-CON-016": "times_large_events_last_28_days",
    "PHM-FUP-CON-017": "times_medium_events_last_28_days",
    "PHM-FUP-CON-018": "transport_shared_outside_household_last_28_days_underground_tram",
    "PHM-FUP-CON-019": "transport_shared_outside_household_last_28_days_train",
    "PHM-FUP-CON-020": "transport_shared_outside_household_last_28_days_bus_coach",
    "PHM-FUP-CON-021": "transport_shared_outside_household_last_28_days_car_van",
    "PHM-FUP-CON-022": "transport_shared_outside_household_last_28_days_taxi",
    "PHM-FUP-CON-023": "transport_shared_outside_household_last_28_days_plane",
    "PHM-FUP-CON-024": "transport_shared_outside_household_last_28_days_ferry_boat",
    "PHM-FUP-CON-025": "transport_shared_outside_household_last_28_days_other",
    "PHM-FUP-CON-026": "transport_shared_outside_household_last_28_days_none",
    "PHM-FUP-CON-027": "face_covering_other_enclosed_places",
    "PHM-FUP-END-002": "end_screen_questionnaire",
    "PHM-FUP-END-001": "end_screen_sample",
    "started_at": "survey_completion_window_start_datetime",
    "submission_language_code": "survey_language_submitted",
}

phm_validation_schema = {
    "participant_first_name_confirmation": {"type": "string"},
    "participant_first_name_on_behalf_of_confirmation": {"type": "string"},
    "cohort_type": {"type": "string"},
    "swab_taken": {"type": "string"},
    "swab_not_taken_reason": {"type": "string"},
    "swab_barcode_confirmation": {"type": "string"},
    "swab_sample_barcode_user_entered": {"type": "string"},
    "swab_taken_date": {"type": "string"},
    "swab_taken_time_hour": {"type": "integer"},
    "swab_taken_time_minute": {"type": "integer"},
    "swab_taken_am_pm": {"type": "string"},
    "swab_returned": {"type": "string"},
    "swab_return_date": {"type": "string"},
    "swab_return_future_date": {"type": "string"},
    "blood_taken": {"type": "string"},
    "blood_not_taken_reason": {"type": "string"},
    "blood_not_taken_could_not_reason_1": {"type": "string"},
    "blood_not_taken_could_not_reason_2": {"type": "string"},
    "blood_not_taken_could_not_reason_3": {"type": "string"},
    "blood_not_taken_could_not_reason_4": {"type": "string"},
    "blood_not_taken_could_not_reason_5": {"type": "string"},
    "blood_not_taken_could_not_other": {"type": "string"},
    "questionnaire_started_no_incentive": {"type": "string"},
    "test_kit_info_end_of_survey": {"type": "string"},
    "blood_barcode_confirmation": {"type": "string"},
    "blood_barcode_user_entered": {"type": "string"},
    "blood_taken_date": {"type": "string"},
    "blood_taken_time_hour": {"type": "string"},
    "blood_taken_time_minute": {"type": "string"},
    "blood_taken_am_pm": {"type": "string"},
    "blood_returned": {"type": "string"},
    "blood_return_date": {"type": "string"},
    "blood_return_future_date": {"type": "string"},
    "aged_16_or_over": {"type": "string"},
    "work_status_digital": {"type": "string"},
    "work_status_employment": {"type": "string"},
    "work_status_unemployment": {"type": "string"},
    "work_status_education": {"type": "string"},
    "work_in_additional_paid_employment": {"type": "string"},
    "work_main_job_changed": {"type": "string"},
    "work_main_job_title": {"type": "string"},
    "work_main_job_role": {"type": "string"},
    "work_sector": {"type": "string"},
    "work_sector_other": {"type": "string"},
    "work_health_care_area": {"type": "string"},
    "work_nursing_or_residential_care_home": {"type": "string"},
    "work_direct_contact_patients_or_clients": {"type": "string"},
    "work_location": {"type": "string"},
    "work_not_from_home_days_per_week": {"type": "string"},
    "education_in_person_days_per_week": {"type": "string"},
    "transport_to_work_or_education": {"type": "string"},
    "ability_to_socially_distance_at_work_or_education": {"type": "string"},
    "think_have_covid_symptom_runny_nose_or_sneezing": {"type": "string"},
    "think_have_covid_symptom_loss_of_smell": {"type": "string"},
    "think_have_covid_symptom_loss_of_taste": {"type": "string"},
    "think_have_covid_symptom_sore_throat": {"type": "string"},
    "think_have_covid_symptom_cough": {"type": "string"},
    "think_have_covid_symptom_shortness_of_breath": {"type": "string"},
    "think_have_covid_symptom_noisy_breathing": {"type": "string"},
    "think_have_covid_symptom_abdominal_pain": {"type": "string"},
    "think_have_covid_symptom_nausea_or_vomiting": {"type": "string"},
    "think_have_covid_symptom_diarrhoea": {"type": "string"},
    "think_have_covid_symptom_loss_of_appetite": {"type": "string"},
    "no_symptoms_list_1": {"type": "string"},
    "think_have_covid_symptom_muscle_ache": {"type": "string"},
    "think_have_covid_symptom_fatigue": {"type": "string"},
    "think_have_covid_symptom_fever": {"type": "string"},
    "think_have_covid_symptom_more_trouble_sleeping": {"type": "string"},
    "think_have_covid_symptom_memory_loss_or_confusion": {"type": "string"},
    "think_have_covid_symptom_difficulty_concentrating": {"type": "string"},
    "think_have_covid_symptom_anxiety": {"type": "string"},
    "think_have_covid_symptom_low_mood": {"type": "string"},
    "no_symptoms_list_2": {"type": "string"},
    "think_have_covid_symptom_onset_date": {"type": "string"},
    "illness_lasting_over_12_months": {"type": "string"},
    "illness_reduces_activity_or_ability": {"type": "string"},
    "ever_smoked_regularly": {"type": "string"},
    "currently_smokes_or_vapes": {"type": "string"},
    "currently_smokes_or_vapes_cigarettes": {"type": "string"},
    "currently_smokes_or_vapes_cigars": {"type": "string"},
    "currently_smokes_or_vapes_pipes": {"type": "string"},
    "currently_smokes_or_vapes_vapes": {"type": "string"},
    "currently_smokes_or_vapes_hookah": {"type": "string"},
    "cis_covid_vaccine_received": {"type": "string"},
    "cis_covid_vaccine_type": {"type": "string"},
    "cis_covid_vaccine_type_other": {"type": "string"},
    "cis_covid_vaccine_number_of_doses": {"type": "string"},
    "cis_covid_vaccine_date": {"type": "string"},
    "flu_vaccination_received": {"type": "string"},
    "flu_vaccination_received_date": {"type": "string"},
    "been_outside_uk": {"type": "string"},
    "been_outside_uk_last_country": {"type": "string"},
    "been_outside_uk_last_return_date": {"type": "string"},
    "PHM_think_had_respiratory_infection": {"type": "string"},
    "PHM_think_had_respiratory_infection_type_covid": {"type": "string"},
    "PHM_think_had_respiratory_infection_type_flu": {"type": "string"},
    "PHM_think_had_respiratory_infection_type_other": {"type": "string"},
    "PHM_think_had_respiratory_infection_type_dont_know": {"type": "string"},
    "think_had_covid_onset_date": {"type": "string"},
    "think_had_covid_symptom_runny_nose_or_sneezing": {"type": "string"},
    "think_had_covid_symptom_loss_of_smell": {"type": "string"},
    "think_had_covid_symptom_loss_of_taste": {"type": "string"},
    "think_had_covid_symptom_sore_throat": {"type": "string"},
    "think_had_covid_symptom_cough": {"type": "string"},
    "think_had_covid_symptom_shortness_of_breath": {"type": "string"},
    "think_had_covid_symptom_noisy_breathing": {"type": "string"},
    "think_had_covid_symptom_abdominal_pain": {"type": "string"},
    "think_had_covid_symptom_nausea_or_vomiting": {"type": "string"},
    "think_had_covid_symptom_diarrhoea": {"type": "string"},
    "think_had_covid_symptom_loss_of_appetite": {"type": "string"},
    "think_had_covid_symptom_list_1_none": {"type": "string"},
    "think_had_covid_symptom_headache": {"type": "string"},
    "think_had_covid_symptom_muscle_ache": {"type": "string"},
    "think_had_covid_symptom_fatigue": {"type": "string"},
    "think_had_covid_symptom_fever": {"type": "string"},
    "think_had_covid_symptom_more_trouble_sleeping": {"type": "string"},
    "think_had_covid_symptom_memory_loss_or_confusion": {"type": "string"},
    "think_had_covid_symptom_difficulty_concentrating": {"type": "string"},
    "think_had_covid_symptom_anxiety": {"type": "string"},
    "think_had_covid_symptom_low_mood": {"type": "string"},
    "think_had_covid_symptom_list_2_none": {"type": "string"},
    "PHM_think_had_flu_onset_date": {"type": "string"},
    "think_had_flu_symptom_runny_nose_or_sneezing": {"type": "string"},
    "think_had_flu_symptom_loss_of_smell": {"type": "string"},
    "think_had_flu_symptom_loss_of_taste": {"type": "string"},
    "think_had_flu_symptom_sore_throat": {"type": "string"},
    "think_had_flu_symptom_cough": {"type": "string"},
    "think_had_flu_symptom_shortness_of_breath": {"type": "string"},
    "think_had_flu_symptom_noisy_breathing": {"type": "string"},
    "think_had_flu_symptom_abdominal_pain": {"type": "string"},
    "think_had_flu_symptom_nausea_or_vomiting": {"type": "string"},
    "think_had_flu_symptom_diarrhoea": {"type": "string"},
    "think_had_flu_symptom_loss_of_appetite": {"type": "string"},
    "think_had_flu_symptom_list_1_none": {"type": "string"},
    "think_had_flu_symptom_headache": {"type": "string"},
    "think_had_flu_symptom_muscle_ache": {"type": "string"},
    "think_had_flu_symptom_fatigue": {"type": "string"},
    "think_had_flu_symptom_fever": {"type": "string"},
    "think_had_flu_symptom_more_trouble_sleeping": {"type": "string"},
    "think_had_flu_symptom_memory_loss_or_confusion": {"type": "string"},
    "think_had_flu_symptom_difficulty_concentrating": {"type": "string"},
    "think_had_flu_symptom_anxiety": {"type": "string"},
    "think_had_flu_symptom_low_mood": {"type": "string"},
    "think_had_flu_symptom_list_2_none": {"type": "string"},
    "PHM_think_had_other_infection_onset_date": {"type": "string"},
    "think_had_other_infection_symptom_runny_nose_or_sneezing": {"type": "string"},
    "think_had_other_infection_symptom_loss_of_smell": {"type": "string"},
    "think_had_other_infection_symptom_loss_of_taste": {"type": "string"},
    "think_had_other_infection_symptom_sore_throat": {"type": "string"},
    "think_had_other_infection_symptom_cough": {"type": "string"},
    "think_had_other_infection_symptom_shortness_of_breath": {"type": "string"},
    "think_had_other_infection_symptom_noisy_breathing": {"type": "string"},
    "think_had_other_infection_symptom_abdominal_pain": {"type": "string"},
    "think_had_other_infection_symptom_nausea_or_vomiting": {"type": "string"},
    "think_had_other_infection_symptom_diarrhoea": {"type": "string"},
    "think_had_other_infection_symptom_loss_of_appetite": {"type": "string"},
    "think_had_other_infection_symptom_list_1_none": {"type": "string"},
    "think_had_other_infection_symptom_headache": {"type": "string"},
    "think_had_other_infection_symptom_muscle_ache": {"type": "string"},
    "think_had_other_infection_symptom_fatigue": {"type": "string"},
    "think_had_other_infection_symptom_fever": {"type": "string"},
    "think_had_other_infection_symptom_more_trouble_sleeping": {"type": "string"},
    "think_had_other_infection_symptom_memory_loss_or_confusion": {"type": "string"},
    "think_had_other_infection_symptom_difficulty_concentrating": {"type": "string"},
    "think_had_other_infection_symptom_anxiety": {"type": "string"},
    "think_had_other_infection_symptom_low_mood": {"type": "string"},
    "think_had_other_infection_symptom_list_2_none": {"type": "string"},
    "other_covid_infection_test": {"type": "string"},
    "test_type_positive_result": {"type": "string"},
    "other_covid_infection_test_results": {"type": "string"},
    "other_covid_infection_test_positive_date": {"type": "string"},
    "other_covid_infection_test_negative_date": {"type": "string"},
    "last_28_days_unable_usual_activites": {"type": "string"},
    "last_28_days_unable_usual_activites_due_to_respiratory_infection": {"type": "string"},
    "last_28_days_off_work_education_due_to_health": {"type": "string"},
    "last_28_days_off_work_education_due_to_health_respiratory_infection": {"type": "string"},
    "last_28_days_GP_appointment_health_reasons": {"type": "string"},
    "last_28_days_GP_appointment_health_reasons_respiratory_infection": {"type": "string"},
    "last_28_days_pharmacist_111": {"type": "string"},
    "last_28_days_pharmacist_111_respiratory_infection": {"type": "string"},
    "last_28_days_urgent_care": {"type": "string"},
    "last_28_days_urgent_care_respiratory_infection": {"type": "string"},
    "last_28_days_admitted_to_hospital": {"type": "string"},
    "think_have_long_covid": {"type": "string"},
    "think_have_long_covid_symptom_reduced_ability": {"type": "string"},
    "think_have_long_covid_symptom_headache": {"type": "string"},
    "think_have_long_covid_symptom_eyesight_sore_eyes": {"type": "string"},
    "think_have_long_covid_symptom_tinnitus_hearing_problems": {"type": "string"},
    "think_have_long_covid_symptom_ear_pain": {"type": "string"},
    "think_have_long_covid_symptom_runny_nose_or_sneezing": {"type": "string"},
    "think_have_long_covid_symptom_nasal_congestion": {"type": "string"},
    "think_have_long_covid_symptom_sore_throat": {"type": "string"},
    "think_have_long_covid_symptom_cough": {"type": "string"},
    "think_have_long_covid_symptom_shortness_of_breath": {"type": "string"},
    "think_have_long_covid_symptom_noisy_breathing": {"type": "string"},
    "think_have_long_covid_symptom_chest_pain": {"type": "string"},
    "think_have_long_covid_symptom_palpitations": {"type": "string"},
    "think_have_long_covid_symptom_list_1_none": {"type": "string"},
    "think_have_long_covid_symptom_nausea_or_vomiting": {"type": "string"},
    "think_have_long_covid_symptom_abdominal_pain": {"type": "string"},
    "think_have_long_covid_symptom_diarrhoea": {"type": "string"},
    "think_have_long_covid_symptom_loss_of_appetite": {"type": "string"},
    "think_have_long_covid_symptom_muscle_ache": {"type": "string"},
    "think_have_long_covid_symptom_joint_pain": {"type": "string"},
    "think_have_long_covid_symptom_mobility_problems": {"type": "string"},
    "think_have_long_covid_symptom_loss_of_taste": {"type": "string"},
    "think_have_long_covid_symptom_loss_of_smell": {"type": "string"},
    "think_have_long_covid_symptom_memory_loss_or_confusion": {"type": "string"},
    "think_have_long_covid_symptom_difficulty_concentrating": {"type": "string"},
    "think_have_long_covid_symptom_list_2_none": {"type": "string"},
    "think_have_long_covid_symptom_more_trouble_sleeping": {"type": "string"},
    "think_have_long_covid_symptom_anxiety": {"type": "string"},
    "think_have_long_covid_symptom_low_mood": {"type": "string"},
    "think_have_long_covid_symptom_fatigue": {"type": "string"},
    "think_have_long_covid_symptom_fever": {"type": "string"},
    "think_have_long_covid_symptom_general_pain": {"type": "string"},
    "think_have_long_covid_symptom_vertigo_or_dizziness": {"type": "string"},
    "think_have_long_covid_symptom_allergies_intolerances": {"type": "string"},
    "think_have_long_covid_symptom_hair_loss": {"type": "string"},
    "think_have_long_covid_symptom_pins_needles_numbness": {"type": "string"},
    "think_have_long_covid_symptom_rashes_itchy_skin": {"type": "string"},
    "think_have_long_covid_symptom_list_3_none": {"type": "string"},
    "think_have_long_covid_symptom_worse_after_effort": {"type": "string"},
    "other_household_member_hospital_last_28_days": {"type": "string"},
    "care_home_last_28_days": {"type": "string"},
    "hours_a_day_with_someone_else_at_home_number": {"type": "integer"},
    "hours_a_day_with_someone_else_at_home_string": {"type": "integer"},
    "physical_contact_under_18_years": {"type": "string"},
    "physical_contact_18_to_69_years": {"type": "string"},
    "physical_contact_over_70_years": {"type": "string"},
    "social_distance_contact_under_18_years": {"type": "string"},
    "social_distance_contact_18_to_69_years": {"type": "string"},
    "social_distance_contact_over_70_years": {"type": "string"},
    "times_hour_or_longer_another_home_last_7_days": {"type": "string"},
    "times_hour_or_longer_another_person_your_home_last_7_days": {"type": "string"},
    "times_shopping_last_7_days": {"type": "string"},
    "times_socialise_last_7_days": {"type": "integer"},
    "times_indoor_exercise_last_28_days": {"type": "integer"},
    "times_large_events_last_28_days": {"type": "integer"},
    "times_medium_events_last_28_days": {"type": "integer"},
    "transport_shared_outside_household_last_28_days_underground_tram": {"type": "string"},
    "transport_shared_outside_household_last_28_days_train": {"type": "string"},
    "transport_shared_outside_household_last_28_days_bus_coach": {"type": "string"},
    "transport_shared_outside_household_last_28_days_car_van": {"type": "string"},
    "transport_shared_outside_household_last_28_days_taxi": {"type": "string"},
    "transport_shared_outside_household_last_28_days_plane": {"type": "string"},
    "transport_shared_outside_household_last_28_days_ferry_boat": {"type": "string"},
    "transport_shared_outside_household_last_28_days_other": {"type": "string"},
    "transport_shared_outside_household_last_28_days_none": {"type": "string"},
    "face_covering_other_enclosed_places": {"type": "string"},
    "end_screen_questionnaire": {"type": "string"},
    "end_screen_sample": {"type": "string"},
    "survey_completion_window_start_datetime": {"type": "string"},
    "survey_language_submitted": {"type": "string"},
}
