from cishouseholds.pipeline.validation_schema import validation_schemas

d_schema = validation_schemas["cis_digital_validation_schema"]

lookup = {
    "PHM-FUP-INT-002": "uac",
    "PHM-FUP-INT-003": "participant_first_name_confirmation",
    "PHM-FUP-INT-004": "participant_first_name_on_behalf",
    "PHM-FUP-INT-005": "problem_with_survey_access_helpline",
    "PHM-FUP-INT-006": "cohort_type_PHM",
    "PHM-FUP-SAM-001": "swab_taken",
    "PHM-FUP-SAM-002": "swab_not_taken_reason",
    "PHM-FUP-SAM-003": "swab_barcode_confirmation",
    "PHM-FUP-SAM-004": "swab_sample_barcode_user_entered",
    "PHM-FUP-SAM-005": "swab_taken_date",
    "PHM-FUP-SAM-006": "swab_taken_time_hour",
    "PHM-FUP-SAM-007": "swab_taken_time_minute",
    "PHM-FUP-SAM-008": "swab_taken_am_pm",
    "PHM-FUP-SAM-009": "swab_returned_PHM",
    "PHM-FUP-SAM-010": "swab_return_date",
    "PHM-FUP-SAM-011": "swab_return_future_date",
    "PHM-FUP-SAM-012": "blood_taken",
    "PHMFUP-SAM-013": "blood_not_taken_reason",
    "PHM-FUP-SAM-014": "blood_not_taken_could_not_reason",
    "PHM-FUP-SAM-015": "blood_not_taken_could_not_other",
    "PHM-FUP-SAM-016": "blood_barcode_confirmation",
    "PHM-FUP-SAM-017": "blood_barcode_user_entered",
    "PHM-FUP-SAM-018": "blood_taken_date",
    "PHM-FUP-SAM-019": "blood_taken_time_hour",
    "PHM-FUP-SAM-020": "blood_taken_time_minute",
    "PHM-FUP-SAM-021": "blood_taken_am_pm",
    "PHM-FUP-SAM-022": "blood_returned",
    "PHM-FUP-SAM-023": "blood_return_date",
    "PHM-FUP-SAM-024": "blood_return_future_date",
    "PHM-FUP-SAM-025": "questionnaire_started_no_incentive",
    "PHM-FUP-SAM-026": "test_kit_info_end_of_survey",
    "PHM-FUP-WE-001": "aged_16_or_over",
    "PHM-FUP-WE-002": "work_status_digital",
    "PHM-FUP-WE-003": "work_status_employment",
    "PHM-FUP-WE-004": "work_status_unemployment",
    "PHM-FUP-WE-005": "work_status_education",
    "PHM-FUP-WE-006": "work_in_additional_paid_employment",
    "PHM-FUP-WE-007": "work_main_job_changed",
    "PHM-FUP-WE-008": "work_main_job_title",
    "PHM-FUP-WE-009": "work_main_job_role",
    "PHM-FUP-WE-010": "work_sector",
    "PHM-FUP-WE-011": "work_sector_other",
    "PHM-FUP-WE-012": "work_health_care_area",
    "PHM-FUP-WE-013": "work_nursing_or_residential_care_home",
    "PHM-FUP-WE-014": "work_direct_contact_patients_or_clients",
    "PHM-FUP-WE-015": "work_location",
    "PHM-FUP-WE-016": "work_not_from_home_days_per_week",
    "PHM-FUP-WE-017": "education_in_person_days_per_week",
    "PHM-FUP-WE-018": "transport_to_work_or_education",
    "PHM-FUP-WE-019": "ability_to_socially_distance_at_work_or_education",
    "PHM-FUP-HST-001": "think_have_covid_any_symptom_list_1",
    "PHM-FUP-HST-002": "think_have_covid_no_symptoms_list_",
    # "PHM-FUP-HST-013": "confirm_symptoms_list_1",
    "PHM-FUP-HST-003": "think_have_covid_any_symptom_list_2",
    "PHM-FUP-HST-004": "think_have_covid_no_symptoms_list_2",
    # "PHM-FUP-HST-023": "confirm_symptoms_list_2",
    "PHM-FUP-HST-005": "think_have_symptoms_new_or_worse_list1",
    "PHM-FUP-HST-006": "think_have_symptoms_new_or_worse_none_list1",
    "PHM-FUP-HST-007": "think_have_symptoms_new_or_worse_list2",
    "PHM-FUP-HST-008": "think_have_symptoms_new_or_worse_none_list2",
    "PHM-FUP-HST-009": "think_have_covid_symptom_onset_date",
    "PHM-FUP-HST-010": "illness_lasting_over_12_months",
    "PHM-FUP-HST-011": "illness_reduces_activity_or_ability",
    "PHM-FUP-HST-012": "ever_smoked_regularly",
    "PHM-FUP-HST-013": "currently_smokes_or_vapes",
    "PHM-FUP-HST-014": "currently_smokes_or_vapes_type",
    "PHM-FUP-HST-015": "cis_covid_vaccine_received",
    "PHM-FUP-HST-016": "cis_covid_vacine_type",
    "PHM-FUP-HST-017": "cis_covid_vaccine_type_other",
    "PHM-FUP-HST-018": "cis_covid_vaccine_number_of_doses",
    "PHM-FUP-HST-019": "cis_covid_vaccine_date",
    "PHM-FUP-HST-020": "flu_vaccination_received",
    "PHM-FUP-HST-021": "flu_vaccination_received_date",
    "PHM-FUP-HST-022": "been_outside_uk",
    "PHM-FUP-HST-023": "been_outside_uk_last_country",
    "PHM-FUP-HST-024": "been_outside_uk_last_return_date",
    "PHM-FUP-C19-001": "PHM_think_had_respiratory_infection",
    "PHM-FUP-C19-002": "PHM_think_had_respiratory_infection_type",
    "PHM-FUP-C19-003": "think_had_covid_onset_date",
    "PHM-FUP-C19-004": "think_had_covid_symptom_list_1",
    "PHM-FUP-C19-005": "think_had_covid_symptom_none_list_1",
    "PHM-FUP-C19-006": "think_had_covid_symptom_list_2",
    "PHM-FUP-C19-007": "think_had_covid_symptom_none_list_2",
    "PHM-FUP-C19-008": "PHM_think_had_flu_onset_date",
    "PHM-FUP-C19-009": "think_had_flu_symptom_list_1",
    "PHM-FUP-C19-010": "think_had_flu_symptom_none_list_1",
    "PHM-FUP-C19-011": "think_had_flu_symptom_list_2",
    "PHM-FUP-C19-012": "think_had_flu_symptom_list_none_2",
    "PHM-FUP-C19-013": "PHM_think_had_other_infection_onset_date",
    "PHM-FUP-C19-014": "think_had_other_infection_symptom_list_1",
    "PHM-FUP-C19-015": "think_had_other_infection_symptom_none_list_1",
    "PHM-FUP-C19-016": "think_had_other_infection_symptom_list_2",
    "PHM-FUP-C19-017": "think_had_other_infection_symptom_none_list_2",
    "PHM-FUP-C19-018": "other_covid_infection_test",
    "PHM-FUP-C19-019": "other_covid_infection_test_results",
    "PHM-FUP-C19-020": "other_covid_infection_test_positive_date",
    "PHM-FUP-C19-021": "test_type_positive_result",
    "PHM-FUP-C19-022": "last_28_days_unable_usual_activites",
    "PHM-FUP-C19-023": "last_28_days_unable_usual_activites_due_to_respiratory_infection",
    "PHM-FUP-C19-024": "last_28_days_off_work_education_due_to_health",
    "PHM-FUP-C19-025": "last_28_days_off_work_education_due_to_health_respiratory_infection",
    "PHM-FUP-C19-026": "last_28_days_GP_appointment_health_reasons",
    "PHM-FUP-C19-027": "last_28_days_GP_appointment_health_reasons_respiratory_infection",
    "PHM-FUP-C19-028": "last_28_days_pharmacist_111",
    "PHM-FUP-C19-029": "last_28_days_pharmacist_111_respiratory_infection",
    "PHM-FUP-C19-030": "last_28_days_urgent_care",
    "PHM-FUP-C19-031": "last_28_days_urgent_care_respiratory_infection",
    "PHM-FUP-C19-032": "last_28_days_admitted_to_hospital",
    "PHM-FUP-C19-033": "last_28_days_admitted_to_hospital",
    "PHM-FUP-C19-034": "think_have_long_covid",
    "PHM-FUP-C19-035": "think_have_long_covid_symptom_reduced_ability",
    "PHM-FUP-C19-036": "think_have_long_covid_symptom_list_1",
    "PHM-FUP-C19-038": "think_have_long_covid_symptom_list_2",
    "PHM-FUP-C19-040": "think_have_long_covid_symptom_list_3",
    # "PHM-FUP-C19-038": "other_antibody_test_results",
    "PHM-FUP-C19-039": "other_antibody_test_positive_date",
    # "PHM-FUP-C19-040": "other_antibody_test_negative_date",
    "PHM-FUP-C19-042": "think_have_long_covid_symptom_worse_after_effort",
    "PHM-FUP-CON-001": "hospital_last_28_days",
    "PHM-FUP-CON-002": "care_home_last_28_days",
    "PHM-FUP-CON-003": "face_covering_other_enclosed_places",
    "PHM-FUP-CON-004": "physical_contact_under_18_years",
    "PHM-FUP-CON-005": "physical_contact_18_to_69_years",
    "PHM-FUP-CON-006": "physical_contact_over_70_years",
    "PHM-FUP-CON-007": "social_distance_contact_under_18_years",
    "PHM-FUP-CON-008": "social_distance_contact_18_to_69_years",
    "PHM-FUP-CON-009": "social_distance_contact_over_70_years",
    "PHM-FUP-CON-010": "times_hour_or_longer_another_home_last_7_days",
    "PHM-FUP-CON-011": "times_hour_or_longer_another_person_your_home_last_7_days",
    "PHM-FUP-CON-012": "times_shopping_last_7_days",
    "PHM-FUP-CON-013": "times_socialise_last_7_days",
    "PHM-FUP-CON-014": "times_indoor_exercise_last_28_days",
    "PHM-FUP-CON-015": "times_large_events_last_28_days",
    "PHM-FUP-CON-016": "times_medium_events_last_28_days",
    "PHM-FUP-CON-018": "transport_shared_outside_household_last_28_days_none",
    "PHM-FUP-CON-019": "face_covering_work_or_education",
    "PHM-FUP-END-001": "end_screen_questionnaire",
    "PHM-FUP-END-002": "end_screen_sample",
    "PARTICIPANT_ID": "participant_id",
    "BLOOD_TEST_BARCODE": "blood_sample_barcode",
    "SWAB_TEST_BARCODE": "swab_sample_barcode",
}


phm_validation_schema = {
    "think_had_covid_symptom_list_1": {"type": {"containsNull": False, "elementType": "string", "type": "array"}},
    "think_had_covid_symptom_list_2": {"type": {"containsNull": False, "elementType": "string", "type": "array"}},
    "think_had_covid_symptom_list_3": {"type": {"containsNull": False, "elementType": "string", "type": "array"}},
    "case_id": {"type": "string"},
    "survey_id": {"type": "string"},
    "submitted_at": {"type": "string"},
    "participant_first_name_confirmation": {"type": "string"},
    "swab_taken": {"type": "string"},
    "swab_not_taken_reason": {"type": "string"},
    "swab_barcode_confirmation": {"type": "string"},
    "swab_sample_barcode_user_entered": {"type": "string"},
    "swab_taken_date": {"type": "string"},
    "swab_taken_time_hour": {"type": "integer"},
    "swab_taken_time_minute": {"type": "integer"},
    "swab_taken_am_pm": {"type": "string"},
    "swab_return_date": {"type": "string"},
    "swab_return_future_date": {"type": "string"},
    "blood_taken": {"type": "string"},
    "blood_not_taken_reason": {"type": "string"},
    "blood_not_taken_could_not_other": {"type": "string"},
    "questionnaire_started_no_incentive": {"type": "string"},
    "test_kit_info_end_of_survey": {"type": "string"},
    "blood_barcode_confirmation": {"type": "string"},
    "blood_barcode_user_entered": {"type": "string"},
    "blood_taken_date": {"type": "string"},
    "blood_taken_time_hour": {"type": "string"},
    "blood_taken_time_minute": {"type": "string"},
    "blood_taken_am_pm": {"type": "string"},
    "blood_returned": {"type": "string"},
    "blood_return_date": {"type": "string"},
    "blood_return_future_date": {"type": "string"},
    "aged_16_or_over": {"type": "string"},
    "work_status_digital": {"type": "string"},
    "work_status_employment": {"type": "string"},
    "work_status_unemployment": {"type": "string"},
    "work_status_education": {"type": "string"},
    "work_in_additional_paid_employment": {"type": "string"},
    "work_main_job_changed": {"type": "string"},
    "work_main_job_title": {"type": "string"},
    "work_main_job_role": {"type": "string"},
    "work_sector": {"type": "string"},
    "work_sector_other": {"type": "string"},
    "work_health_care_area": {"type": "string"},
    "work_nursing_or_residential_care_home": {"type": "string"},
    "work_direct_contact_patients_or_clients": {"type": "string"},
    "work_location": {"type": "string"},
    "work_not_from_home_days_per_week": {"type": "string"},
    "education_in_person_days_per_week": {"type": "string"},
    "transport_to_work_or_education": {"type": "string"},
    "ability_to_socially_distance_at_work_or_education": {"type": "string"},
    "think_have_covid_symptom_onset_date": {"type": "string"},
    "illness_lasting_over_12_months": {"type": "string"},
    "illness_reduces_activity_or_ability": {"type": "string"},
    "ever_smoked_regularly": {"type": "string"},
    "currently_smokes_or_vapes": {"type": "string"},
    "cis_covid_vaccine_received": {"type": "string"},
    "cis_covid_vaccine_type_other": {"type": "string"},
    "cis_covid_vaccine_number_of_doses": {"type": "string"},
    "cis_covid_vaccine_date": {"type": "string"},
    "flu_vaccination_received": {"type": "string"},
    "flu_vaccination_received_date": {"type": "string"},
    "been_outside_uk": {"type": "string"},
    "been_outside_uk_last_country": {"type": "string"},
    "been_outside_uk_last_return_date": {"type": "string"},
    "PHM_think_had_respiratory_infection": {"type": "string"},
    "think_had_covid_onset_date": {"type": "string"},
    "PHM_think_had_flu_onset_date": {"type": "string"},
    "PHM_think_had_other_infection_onset_date": {"type": "string"},
    "other_covid_infection_test": {"type": "string"},
    "test_type_positive_result": {"type": "string"},
    "other_covid_infection_test_results": {"type": "string"},
    "other_covid_infection_test_positive_date": {"type": "string"},
    "last_28_days_unable_usual_activites": {"type": "string"},
    "last_28_days_unable_usual_activites_due_to_respiratory_infection": {"type": "string"},
    "last_28_days_off_work_education_due_to_health": {"type": "string"},
    "last_28_days_off_work_education_due_to_health_respiratory_infection": {"type": "string"},
    "last_28_days_GP_appointment_health_reasons": {"type": "string"},
    "last_28_days_GP_appointment_health_reasons_respiratory_infection": {"type": "string"},
    "last_28_days_pharmacist_111": {"type": "string"},
    "last_28_days_pharmacist_111_respiratory_infection": {"type": "string"},
    "last_28_days_urgent_care": {"type": "string"},
    "last_28_days_urgent_care_respiratory_infection": {"type": "string"},
    "last_28_days_admitted_to_hospital": {"type": "string"},
    "think_have_long_covid": {"type": "string"},
    "think_have_long_covid_symptom_reduced_ability": {"type": "string"},
    "think_have_long_covid_symptom_worse_after_effort": {"type": "string"},
    "care_home_last_28_days": {"type": "string"},
    "physical_contact_under_18_years": {"type": "string"},
    "physical_contact_18_to_69_years": {"type": "string"},
    "physical_contact_over_70_years": {"type": "string"},
    "social_distance_contact_under_18_years": {"type": "string"},
    "social_distance_contact_18_to_69_years": {"type": "string"},
    "social_distance_contact_over_70_years": {"type": "string"},
    "times_hour_or_longer_another_home_last_7_days": {"type": "string"},
    "times_hour_or_longer_another_person_your_home_last_7_days": {"type": "string"},
    "times_shopping_last_7_days": {"type": "string"},
    "times_socialise_last_7_days": {"type": "integer"},
    "times_indoor_exercise_last_28_days": {"type": "integer"},
    "times_large_events_last_28_days": {"type": "integer"},
    "times_medium_events_last_28_days": {"type": "integer"},
    "transport_shared_outside_household_last_28_days_none": {"type": "string"},
    "face_covering_other_enclosed_places": {"type": "string"},
    "end_screen_questionnaire": {"type": "string"},
    "end_screen_sample": {"type": "string"},
}
