from typing import Dict

_times_in_last_7_day_categories = {
    "None": 0,
    "1": 1,
    "2": 2,
    "3": 3,
    "4": 4,
    "5": 5,
    "6": 6,
    "7 times or more": 7,
}

_yes_no_categories = {"No": 0, "Yes": 1}

category_maps = {
    "iqvia_raw_category_map": {
        "agreed_to_additional_consent_visit": _yes_no_categories,
        "consent_blood_samples_if_positive_yn": _yes_no_categories,
        "consent_contact_extra_research_yn": _yes_no_categories,
        "consent_finger_prick_a1_a3": _yes_no_categories,
        "consent_blood_samples_if_positive_yn": _yes_no_categories,
        "consent_extend_study_under_16_b1_b3": _yes_no_categories,
        "consent_fingerprick_blood_samples": {"false": 0, "true": 1},
        "reconsented_blood": {"false": 0, "true": 1},
        "consent_extend_study_under_16_b1_b3": _yes_no_categories,
        "consent_use_of_surplus_blood_samples_yn": _yes_no_categories,
        "consent_blood_samples_if_positive": {"false": 0, "true": 1},
        "swab_taken": _yes_no_categories,
        "blood_taken": _yes_no_categories,
        "illness_lasting_over_12_months": _yes_no_categories,
        "ever_smoked_regularly": _yes_no_categories,
        "smoke_cigarettes": _yes_no_categories,
        "smokes_cigar": _yes_no_categories,
        "smokes_pipe": _yes_no_categories,
        "smokes_vape_e_cigarettes": _yes_no_categories,
        "smokes_hookah_shisha_pipes": _yes_no_categories,
        "smokes_nothing_now": _yes_no_categories,
        "work_nursing_or_residential_care_home": _yes_no_categories,
        "work_direct_contact_patients_or_clients": _yes_no_categories,
        "think_have_covid_symptom_any": _yes_no_categories,
        "think_have_covid_symptom_fever": _yes_no_categories,
        "think_have_covid_symptom_muscle_ache": _yes_no_categories,
        "think_have_covid_symptom_fatigue": _yes_no_categories,
        "think_have_covid_symptom_sore_throat": _yes_no_categories,
        "think_have_covid_symptom_cough": _yes_no_categories,
        "think_have_covid_symptom_shortness_of_breath": _yes_no_categories,
        "think_have_covid_symptom_headache": _yes_no_categories,
        "think_have_covid_symptom_nausea_or_vomiting": _yes_no_categories,
        "think_have_covid_symptom_abdominal_pain": _yes_no_categories,
        "think_have_covid_symptom_diarrhoea": _yes_no_categories,
        "think_have_covid_symptom_loss_of_taste": _yes_no_categories,
        "think_have_covid_symptom_loss_of_smell": _yes_no_categories,
        "think_have_covid_symptom_more_trouble_sleeping": _yes_no_categories,
        "think_have_covid_symptom_runny_nose_or_sneezing": _yes_no_categories,
        "think_have_covid_symptom_noisy_breathing": _yes_no_categories,
        "think_have_covid_symptom_loss_of_appetite": _yes_no_categories,
        "think_have_covid_symptom_chest_pain": _yes_no_categories,
        "think_have_covid_symptom_palpitations": _yes_no_categories,
        "think_have_covid_symptom_vertigo_or_dizziness": _yes_no_categories,
        "think_have_covid_symptom_anxiety": _yes_no_categories,
        "think_have_covid_symptom_low_mood": _yes_no_categories,
        "think_have_covid_symptom_memory_loss_or_confusion": _yes_no_categories,
        "think_have_covid_symptom_difficulty_concentrating": _yes_no_categories,
        "think_have_covid": _yes_no_categories,
        "self_isolating": _yes_no_categories,
        "received_shielding_letter": _yes_no_categories,
        "contact_known_positive_covid_last_28_days": _yes_no_categories,
        "contact_suspected_positive_covid_last_28_days": _yes_no_categories,
        "hospital_last_28_days": _yes_no_categories,
        "other_household_member_hospital_last_28_days": _yes_no_categories,
        "care_home_last_28_days": _yes_no_categories,
        "other_household_member_care_home_last_28_days": _yes_no_categories,
        "think_had_covid": _yes_no_categories,
        "think_had_covid_contacted_nhs": _yes_no_categories,
        "think_had_covid_admitted_to_hospital": _yes_no_categories,
        "think_had_covid_any_symptoms": _yes_no_categories,
        "think_had_covid_symptom_fever": _yes_no_categories,
        "think_had_covid_symptom_muscle_ache": _yes_no_categories,
        "think_had_covid_symptom_fatigue": _yes_no_categories,
        "think_had_covid_symptom_sore_throat": _yes_no_categories,
        "think_had_covid_symptom_cough": _yes_no_categories,
        "think_had_covid_symptom_shortness_of_breath": _yes_no_categories,
        "think_had_covid_symptom_headache": _yes_no_categories,
        "think_had_covid_symptom_nausea_or_vomiting": _yes_no_categories,
        "think_had_covid_symptom_abdominal_pain": _yes_no_categories,
        "think_had_covid_symptom_diarrhoea": _yes_no_categories,
        "think_had_covid_symptom_loss_of_taste": _yes_no_categories,
        "think_had_covid_symptom_loss_of_smell": _yes_no_categories,
        "think_had_covid_symptom_more_trouble_sleeping": _yes_no_categories,
        "think_had_covid_symptom_runny_nose_or_sneezing": _yes_no_categories,
        "think_had_covid_symptom_noisy_breathing": _yes_no_categories,
        "think_had_covid_symptom_loss_of_appetite": _yes_no_categories,
        "think_had_covid_symptom_chest_pain": _yes_no_categories,
        "think_had_covid_symptom_palpitations": _yes_no_categories,
        "think_had_covid_symptom_vertigo_or_dizziness": _yes_no_categories,
        "think_had_covid_symptom_anxiety": _yes_no_categories,
        "think_had_covid_symptom_low_mood": _yes_no_categories,
        "think_had_covid_symptom_memory_loss_or_confusion": _yes_no_categories,
        "think_had_covid_symptom_difficulty_concentrating": _yes_no_categories,
        "think_had_covid_symptom_low_mood": _yes_no_categories,
        "other_covid_infection_test": _yes_no_categories,
        "other_antibody_test": _yes_no_categories,
        "been_outside_uk": _yes_no_categories,
        "think_have_long_covid": _yes_no_categories,
        "think_have_long_covid_symptom_fever": _yes_no_categories,
        "think_have_long_covid_symptom_fatigue": _yes_no_categories,
        "think_have_long_covid_symptom_diarrhoea": _yes_no_categories,
        "think_have_long_covid_symptom_loss_of_smell": _yes_no_categories,
        "think_have_long_covid_symptom_shortness_of_breath": _yes_no_categories,
        "think_have_long_covid_symptom_vertigo_or_dizziness": _yes_no_categories,
        "think_have_long_covid_symptom_more_trouble_sleeping": _yes_no_categories,
        "think_have_long_covid_symptom_headache": _yes_no_categories,
        "think_have_long_covid_symptom_nausea_or_vomiting": _yes_no_categories,
        "think_have_long_covid_symptom_loss_of_appetite": _yes_no_categories,
        "think_have_long_covid_symptom_sore_throat": _yes_no_categories,
        "think_have_long_covid_symptom_chest_pain": _yes_no_categories,
        "think_have_long_covid_symptom_anxiety": _yes_no_categories,
        "think_have_long_covid_symptom_memory_loss_or_confusion": _yes_no_categories,
        "think_have_long_covid_symptom_muscle_ache": _yes_no_categories,
        "think_have_long_covid_symptom_abdominal_pain": _yes_no_categories,
        "think_have_long_covid_symptom_loss_of_taste": _yes_no_categories,
        "think_have_long_covid_symptom_cough": _yes_no_categories,
        "think_have_long_covid_symptom_palpitations": _yes_no_categories,
        "think_have_long_covid_symptom_low_mood": _yes_no_categories,
        "think_have_long_covid_symptom_difficulty_concentrating": _yes_no_categories,
        "think_have_long_covid_symptom_runny_nose_or_sneezing": _yes_no_categories,
        "think_have_long_covid_symptom_noisy_breathing": _yes_no_categories,
        "confirm_received_vouchers": _yes_no_categories,
        "have_landline_number": _yes_no_categories,
        "have_mobile_number": _yes_no_categories,
        "have_email_address": _yes_no_categories,
        "work_main_job_changed": _yes_no_categories,
        "work_in_additional_paid_employment": _yes_no_categories,
        "cis_covid_vaccine_received": _yes_no_categories,
        "cis_flu_vaccine_received": _yes_no_categories,
        "did_not_attend_inferred": _yes_no_categories,
        "digital_survey_mode_preference": {"Online": 0, "Telephone": 1},
        "digital_communication_preference": {"Email": 0, "Letter": 1},
        "sample_return_preference": {"Post": 0, "Courier": 1},
        "visit_order": {
            "First Visit": 1,
            "Follow-up 1": 2,
            "Follow-up 2": 3,
            "Follow-up 3": 4,
            "Follow-up 4": 5,
            "Month 2": 6,
            "Month 3": 7,
            "Month 4": 8,
            "Month 5": 9,
            "Month 6": 10,
            "Month 7": 11,
            "Month 8": 12,
            "Month 9": 13,
            "Month 10": 14,
            "Month 11": 15,
            "Month 12": 16,
            "Month 13": 17,
            "Month 14": 18,
            "Month 15": 19,
            "Month 16": 20,
            "Month 17": 21,
            "Month 18": 22,
            "Month 19": 23,
            "Month 20": 24,
            "Month 21": 25,
            "Month 22": 26,
            "Month 23": 27,
            "Month 24": 28,
        },
        "participant_visit_status": {
            "Cancelled": 0,
            "Completed": 1,
            "Patient did not attend": 2,
            "Participant did not attend": 2,
            "Re-scheduled": 3,
            "Scheduled": 4,
            "Partially Completed": 5,
            "Withdrawn": 6,
            "New": 7,
            "Dispatched": 8,
            "Household did not attend": 9,
        },
        "survey_response_type": {"First Visit": 0, "Follow-up Visit": 1},
        "sex": {"Male": 1, "Female": 2},
        "ethnicity": {
            "White-British": 1,
            "White-Irish": 2,
            "White-Gypsy or Irish Traveller": 3,
            "Any other white background": 4,
            "Mixed-White & Black Caribbean": 5,
            "Mixed-White & Black African": 6,
            "Mixed-White & Asian": 7,
            "Any other Mixed background": 8,
            "Asian or Asian British-Indian": 9,
            "Asian or Asian British-Pakistani": 10,
            "Asian or Asian British-Bangladeshi": 11,
            "Asian or Asian British-Chinese": 12,
            "Any other Asian background": 13,
            "Black,Caribbean,African-African": 14,
            "Black,Caribbean,Afro-Caribbean": 15,
            "Any other Black background": 16,
            "Other ethnic group-Arab": 17,
            "Any other ethnic group": 18,
        },
        "ethnicity_white": {
            "Non-White": 0,
            "White": 1,
        },
        "illness_reduces_activity_or_ability": {"Not at all": 0, "Yes, a little": 1, "Yes, a lot": 2},
        "work_sector": {
            "Teaching and education": 1,
            "Health care": 2,
            "Social care": 3,
            "Transport (incl. storage, logistic)": 4,
            "Retail sector (incl. wholesale)": 5,
            "Hospitality (e.g. hotel, restaurant)": 6,
            "Food production, agriculture, farming": 7,
            "Personal services (e.g. hairdressers)": 8,
            "Information technology and communication": 9,
            "Financial services incl. insurance": 10,
            "Manufacturing or construction": 11,
            "Civil service or Local Government": 12,
            "Armed forces": 13,
            "Arts,Entertainment or Recreation": 14,
            "Other occupation sector": 15,
            "NA(Not currently working)": 99,
        },
        "work_health_care_area": {
            "No": 0,
            "Yes, in primary care, e.g. GP, dentist": 1,
            "Yes, in secondary care, e.g. hospital": 2,
            "Yes, in other healthcare settings, e.g. mental health": 3,
        },
        "work_health_care_patient_facing": {
            "No": 0,
            "Yes, primary care, patient-facing": 1,
            "Yes, secondary care, patient-facing": 2,
            "Yes, other healthcare, patient-facing": 3,
            "Yes, primary care, non-patient-facing": 4,
            "Yes, secondary care, non-patient-facing": 5,
            "Yes, other healthcare, non-patient-facing": 6,
        },
        "work_social_care": {
            "No": 0,
            "Yes, care/residential home, resident-facing": 1,
            "Yes, other social care, resident-facing": 2,
            "Yes, care/residential home, non-resident-facing": 3,
            "Yes, other social care, non-resident-facing": 4,
        },
        "work_status_v0": {
            "Employed": 1,
            "Self-employed": 2,
            "Furloughed (temporarily not working)": 3,
            "Not working (unemployed, retired, long-term sick etc.)": 4,
            "Student": 5,
        },
        "work_status_v1": {
            "Employed and currently working": 1,
            "Employed and currently not working": 2,
            "Self-employed and currently working": 3,
            "Self-employed and currently not working": 4,
            "Looking for paid work and able to start": 5,
            "Not working and not looking for work": 6,
            "Retired": 7,
            "Child under 5y not attending child care": 8,
            "Child under 5y attending child care": 9,
            "5y and older in full-time education": 10,
        },
        "work_status_v2": {
            "Employed and currently working": 1,
            "Employed and currently not working": 2,
            "Self-employed and currently working": 3,
            "Self-employed and currently not working": 4,
            "Looking for paid work and able to start": 5,
            "Not working and not looking for work": 6,
            "Retired": 7,
            "Child under 4-5y not attending child care": 8,
            "Child under 4-5y attending child care": 9,
            "4-5y and older at school/home-school": 10,
            "Attending college or FE (including if temporarily absent)": 11,
            "Attending university (including if temporarily absent)": 12,
        },
        "work_location": {
            "Working from home": 1,
            "Working somewhere else (not your home)": 2,
            "Both (from home and somewhere else)": 3,
            "Not applicable, not currently working": 4,
        },
        "ability_to_socially_distance_at_work_or_education": {
            "Easy to maintain 2m": 1,
            "Relatively easy to maintain 2m": 2,
            "Difficult to maintain 2m, but can be 1m": 3,
            "Very difficult to be more than 1m away": 4,
            "N/A (not working/in education etc)": 9,
        },
        "transport_to_work_or_education": {
            "Underground, metro, light rail, tram": 1,
            "Train": 2,
            "Bus, minibus, coach": 3,
            "Motorbike, scooter or moped": 4,
            "Car or van": 5,
            "Taxi/minicab": 6,
            "Bicycle": 7,
            "On foot": 8,
            "Other method": 9,
            "N/A (not working/in education etc)": 99,
        },
        "self_isolating_reason": {
            "No": 0,
            "Yes, you have/have had symptoms": 1,
            "Yes, someone you live with had symptoms": 2,
            "Yes, for other reasons (e.g. going into hospital, quarantining)": 3,
        },
        "last_covid_contact_type": {"Living in your own home": 1, "Outside your home": 2},
        "last_suspected_covid_contact_type": {"Living in your own home": 1, "Outside your home": 2},
        "household_been_hospital_last_28_days": {
            "No, no one in my household has": 0,
            "Yes, I have": 1,
            "No I haven’t, but someone else in my household has": 2,
        },
        "household_been_care_home_last_28_days": {
            "No, no one in my household has": 0,
            "Yes, I have": 1,
            "No I haven’t, but someone else in my household has": 2,
        },
        "physical_contact_under_18_years": {"0": 0, "1-5": 1, "6-10": 2, "11-20": 3, "21 or more": 4},
        "physical_contact_18_to_69_years": {"0": 0, "1-5": 1, "6-10": 2, "11-20": 3, "21 or more": 4},
        "physical_contact_over_70_years": {"0": 0, "1-5": 1, "6-10": 2, "11-20": 3, "21 or more": 4},
        "social_distance_contact_under_18_years": {"0": 0, "1-5": 1, "6-10": 2, "11-20": 3, "21 or more": 4},
        "social_distance_contact_18_to_69_years": {"0": 0, "1-5": 1, "6-10": 2, "11-20": 3, "21 or more": 4},
        "social_distance_contact_over_70_years": {"0": 0, "1-5": 1, "6-10": 2, "11-20": 3, "21 or more": 4},
        "face_covering_outside_of_home": {
            "No": 0,
            "Yes, at work/school only": 1,
            "Yes, in other situations only": 2,
            "Yes, usually both Work/school/other": 3,
            "My face is already covered": 4,
        },
        "face_covering_work_or_education": {
            "Never": 0,
            "Yes, sometimes": 1,
            "Yes, always": 2,
            "Not going to place of work or education": 3,
            "My face is already covered": 4,
            "My face is already covered for other reasons such as religious or cultural reasons": 5,
        },
        "face_covering_other_enclosed_places": {
            "Never": 0,
            "Yes, sometimes": 1,
            "Yes, always": 2,
            "Not going to other enclosed public spaces or using public transport": 3,
            "My face is already covered": 4,
            "My face is already covered for other reasons such as religious or cultural reasons": 5,
        },
        "other_covid_infection_test_results": {
            "Any tests negative, but none positive": 0,
            "One or more positive test(s)": 1,
            "Waiting for all results": 2,
            "All Tests failed": 9,
        },
        "other_antibody_test_results": {
            "Any tests negative, but none positive": 0,
            "One or more positive test(s)": 1,
            "Waiting for all results": 2,
            "All Tests failed": 9,
        },
        "other_antibody_test_location": {"In the NHS (e.g. GP, hospital)": 1, "Private lab": 2, "Home test": 3},
        "think_have_long_covid_symptom_reduced_ability": {
            "Not at all": 4,
            "Yes a little": 5,
            "Yes a lot": 6,
        },
        "participant_withdrawal_type": {
            "Withdrawn": 1,
            "Withdrawn_no_future_linkage_or_use of samples": 2,
            "Withdrawn_no_future_linkage": 3,
        },
        "country_barcode": {"England": 0, "Wales": 1, "NI": 2, "Scotland": 3},
        "not_attended_reason": {
            "At School": 1,
            "At Work": 2,
            "Doctor Appointment": 3,
            "Living Away - For Education": 4,
            "On Holiday": 5,
            "Other": 6,
            "Phone not answered": 7,
            "Planning to withdraw": 8,
        },
        "deferred": {"NA": 0, "Deferred": 1},
        "times_hour_or_longer_another_home_last_7_days": _times_in_last_7_day_categories,
        "times_hour_or_longer_another_person_your_home_last_7_days": _times_in_last_7_day_categories,
        "voucher_type_preference": {"email_address": 1, "Paper": 2},
        "participant_testing_group": {"Swab Only": 0, "Blood and Swab": 1, "Fingerprick and Swab": 2},
        "household_fingerprick_status": {
            "Accepted": 0,
            "Declined": 1,
            "Invited": 2,
            "At least one person consented": 3,
            "Not invited": 4,
            "No-one Consented": 5,
        },
        "able_to_take_blood": _yes_no_categories,
        "no_fingerprick_blood_taken_reason": {
            "Bruising or pain after first attempt": 0,
            "Couldn't get enough blood": 1,
            "No stock": 2,
            "Other": 3,
            "Participant felt unwell/fainted": 4,
            "Participant refused to give blood on this visit": 5,
            "Participant time constraints": 6,
            "Two attempts made": 7,
            "High risk assessment outcome": 8,
        },
        "no_venous_blood_taken_reason": {
            "Non-contact visit. Household self-isolating": 0,
            "Participant dehydrated": 1,
            "No stock": 2,
            "Other": 3,
            "Participant felt unwell/fainted": 4,
            "Participant refused": 5,
            "Participant time constraints": 6,
            "Poor venous access": 7,
            "Two attempts made": 8,
            "Bruising or pain after first attempt": 9,
        },
        "accepted_fingerprick_invite": _yes_no_categories,
        "cis_covid_vaccine_offered": _yes_no_categories,
        "regularly_lateral_flow_testing": _yes_no_categories,
        "household_visit_status": {
            "Completed": 1,
            "Dispatched": 2,
            "Household did not attend": 3,
            "Partially Completed": 4,
            "Withdrawn": 5,
        },
        "participant_survey_status": {"Active": 0, "Withdrawn": 1, "Completed": 2},
        "participant_withdrawal_reason": {
            "Bad experience with interviewer/survey": 1,
            "Moving location": 2,
            "No longer convenient": 3,
            "No longer wants to take part": 4,
            "Participant does not want to self swab": 5,
            "Swab/blood process too distressing": 6,
            "Too many visits": 7,
            "Household declined": 8,
            "Deceased": 9,
            "Do not reinstate": 10,
            "SWCAP": 11,
        },
        "cis_covid_vaccine_type": {
            "Don't know type": 1,
            "From a research study/trial": 2,
            "Moderna": 3,
            "Oxford/AstraZeneca": 4,
            "Pfizer/BioNTech": 5,
            "Other / specify": 6,
            "Janssen/Johnson&Johnson": 7,
            "Novavax": 8,
            "Sinovac": 9,
            "Sinovax": 10,
            "Valneva": 11,
            "Sinopharm": 12,
            "Sputnik": 13,
        },
        "cis_covid_vaccine_type_1": {
            "Don't know type": 1,
            "From a research study/trial": 2,
            "Moderna": 3,
            "Oxford/AstraZeneca": 4,
            "Pfizer/BioNTech": 5,
            "Other / specify": 6,
            "Janssen/Johnson&Johnson": 7,
            "Novavax": 8,
            "Sinovac": 9,
            "Sinovax": 10,
            "Valneva": 11,
            "Sinopharm": 12,
            "Sputnik": 13,
        },
        "cis_covid_vaccine_type_2": {
            "Don't know type": 1,
            "From a research study/trial": 2,
            "Moderna": 3,
            "Oxford/AstraZeneca": 4,
            "Pfizer/BioNTech": 5,
            "Other / specify": 6,
            "Janssen/Johnson&Johnson": 7,
            "Novavax": 8,
            "Sinovac": 9,
            "Sinovax": 10,
            "Valneva": 11,
            "Sinopharm": 12,
            "Sputnik": 13,
        },
        "cis_covid_vaccine_type_3": {
            "Don't know type": 1,
            "From a research study/trial": 2,
            "Moderna": 3,
            "Oxford/AstraZeneca": 4,
            "Pfizer/BioNTech": 5,
            "Other / specify": 6,
            "Janssen/Johnson&Johnson": 7,
            "Novavax": 8,
            "Sinovac": 9,
            "Sinovax": 10,
            "Valneva": 11,
            "Sinopharm": 12,
            "Sputnik": 13,
        },
        "cis_covid_vaccine_type_4": {
            "Don't know type": 1,
            "From a research study/trial": 2,
            "Moderna": 3,
            "Oxford/AstraZeneca": 4,
            "Pfizer/BioNTech": 5,
            "Other / specify": 6,
            "Janssen/Johnson&Johnson": 7,
            "Novavax": 8,
            "Sinovac": 9,
            "Sinovax": 10,
            "Valneva": 11,
            "Sinopharm": 12,
            "Sputnik": 13,
        },
        "cis_covid_vaccine_number_of_doses": {"1": 1, "2": 2, "3 or more": 3},
        "visit_date_type": {
            "actual_visit_date": 0,
            "latest_checkin_date": 1,
            "sample_taken_date": 2,
            "scheduled_date": 3,
        },
        "country_name_12": {"England": 0, "Wales": 1, "Northern Ireland": 2, "Scotland": 3},
        "local_authority_unity_authority_code": {
            "E06000001": 1,
            "E06000002": 2,
            "E06000003": 3,
            "E06000004": 4,
            "E06000005": 5,
            "E06000006": 6,
            "E06000007": 7,
            "E06000008": 8,
            "E06000009": 9,
            "E06000010": 10,
            "E06000011": 11,
            "E06000012": 12,
            "E06000013": 13,
            "E06000014": 14,
            "E06000015": 15,
            "E06000016": 16,
            "E06000017": 17,
            "E06000018": 18,
            "E06000019": 19,
            "E06000020": 20,
            "E06000021": 21,
            "E06000022": 22,
            "E06000023": 23,
            "E06000024": 24,
            "E06000025": 25,
            "E06000026": 26,
            "E06000027": 27,
            "E06000030": 28,
            "E06000031": 29,
            "E06000032": 30,
            "E06000033": 31,
            "E06000034": 32,
            "E06000035": 33,
            "E06000036": 34,
            "E06000037": 35,
            "E06000038": 36,
            "E06000039": 37,
            "E06000040": 38,
            "E06000041": 39,
            "E06000042": 40,
            "E06000043": 41,
            "E06000044": 42,
            "E06000045": 43,
            "E06000046": 44,
            "E06000047": 45,
            "E06000049": 46,
            "E06000050": 47,
            "E06000051": 48,
            "E06000052": 49,
            "E06000053": 50,
            "E06000054": 51,
            "E06000055": 52,
            "E06000056": 53,
            "E06000057": 54,
            "E06000058": 55,
            "E06000059": 56,
            "E06000060": 57,
            "E07000004": 58,
            "E07000005": 59,
            "E07000006": 60,
            "E07000007": 61,
            "E07000008": 62,
            "E07000009": 63,
            "E07000010": 64,
            "E07000011": 65,
            "E07000012": 66,
            "E07000026": 67,
            "E07000027": 68,
            "E07000028": 69,
            "E07000029": 70,
            "E07000030": 71,
            "E07000031": 72,
            "E07000032": 73,
            "E07000033": 74,
            "E07000034": 75,
            "E07000035": 76,
            "E07000036": 77,
            "E07000037": 78,
            "E07000038": 79,
            "E07000039": 80,
            "E07000040": 81,
            "E07000041": 82,
            "E07000042": 83,
            "E07000043": 84,
            "E07000044": 85,
            "E07000045": 86,
            "E07000046": 87,
            "E07000047": 88,
            "E07000061": 89,
            "E07000062": 90,
            "E07000063": 91,
            "E07000064": 92,
            "E07000065": 93,
            "E07000066": 94,
            "E07000067": 95,
            "E07000068": 96,
            "E07000069": 97,
            "E07000070": 98,
            "E07000071": 99,
            "E07000072": 100,
            "E07000073": 101,
            "E07000074": 102,
            "E07000075": 103,
            "E07000076": 104,
            "E07000077": 105,
            "E07000078": 106,
            "E07000079": 107,
            "E07000080": 108,
            "E07000081": 109,
            "E07000082": 110,
            "E07000083": 111,
            "E07000084": 112,
            "E07000085": 113,
            "E07000086": 114,
            "E07000087": 115,
            "E07000088": 116,
            "E07000089": 117,
            "E07000090": 118,
            "E07000091": 119,
            "E07000092": 120,
            "E07000093": 121,
            "E07000094": 122,
            "E07000095": 123,
            "E07000096": 124,
            "E07000098": 125,
            "E07000099": 126,
            "E07000102": 127,
            "E07000103": 128,
            "E07000105": 129,
            "E07000106": 130,
            "E07000107": 131,
            "E07000108": 132,
            "E07000109": 133,
            "E07000110": 134,
            "E07000111": 135,
            "E07000112": 136,
            "E07000113": 137,
            "E07000114": 138,
            "E07000115": 139,
            "E07000116": 140,
            "E07000117": 141,
            "E07000118": 142,
            "E07000119": 143,
            "E07000120": 144,
            "E07000121": 145,
            "E07000122": 146,
            "E07000123": 147,
            "E07000124": 148,
            "E07000125": 149,
            "E07000126": 150,
            "E07000127": 151,
            "E07000128": 152,
            "E07000129": 153,
            "E07000130": 154,
            "E07000131": 155,
            "E07000132": 156,
            "E07000133": 157,
            "E07000134": 158,
            "E07000135": 159,
            "E07000136": 160,
            "E07000137": 161,
            "E07000138": 162,
            "E07000139": 163,
            "E07000140": 164,
            "E07000141": 165,
            "E07000142": 166,
            "E07000143": 167,
            "E07000144": 168,
            "E07000145": 169,
            "E07000146": 170,
            "E07000147": 171,
            "E07000148": 172,
            "E07000149": 173,
            "E07000150": 174,
            "E07000151": 175,
            "E07000152": 176,
            "E07000153": 177,
            "E07000154": 178,
            "E07000155": 179,
            "E07000156": 180,
            "E07000163": 181,
            "E07000164": 182,
            "E07000165": 183,
            "E07000166": 184,
            "E07000167": 185,
            "E07000168": 186,
            "E07000169": 187,
            "E07000170": 188,
            "E07000171": 189,
            "E07000172": 190,
            "E07000173": 191,
            "E07000174": 192,
            "E07000175": 193,
            "E07000176": 194,
            "E07000177": 195,
            "E07000178": 196,
            "E07000179": 197,
            "E07000180": 198,
            "E07000181": 199,
            "E07000187": 200,
            "E07000188": 201,
            "E07000189": 202,
            "E07000192": 203,
            "E07000193": 204,
            "E07000194": 205,
            "E07000195": 206,
            "E07000196": 207,
            "E07000197": 208,
            "E07000198": 209,
            "E07000199": 210,
            "E07000200": 211,
            "E07000202": 212,
            "E07000203": 213,
            "E07000207": 214,
            "E07000208": 215,
            "E07000209": 216,
            "E07000210": 217,
            "E07000211": 218,
            "E07000212": 219,
            "E07000213": 220,
            "E07000214": 221,
            "E07000215": 222,
            "E07000216": 223,
            "E07000217": 224,
            "E07000218": 225,
            "E07000219": 226,
            "E07000220": 227,
            "E07000221": 228,
            "E07000222": 229,
            "E07000223": 230,
            "E07000224": 231,
            "E07000225": 232,
            "E07000226": 233,
            "E07000227": 234,
            "E07000228": 235,
            "E07000229": 236,
            "E07000234": 237,
            "E07000235": 238,
            "E07000236": 239,
            "E07000237": 240,
            "E07000238": 241,
            "E07000239": 242,
            "E07000240": 243,
            "E07000241": 244,
            "E07000242": 245,
            "E07000243": 246,
            "E07000244": 247,
            "E07000245": 248,
            "E07000246": 249,
            "E08000001": 250,
            "E08000002": 251,
            "E08000003": 252,
            "E08000004": 253,
            "E08000005": 254,
            "E08000006": 255,
            "E08000007": 256,
            "E08000008": 257,
            "E08000009": 258,
            "E08000010": 259,
            "E08000011": 260,
            "E08000012": 261,
            "E08000013": 262,
            "E08000014": 263,
            "E08000015": 264,
            "E08000016": 265,
            "E08000017": 266,
            "E08000018": 267,
            "E08000019": 268,
            "E08000021": 269,
            "E08000022": 270,
            "E08000023": 271,
            "E08000024": 272,
            "E08000025": 273,
            "E08000026": 274,
            "E08000027": 275,
            "E08000028": 276,
            "E08000029": 277,
            "E08000030": 278,
            "E08000031": 279,
            "E08000032": 280,
            "E08000033": 281,
            "E08000034": 282,
            "E08000035": 283,
            "E08000036": 284,
            "E08000037": 285,
            "E09000001": 286,
            "E09000002": 287,
            "E09000003": 288,
            "E09000004": 289,
            "E09000005": 290,
            "E09000006": 291,
            "E09000007": 292,
            "E09000008": 293,
            "E09000009": 294,
            "E09000010": 295,
            "E09000011": 296,
            "E09000012": 297,
            "E09000013": 298,
            "E09000014": 299,
            "E09000015": 300,
            "E09000016": 301,
            "E09000017": 302,
            "E09000018": 303,
            "E09000019": 304,
            "E09000020": 305,
            "E09000021": 306,
            "E09000022": 307,
            "E09000023": 308,
            "E09000024": 309,
            "E09000025": 310,
            "E09000026": 311,
            "E09000027": 312,
            "E09000028": 313,
            "E09000029": 314,
            "E09000030": 315,
            "E09000031": 316,
            "E09000032": 317,
            "E09000033": 318,
            "N09000001": 319,
            "N09000002": 320,
            "N09000003": 321,
            "N09000004": 322,
            "N09000005": 323,
            "N09000006": 324,
            "N09000007": 325,
            "N09000008": 326,
            "N09000009": 327,
            "N09000010": 328,
            "N09000011": 329,
            "S12000005": 330,
            "S12000006": 331,
            "S12000008": 332,
            "S12000010": 333,
            "S12000011": 334,
            "S12000013": 335,
            "S12000014": 336,
            "S12000017": 337,
            "S12000018": 338,
            "S12000019": 339,
            "S12000020": 340,
            "S12000021": 341,
            "S12000023": 342,
            "S12000026": 343,
            "S12000027": 344,
            "S12000028": 345,
            "S12000029": 346,
            "S12000030": 347,
            "S12000033": 348,
            "S12000034": 349,
            "S12000035": 350,
            "S12000036": 351,
            "S12000038": 352,
            "S12000039": 353,
            "S12000040": 354,
            "S12000041": 355,
            "S12000042": 356,
            "S12000045": 357,
            "S12000047": 358,
            "S12000048": 359,
            "S12000049": 360,
            "S12000050": 361,
            "W06000001": 362,
            "W06000002": 363,
            "W06000003": 364,
            "W06000004": 365,
            "W06000005": 366,
            "W06000006": 367,
            "W06000008": 368,
            "W06000009": 369,
            "W06000010": 370,
            "W06000011": 371,
            "W06000012": 372,
            "W06000013": 373,
            "W06000014": 374,
            "W06000015": 375,
            "W06000016": 376,
            "W06000018": 377,
            "W06000019": 378,
            "W06000020": 379,
            "W06000021": 380,
            "W06000022": 381,
            "W06000023": 382,
            "W06000024": 383,
        },
        "cis_area_code_20": {
            "J06000101": 1,
            "J06000102": 2,
            "J06000103": 3,
            "J06000104": 4,
            "J06000105": 5,
            "J06000106": 6,
            "J06000107": 7,
            "J06000108": 8,
            "J06000109": 9,
            "J06000110": 10,
            "J06000111": 11,
            "J06000112": 12,
            "J06000113": 13,
            "J06000114": 14,
            "J06000115": 15,
            "J06000116": 16,
            "J06000117": 17,
            "J06000118": 18,
            "J06000119": 19,
            "J06000120": 20,
            "J06000121": 21,
            "J06000122": 22,
            "J06000123": 23,
            "J06000124": 24,
            "J06000125": 25,
            "J06000126": 26,
            "J06000127": 27,
            "J06000128": 28,
            "J06000129": 29,
            "J06000130": 30,
            "J06000131": 31,
            "J06000132": 32,
            "J06000133": 33,
            "J06000134": 34,
            "J06000135": 35,
            "J06000136": 36,
            "J06000137": 37,
            "J06000138": 38,
            "J06000139": 39,
            "J06000140": 40,
            "J06000141": 41,
            "J06000142": 42,
            "J06000143": 43,
            "J06000144": 44,
            "J06000145": 45,
            "J06000146": 46,
            "J06000147": 47,
            "J06000148": 48,
            "J06000149": 49,
            "J06000150": 50,
            "J06000151": 51,
            "J06000152": 52,
            "J06000153": 53,
            "J06000154": 54,
            "J06000155": 55,
            "J06000156": 56,
            "J06000157": 57,
            "J06000158": 58,
            "J06000159": 59,
            "J06000160": 60,
            "J06000161": 61,
            "J06000162": 62,
            "J06000163": 63,
            "J06000164": 64,
            "J06000165": 65,
            "J06000166": 66,
            "J06000167": 67,
            "J06000168": 68,
            "J06000169": 69,
            "J06000170": 70,
            "J06000171": 71,
            "J06000172": 72,
            "J06000173": 73,
            "J06000174": 74,
            "J06000175": 75,
            "J06000176": 76,
            "J06000177": 77,
            "J06000178": 78,
            "J06000179": 79,
            "J06000180": 80,
            "J06000181": 81,
            "J06000182": 82,
            "J06000183": 83,
            "J06000184": 84,
            "J06000185": 85,
            "J06000186": 86,
            "J06000187": 87,
            "J06000188": 88,
            "J06000189": 89,
            "J06000190": 90,
            "J06000191": 91,
            "J06000192": 92,
            "J06000193": 93,
            "J06000194": 94,
            "J06000195": 95,
            "J06000196": 96,
            "J06000197": 97,
            "J06000198": 98,
            "J06000199": 99,
            "J06000200": 100,
            "J06000201": 101,
            "J06000202": 102,
            "J06000203": 103,
            "J06000204": 104,
            "J06000205": 105,
            "J06000206": 106,
            "J06000207": 107,
            "J06000208": 108,
            "J06000209": 109,
            "J06000210": 110,
            "J06000211": 111,
            "J06000212": 112,
            "J06000213": 113,
            "J06000214": 114,
            "J06000215": 115,
            "J06000216": 116,
            "J06000217": 117,
            "J06000218": 118,
            "J06000219": 119,
            "J06000220": 120,
            "J06000221": 121,
            "J06000222": 122,
            "J06000223": 123,
            "J06000224": 124,
            "J06000225": 125,
            "J06000226": 126,
            "J06000227": 127,
            "J06000228": 128,
            "J06000229": 129,
            "J06000230": 130,
            "J06000231": 131,
            "J06000232": 132,
            "J06000233": 133,
        },
        "people_in_household_count_group": {"1": 1, "2": 2, "3": 3, "4": 4, "5+": 5},
        "region_code": {
            "E12000001": 1,
            "E12000002": 2,
            "E12000003": 3,
            "E12000004": 4,
            "E12000005": 5,
            "E12000006": 6,
            "E12000007": 7,
            "E12000008": 8,
            "E12000009": 9,
            "N99999999": 10,
            "S99999999": 11,
            "W99999999": 12,
        },
    }
}


column_name_maps: Dict[str, Dict[str, str]]
column_name_maps = {
    "swab_variable_name_map": {
        "Sample": "swab_sample_barcode",
        "Result": "pcr_result_classification",
        "Date Tested": "pcr_result_recorded_datetime",
        "Lab ID": "pcr_lab_id",
        "testKit": "testKit",
        "CH1-Target": "orf1ab_gene_pcr_target",
        "CH1-Result": "orf1ab_gene_pcr_result_classification",
        "CH1-Cq": "orf1ab_gene_pcr_cq_value",
        "CH2-Target": "n_gene_pcr_target",
        "CH2-Result": "n_gene_pcr_result_classification",
        "CH2-Cq": "n_gene_pcr_cq_value",
        "CH3-Target": "s_gene_pcr_target",
        "CH3-Result": "s_gene_pcr_result_classification",
        "CH3-Cq": "s_gene_pcr_cq_value",
        "CH4-Target": "ms2_pcr_target",
        "CH4-Result": "ms2_pcr_result_classification",
        "CH4-Cq": "ms2_pcr_cq_value",
    },
    "blood_variable_name_map": {
        "Serum Source ID": "blood_sample_barcode",
        "Blood Sample Type": "blood_sample_type",
        "Plate Barcode": "antibody_test_plate_id",
        "Well ID": "antibody_test_well_id",
        "Detection": "antibody_test_result_classification",
        "Monoclonal quantitation (Colourimetric)": "antibody_test_result_value",
        "Monoclonal bounded quantitation (Colourimetric)": "antibody_test_bounded_result_value",
        "Monoclonal undiluted quantitation (Colourimetric)": "antibody_test_undiluted_result_value",
        "Date ELISA Result record created": "antibody_test_result_recorded_date",
        "Date Samples Arrayed Oxford": "blood_sample_arrayed_date",
        "Date Samples Received Oxford": "blood_sample_received_date",
        "Voyager Date Created": "blood_sample_collected_datetime",
    },
    "unassayed_bloods_variable_name_map": {
        "Date Received": "blood_sample_received_date",
        "Sample ID": "blood_sample_barcode",
        "Rejection Code": "rejection_code",
        "Reason for rejection": "rejection_reason",
        "Sample Type V/C": "blood_sample_type",
    },
    "historical_blood_variable_name_map": {
        "blood_barcode_OX": "blood_sample_barcode",
        "received_ox_date": "blood_sample_received_date",
        "result_tdi": "antibody_test_result_classification",
        "result_siemens": "siemens_antibody_test_result_classification",
        "result_tdi_date": "antibody_test_result_recorded_date",
        "assay_tdi": "antibody_test_tdi_result_value",
        "assay_category": "antibody_assay_category",
        "assay_siemens": "siemens_antibody_test_result_value",
        "plate_tdi": "antibody_test_plate_id",
        "well_tdi": "antibody_test_well_id",
        "lims_id": "lims_id",
        "blood_sample_type": "blood_sample_type",
        "voyager_blood_dt_time": "blood_sample_collected_datetime",
        "arrayed_ox_date": "blood_sample_arrayed_date",
        "assay_mabs": "antibody_test_result_value",
        "platestorage": "plate_storage_method",
    },
    "sample_eng_wl_sc_variable_name_map": {
        "UAC": "unique_access_code",
        "LA_CODE": "local_authority_code",
        "Bloods": "in_blood_cohort",
        "oa11": "output_area_code",
        "laua": "local_authority_unity_authority_code",
        "ctry": "country_code",
        "CUSTODIAN_REGION_CODE": "custodian_region_code",
        "lsoa11": "lower_super_output_area_code",
        "msoa11": "middle_super_output_area_code",
        "ru11ind": "rural_urban_classification",
        "oac11": "census_output_area_classification",
        "rgn": "region_code",
        "imd": "index_multiple_deprivation",
        "interim_id": "cis_area_indicator",
    },
    "sample_ni_variable_name_map": {
        "UAC": "unique_access_code",
        "sample": "sample_week_indicator",
        "oa11": "output_area_code",
        "laua": "local_authority_unity_authority_code",
        "ctry": "country_code",
        "GOR9D": "region_code",
        "lsoa11": "lower_super_output_area_code",
        "msoa11": "middle_super_output_area_code",
        "oac11": "census_output_area_classification",
        "LSOA11NM": "lower_super_output_area_name",
        "CIS20CD": "cis_area_code",
        "rgn": "region_code",
        "imd": "index_multiple_deprivation",
        "interim_id": "cis_area_indicator",
    },
    "nims_column_name_map": {
        "cis_participant_id": "participant_id",
        "product_dose_1": "nims_vaccine_dose_1_type",
        "vaccination_date_dose_1": "nims_vaccine_dose_1_datetime",
        "product_dose_2": "nims_vaccine_dose_2_type",
        "vaccination_date_dose_2": "nims_vaccine_dose_2_datetime",
        "found_pds": "nims_linkage_via_pds",
        "pds_conflict": "nims_conflicting_linkage_via_pds",
    },
    "survey_responses_v0_variable_name_map": {
        "ONS Household ID": "ons_household_id",
        "Visit ID": "visit_id",
        "Type of Visit": "survey_response_type",
        "Participant_Visit_status": "participant_visit_status",
        "Withdrawal_reason": "participant_withdrawal_reason",
        "Visit Date/Time": "visit_datetime",
        "Street": "street",
        "City": "city",
        "County": "county",
        "Postcode": "postcode",
        "Phase": "phase",
        "No. Paticicpants not Consented": "household_participants_not_consenting_count",
        "Reason Participants not Consented": "household_participants_not_consented_reason",
        "No. Participants not present for Visit": "household_members_over_2_years_and_not_present_count",
        "Reason Participants not present on Visit": "household_participants_not_present_reason",
        "Any Household Members Under 2 Years": "household_members_under_2_years",
        "Infant 1 age in Months": "infant_age_months_1",
        "Infant 2 age in Months": "infant_age_months_2",
        "Infant 3 age in Months": "infant_age_months_3",
        "Infant 4 age in Months": "infant_age_months_4",
        "Infant 5 age in Months": "infant_age_months_5",
        "Infant 6 age in Months": "infant_age_months_6",
        "Infant 7 age in Months": "infant_age_months_7",
        "Infant 8 age in Months": "infant_age_months_8",
        "Any Household Members Over 2 Not Present": "any_household_members_over_2_years_and_not_present",
        "Person 1 age in Years": "person_not_present_age_1",
        "Person 2 age in Years": "person_not_present_age_2",
        "Person 3 age in Years": "person_not_present_age_3",
        "Person 4 age in Years": "person_not_present_age_4",
        "Person 5 age in Years": "person_not_present_age_5",
        "Person 6 age in Years": "person_not_present_age_6",
        "Person 7 age in Years": "person_not_present_age_7",
        "Person 8 age in Years": "person_not_present_age_8",
        "Person 1 Not Consenting (Age in Years)": "person_not_consenting_age_1",
        "Reason for Not Consenting (Person 1)": "person_1_reason_for_not_consenting",
        "Person 2 Not Consenting (Age in Years)": "person_not_consenting_age_2",
        "Reason for Not Consenting (Person 2)": "person_2_reason_for_not_consenting",
        "Person 3 Not Consenting (Age in Years)": "person_not_consenting_age_3",
        "Reason for Not Consenting (Person 3)": "person_3_reason_for_not_consenting",
        "Person 4 Not Consenting (Age in Years)": "person_not_consenting_age_4",
        "Reason for Not Consenting (Person 4)": "person_4_reason_for_not_consenting",
        "Person 5 Not Consenting (Age in Years)": "person_not_consenting_age_5",
        "Reason for Not Consenting (Person 5)": "person_5_reason_for_not_consenting",
        "Person 6 Not Consenting (Age in Years)": "person_not_consenting_age_6",
        "Reason for Not Consenting (Person 6)": "person_6_reason_for_not_consenting",
        "Person 7 Not Consenting (Age in Years)": "person_not_consenting_age_7",
        "Reason for Not Consenting (Person 7)": "person_7_reason_for_not_consenting",
        "Person 8 Not Consenting (Age in Years)": "person_not_consenting_age_8",
        "Reason for Not Consenting (Person 8)": "person_8_reason_for_not_consenting",
        "Person 9 Not Consenting (Age in Years)": "person_not_consenting_age_9",
        "Reason for Not Consenting (Person 9)": "person_9_reason_for_not_consenting",
        "Participant ID": "participant_id",
        "Suffix": "suffix",
        "Full Name": "full_name",
        "DoB": "date_of_birth",
        "Email": "email_address",
        "No Email Address": "no_email_address",
        "Bloods Taken": "bloods_taken",
        "Bloods Barcode 1": "blood_sample_barcode",
        "Swab Taken": "swabs_taken",
        "Swab Barcode 1": "swab_sample_barcode",
        "Date/Time Samples Taken": "samples_taken_datetime",
        "Sex": "sex",
        "Gender": "gender",
        "Ethnicity": "ethnicity",
        "Consent to First Visit": "consent_1_visit",
        "Consent to Five Visits": "consent_5_visits",
        "Consent to Sixteen Visits": "consent_16_visits",
        "Consent to be Contacted Extra Research": "consent_contact_extra_research",
        "Consent to Blood Samples": "consent_blood_test",
        "Consent to Surplus Blood Sample": "consent_use_of_surplus_blood_samples",
        "Working Status (Main Job)": "work_status_v0",
        "Job Title": "work_main_job_title",
        "Main Job Responsibilities": "work_main_job_role",
        "Working Location": "work_location",
        "No. days a week working outside of home?": "work_not_from_home_days_per_week",
        "Do you work in healthcare?": "work_health_care_patient_facing",
        "Do you work in social care?": "work_social_care",
        "Do you have any of these symptoms Today?": "think_have_covid_symptom_any",
        "Symptoms today": "which_symptoms_last_7_days",
        "Symptoms today- Fever": "think_have_covid_symptom_fever",
        "Symptoms today- Muscle ache (myalgia)": "think_have_covid_symptom_muscle_ache",
        "Symptoms today- Fatigue (weakness)": "think_have_covid_symptom_fatigue",
        "Symptoms today- Sore throat": "think_have_covid_symptom_sore_throat",
        "Symptoms today- Cough": "think_have_covid_symptom_cough",
        "Symptoms today- Shortness of breath": "think_have_covid_symptom_shortness_of_breath",
        "Symptoms today- Headache": "think_have_covid_symptom_headache",
        "Symptoms today- Nausea/vomiting": "think_have_covid_symptom_nausea_or_vomiting",
        "Symptoms today- Abdominal pain": "think_have_covid_symptom_abdominal_pain",
        "Symptoms today- Diarrhoea": "think_have_covid_symptom_diarrhoea",
        "Symptoms today- Loss of taste": "think_have_covid_symptom_loss_of_taste",
        "Symptoms today- Loss of smell": "think_have_covid_symptom_loss_of_smell",
        "Are you self Isolating?": "self_isolating",
        "Received shielding letter from NHS?": "received_shielding_letter",
        "Do you think you have Covid Symptoms?": "think_have_covid",
        "Contact with Known Positive COVID19 Case": "contact_known_positive_covid_last_28_days",
        "If Known; Last contact date": "last_covid_contact_date",
        "If Known; Type of contact": "last_covid_contact_type",
        "Contact with Suspected Covid19 Case": "contact_suspected_positive_covid_last_28_days",
        "If Suspect; Last contact date": "last_suspected_covid_contact_date",
        "If Suspect; Type of contact": "last_suspected_covid_contact_type",
        "Household been Hospital last 2 wks": "household_been_hospital_last_28_days",
        "Household been in Care home last 2 wks": "household_been_care_home_last_28_days",
        "Do you think you have had Covid 19?": "think_had_covid",
        "Which symptoms did you have?": "think_had_covid_which_symptoms",
        "Previous Symptoms-Fever": "think_had_covid_symptom_fever",
        "Previous Symptoms-Muscle ache (myalgia)": "think_had_covid_symptom_muscle_ache",
        "Previous Symptoms-Fatigue (weakness)": "think_had_covid_symptom_fatigue",
        "Previous Symptoms-Sore throat": "think_had_covid_symptom_sore_throat",
        "Previous Symptoms-Cough": "think_had_covid_symptom_cough",
        "Previous Symptoms-Shortness of breath": "think_had_covid_symptom_shortness_of_breath",
        "Previous Symptoms-Headache": "think_had_covid_symptom_headache",
        "Previous Symptoms-Nausea/vomiting": "think_had_covid_symptom_nausea_or_vomiting",
        "Previous Symptoms-Abdominal pain": "think_had_covid_symptom_abdominal_pain",
        "Previous Symptoms-Diarrhoea": "think_had_covid_symptom_diarrhoea",
        "Previous Symptoms-Loss of taste": "think_had_covid_symptom_loss_of_taste",
        "Previous Symptoms-Loss of smell": "think_had_covid_symptom_loss_of_smell",
        "If Yes; Date of first symptoms": "think_had_covid_onset_date",
        "Did you contact NHS?": "think_had_covid_contacted_nhs",
        "If Yes; Were you tested": "other_covid_infection_test",
        "If Yes;Test Result": "other_covid_infection_test_results",
        "Were you admitted to hospital?": "think_had_covid_admitted_to_hospital",
    },
    "survey_responses_v1_variable_name_map": {
        "ons_household_id": "ons_household_id",
        "Visit_ID": "visit_id",
        "Type_of_Visit": "survey_response_type",
        "Participant_Visit_status": "participant_visit_status",
        "Withdrawal_reason": "participant_withdrawal_reason",
        "Visit_Date_Time": "visit_datetime",
        "Street": "street",
        "City": "city",
        "County": "county",
        "Postcode": "postcode",
        "Cohort": "study_cohort",
        "No_Paticicpants_not_Consented": "household_participants_not_consenting_count",
        "Reason_Participants_not_Consented": "household_participants_not_consented_reason",
        "No_Participants_not_present_for_Visit": "household_members_over_2_years_and_not_present_count",
        "Reason_Participants_not_present_on_Visit": "household_participants_not_present_reason",
        "Household_Members_Under_2_Years": "household_members_under_2_years",
        "Infant_1": "infant_age_months_1",
        "Infant_2": "infant_age_months_2",
        "Infant_3": "infant_age_months_3",
        "Infant_4": "infant_age_months_4",
        "Infant_5": "infant_age_months_5",
        "Infant_6": "infant_age_months_6",
        "Infant_7": "infant_age_months_7",
        "Infant_8": "infant_age_months_8",
        "Household_Members_Over_2_and_Not_Present": "any_household_members_over_2_years_and_not_present",
        "Person_1": "person_not_present_age_1",
        "Person_2": "person_not_present_age_2",
        "Person_3": "person_not_present_age_3",
        "Person_4": "person_not_present_age_4",
        "Person_5": "person_not_present_age_5",
        "Person_6": "person_not_present_age_6",
        "Person_7": "person_not_present_age_7",
        "Person_8": "person_not_present_age_8",
        "Person_1_Not_Consenting_Age": "person_not_consenting_age_1",
        "Person1_Reason_for_Not_Consenting": "person_1_reason_for_not_consenting",
        "Person_2_Not_Consenting_Age": "person_not_consenting_age_2",
        "Person2_Reason_for_Not_Consenting": "person_2_reason_for_not_consenting",
        "Person_3_Not_Consenting_Age": "person_not_consenting_age_3",
        "Person3_Reason_for_Not_Consenting": "person_3_reason_for_not_consenting",
        "Person_4_Not_Consenting_Age": "person_not_consenting_age_4",
        "Person4_Reason_for_Not_Consenting": "person_4_reason_for_not_consenting",
        "Person_5_Not_Consenting_Age": "person_not_consenting_age_5",
        "Person5_Reason_for_Not_Consenting": "person_5_reason_for_not_consenting",
        "Person_6_Not_Consenting_Age": "person_not_consenting_age_6",
        "Person6_Reason_for_Not_Consenting": "person_6_reason_for_not_consenting",
        "Person_7_Not_Consenting_Age": "person_not_consenting_age_7",
        "Person7_Reason_for_Not_Consenting": "person_7_reason_for_not_consenting",
        "Person_8_Not_Consenting_Age": "person_not_consenting_age_8",
        "Person8_Reason_for_Not_Consenting": "person_8_reason_for_not_consenting",
        "Person_9_Not_Consenting_Age": "person_not_consenting_age_9",
        "Person9_Reason_for_Not_Consenting": "person_9_reason_for_not_consenting",
        "Participant_id": "participant_id",
        "Title": "title",
        "First_Name": "first_name",
        "Middle_Name": "middle_name",
        "Last_Name": "last_name",
        "DoB": "date_of_birth",
        "Email": "email_address",
        "No_Email_address": "no_email_address",
        "Bloods_Taken": "bloods_taken",
        "bloods_barcode_1": "blood_sample_barcode",
        "Swab_Taken": "swabs_taken",
        "Swab_Barcode_1": "swab_sample_barcode",
        "Date_Time_Samples_Taken": "samples_taken_datetime",
        "Sex": "sex",
        "Gender": "gender",
        "Ethnicity": "ethnicity",
        "Ethnicity_Other": "ethnicity_other",
        "Consent_to_First_Visit": "consent_1_visit",
        "Consent_to_Five_Visits": "consent_5_visits",
        "Consent_to_Sixteen_Visits": "consent_16_visits",
        "Consent_to_Blood_Test": "consent_blood_test",
        "Consent_to_be_Contacted_Extra_Research": "consent_contact_extra_research",
        "Consent_to_use_of_Surplus_Blood_Samples": "consent_use_of_surplus_blood_samples",
        "What_is_the_title_of_your_main_job": "work_main_job_title",
        "What_do_you_do_in_your_main_job_business": "work_main_job_role",
        "Occupations_sectors_do_you_work_in": "work_sector",
        "occupation_sector_other": "work_sector_other",
        "Work_in_a_nursing_residential_care_home": "work_nursing_or_residential_care_home",
        "Do_you_currently_work_in_healthcare": "work_health_care_area",
        "Direct_contact_patients_clients_resid": "work_direct_contact_patients_or_clients",
        "Have_physical_mental_health_or_illnesses": "illness_lasting_over_12_months",
        "physical_mental_health_or_illness_reduces_activity_ability": "illness_reduces_activity_or_ability",
        "Have_you_ever_smoked_regularly": "ever_smoked_regularly",
        "Do_you_currently_smoke_or_vape": "currently_smokes_or_vapes_description",
        "Smoke_Yes_cigarettes": "smoke_cigarettes",
        "Smoke_Yes_cigar": "smokes_cigar",
        "Smoke_Yes_pipe": "smokes_pipe",
        "Smoke_Yes_vape_e_cigarettes": "smokes_vape_e_cigarettes",
        "Smoke_No": "smokes_nothing_now",
        "Smoke_Hookah_shisha pipes": "smokes_hookah_shisha_pipes",
        "What_is_your_current_working_status": "work_status_v1",
        "Where_are_you_mainly_working_now": "work_location",
        "How_often_do_you_work_elsewhere": "work_not_from_home_days_per_week",
        "Can_you_socially_distance_at_work": "ability_to_socially_distance_at_work_or_education",
        "How_do_you_get_to_and_from_work_school": "transport_to_work_or_education",
        "Had_symptoms_in_the_last_7_days": "think_have_covid_symptom_any",
        "Which_symptoms_in_the_last_7_days": "which_symptoms_last_7_days",
        "Date_of_first_symptom_onset": "think_have_covid_onset_date",
        "Symptoms_7_Fever": "think_have_covid_symptom_fever",
        "Symptoms_7_Muscle_ache_myalgia": "think_have_covid_symptom_muscle_ache",
        "Symptoms_7_Fatigue_weakness": "think_have_covid_symptom_fatigue",
        "Symptoms_7_Sore_throat": "think_have_covid_symptom_sore_throat",
        "Symptoms_7_Cough": "think_have_covid_symptom_cough",
        "Symptoms_7_Shortness_of_breath": "think_have_covid_symptom_shortness_of_breath",
        "Symptoms_7_Headache": "think_have_covid_symptom_headache",
        "Symptoms_7_Nausea_vomiting": "think_have_covid_symptom_nausea_or_vomiting",
        "Symptoms_7_Abdominal_pain": "think_have_covid_symptom_abdominal_pain",
        "Symptoms_7_Diarrhoea": "think_have_covid_symptom_diarrhoea",
        "Symptoms_7_Loss_of_taste": "think_have_covid_symptom_loss_of_taste",
        "Symptoms_7_Loss_of_smell": "think_have_covid_symptom_loss_of_smell",
        "Are_you_self_Isolating_S2": "self_isolating_reason",
        "Do_you_think_you_have_Covid_Symptoms": "think_have_covid",
        "Contact_Known_Positive_COVID19_28_days": "contact_known_positive_covid_last_28_days",
        "If_Known_last_contact_date": "last_covid_contact_date",
        "If_Known_type_of_contact_S2": "last_covid_contact_type",
        "Contact_Suspect_Positive_COVID19_28_d": "contact_suspected_positive_covid_last_28_days",
        "If_suspect_last_contact_date": "last_suspected_covid_contact_date",
        "If_suspect_type_of_contact_S2": "last_suspected_covid_contact_type",
        "Household_been_Hospital_last_28_days": "household_been_hospital_last_28_days",
        "Household_been_in_Care_Home_last_28_days": "household_been_care_home_last_28_days",
        "Hours_a_day_with_someone_else": "hours_a_day_with_someone_else_at_home",
        "Physical_Contact_18yrs": "physical_contact_under_18_years",
        "Physical_Contact_18_to_69_yrs": "physical_contact_18_to_69_years",
        "Physical_Contact_70_yrs": "physical_contact_over_70_years",
        "Social_Distance_Contact_18yrs": "social_distance_contact_under_18_years",
        "Social_Distance_Contact_18_to_69_yrs": "social_distance_contact_18_to_69_years",
        "Social_Distance_Contact_70_yrs": "social_distance_contact_over_70_years",
        "1Hour_or_Longer_another_person_home": "times_hour_or_longer_another_home_last_7_days",
        "1Hour_or_Longer_another_person_yourhome": "times_hour_or_longer_another_person_your_home_last_7_days",
        "Times_Outside_Home_For_Shopping": "times_outside_shopping_or_socialising_last_7_days",
        "Face_Covering_or_Mask_outside_of_home": "face_covering_outside_of_home",
        "Do_you_think_you_have_had_Covid_19": "think_had_covid",
        "think_had_covid_19_any_symptoms": "think_had_covid_any_symptoms",
        "think_had_covid_19_which_symptoms": "think_had_covid_which_symptoms",
        "Previous_Symptoms_Fever": "think_had_covid_symptom_fever",
        "Previous_Symptoms_Muscle_ache_myalgia": "think_had_covid_symptom_muscle_ache",
        "Previous_Symptoms_Fatigue_weakness": "think_had_covid_symptom_fatigue",
        "Previous_Symptoms_Sore_throat": "think_had_covid_symptom_sore_throat",
        "Previous_Symptoms_Cough": "think_had_covid_symptom_cough",
        "Previous_Symptoms_Shortness_of_breath": "think_had_covid_symptom_shortness_of_breath",
        "Previous_Symptoms_Headache": "think_had_covid_symptom_headache",
        "Previous_Symptoms_Nausea_vomiting": "think_had_covid_symptom_nausea_or_vomiting",
        "Previous_Symptoms_Abdominal_pain": "think_had_covid_symptom_abdominal_pain",
        "Previous_Symptoms_Diarrhoea": "think_had_covid_symptom_diarrhoea",
        "Previous_Symptoms_Loss_of_taste": "think_had_covid_symptom_loss_of_taste",
        "Previous_Symptoms_Loss_of_smell": "think_had_covid_symptom_loss_of_smell",
        "If_yes_Date_of_first_symptoms": "think_had_covid_onset_date",
        "Did_you_contact_NHS": "think_had_covid_contacted_nhs",
        "Were_you_admitted_to_hospital": "think_had_covid_admitted_to_hospital",
        "Have_you_had_a_swab_test": "other_covid_infection_test",
        "If_Yes_What_was_result": "other_covid_infection_test_results",
        "If_positive_Date_of_1st_ve_test": "other_covid_infection_test_first_positive_date",
        "If_all_negative_Date_last_test": "other_covid_infection_test_last_negative_date",
        "Have_you_had_a_blood_test_for_Covid": "other_antibody_test",
        "What_was_the_result_of_the_blood_test": "other_antibody_test_results",
        "Where_was_the_test_done": "other_antibody_test_location",
        "If_ve_Blood_Date_of_1st_ve_test": "other_antibody_test_first_positive_date",
        "If_all_ve_blood_Date_last_ve_test": "other_antibody_test_last_negative_date",
        "Have_you_been_outside_UK_since_April": "been_outside_uk_since_april_2020",
        "been_outside_uk_last_country": "been_outside_uk_last_country",
        "been_outside_uk_last_date": "been_outside_uk_last_return_date",
        "Vaccinated_Against_Covid": "cis_covid_vaccine_received",
        "Date_Of_Vaccination": "cis_covid_vaccine_date",
    },
    "survey_responses_v2_variable_name_map": {
        "ons_household_id": "ons_household_id",
        "Visit_ID": "visit_id",
        "Visit Status": "household_visit_status",
        "Participant_Visit_status": "participant_visit_status",
        "Participant_status": "participant_survey_status",
        "Withdrawal_reason": "participant_withdrawal_reason",
        "Withdrawn_Type": "participant_withdrawal_type",
        "NotAttendReason": "not_attended_reason",
        "Type_of_Visit": "survey_response_type",
        "Visit_Order": "visit_order",
        "Work_Type_Picklist": "participant_testing_group",
        "Visit_Date_Time": "visit_datetime",
        "Visit_Date_type": "visit_date_type",
        "actual_visit_date": "improved_visit_date",
        "Deferred": "deferred",
        "Street": "street",
        "City": "city",
        "County": "county",
        "Postcode": "postcode",
        "Cohort": "study_cohort",
        "Fingerprick_Status": "household_fingerprick_status",
        "Household_Members_Under_2_Years": "household_members_under_2_years",
        "Infant_1": "infant_age_months_1",
        "Infant_2": "infant_age_months_2",
        "Infant_3": "infant_age_months_3",
        "Infant_4": "infant_age_months_4",
        "Infant_5": "infant_age_months_5",
        "Infant_6": "infant_age_months_6",
        "Infant_7": "infant_age_months_7",
        "Infant_8": "infant_age_months_8",
        "Household_Members_Over_2_and_Not_Present": "any_household_members_over_2_years_and_not_present",
        "Person_1": "person_not_present_age_1",
        "Person_2": "person_not_present_age_2",
        "Person_3": "person_not_present_age_3",
        "Person_4": "person_not_present_age_4",
        "Person_5": "person_not_present_age_5",
        "Person_6": "person_not_present_age_6",
        "Person_7": "person_not_present_age_7",
        "Person_8": "person_not_present_age_8",
        "Person_1_Not_Consenting_Age": "person_not_consenting_age_1",
        "Person1_Reason_for_Not_Consenting": "person_1_reason_for_not_consenting",
        "Person_2_Not_Consenting_Age": "person_not_consenting_age_2",
        "Person2_Reason_for_Not_Consenting": "person_2_reason_for_not_consenting",
        "Person_3_Not_Consenting_Age": "person_not_consenting_age_3",
        "Person3_Reason_for_Not_Consenting": "person_3_reason_for_not_consenting",
        "Person_4_Not_Consenting_Age": "person_not_consenting_age_4",
        "Person4_Reason_for_Not_Consenting": "person_4_reason_for_not_consenting",
        "Person_5_Not_Consenting_Age": "person_not_consenting_age_5",
        "Person5_Reason_for_Not_Consenting": "person_5_reason_for_not_consenting",
        "Person_6_Not_Consenting_Age": "person_not_consenting_age_6",
        "Person6_Reason_for_Not_Consenting": "person_6_reason_for_not_consenting",
        "Person_7_Not_Consenting_Age": "person_not_consenting_age_7",
        "Person7_Reason_for_Not_Consenting": "person_7_reason_for_not_consenting",
        "Person_8_Not_Consenting_Age": "person_not_consenting_age_8",
        "Person8_Reason_for_Not_Consenting": "person_8_reason_for_not_consenting",
        "Person_9_Not_Consenting_Age": "person_not_consenting_age_9",
        "Person9_Reason_for_Not_Consenting": "person_9_reason_for_not_consenting",
        "Participant_id": "participant_id",
        "Title": "title",
        "First_Name": "first_name",
        "Middle_Name": "middle_name",
        "Last_Name": "last_name",
        "DoB": "date_of_birth",
        "Email": "email_address",
        "Have_landline_number": "have_landline_number",
        "Have_mobile_number": "have_mobile_number",
        "Have_email_address": "have_email_address",
        "Prefer_receive_vouchers": "voucher_type_preference",
        "Confirm_receive_vouchers": "confirm_received_vouchers",
        "No_Email_address": "no_email_address",
        "Able_to_take_blood": "able_to_take_blood",
        "No_Blood_reason_fingerprick": "no_fingerprick_blood_taken_reason",
        "No_Blood_reason_venous": "no_venous_blood_taken_reason",
        "bloods_barcode_1": "blood_sample_barcode",
        "Swab_Barcode_1": "swab_sample_barcode",
        "Date_Time_Samples_Taken": "samples_taken_datetime",
        "Sex": "sex",
        "Gender": "gender",
        "Ethnic_group": "ethnic_group",
        "Ethnicity": "ethnicity",
        "Ethnicity_Other": "ethnicity_other",
        "Consent_to_First_Visit": "consent_1_visit",
        "Consent_to_Five_Visits": "consent_5_visits",
        "Consent_to_April_22": "consent_april_22",
        "Consent_to_Sixteen_Visits": "consent_16_visits",
        "Consent_to_Blood_Test": "consent_blood_test",
        "Consent_to_Finger_prick_A1_A3": "consent_finger_prick_a1_a3",
        "Consent_to_extend_study_under_16_B1_B3": "consent_extend_study_under_16_b1_b3",
        "Consent_to_be_Contacted_Extra_Research": "consent_contact_extra_research",
        "Consent_to_be_Contacted_Extra_ResearchYN": "consent_contact_extra_research_yn",
        "Consent_to_use_of_Surplus_Blood_Samples": "consent_use_of_surplus_blood_samples",
        "Consent_to_use_of_Surplus_Blood_SamplesYN": "consent_use_of_surplus_blood_samples_yn",
        "Approached_for_blood_samples?": "approached_for_blood_samples",
        "Consent_to_blood_samples_if_positive": "consent_blood_samples_if_positive",
        "Consent_to_blood_samples_if_positiveYN": "consent_blood_samples_if_positive_yn",
        "Consent_to_fingerprick_blood_samples": "consent_fingerprick_blood_samples",
        "Accepted_invite_to_fingerprick": "accepted_fingerprick_invite",
        "Re_consented_for_blood": "reconsented_blood",
        "Agreed_to_additional_consent_visit": "agreed_to_additional_consent_visit",
        "Additional_Consent_Requirement": "additional_consent_requirement",
        "What_is_the_title_of_your_main_job": "work_main_job_title",
        "What_do_you_do_in_your_main_job_business": "work_main_job_role",
        "Occupations_sectors_do_you_work_in": "work_sector",
        "occupation_sector_other": "work_sector_other",
        "Work_in_a_nursing_residential_care_home": "work_nursing_or_residential_care_home",
        "Do_you_currently_work_in_healthcare": "work_health_care_area",
        "Direct_contact_patients_clients_resid": "work_direct_contact_patients_or_clients",
        "Have_physical_mental_health_or_illnesses": "illness_lasting_over_12_months",
        "physical_mental_health_or_illness_reduces_activity_ability": "illness_reduces_activity_or_ability",
        "Have_you_ever_smoked_regularly": "ever_smoked_regularly",
        "Do_you_currently_smoke_or_vape": "currently_smokes_or_vapes_description",
        "Do_you_currently_smoke_or_vape_at_all": "currently_smokes_or_vapes",
        "Smoke_Yes_cigarettes": "smoke_cigarettes",
        "Smoke_Yes_cigar": "smokes_cigar",
        "Smoke_Yes_pipe": "smokes_pipe",
        "Smoke_Yes_vape_e_cigarettes": "smokes_vape_e_cigarettes",
        "Smoke_Hookah/shisha pipes": "smokes_hookah_shisha_pipes",
        "What_is_your_current_working_status": "work_status_v2",
        "Paid_employment": "work_in_additional_paid_employment",
        "Main_Job_Changed": "work_main_job_changed",
        "Where_are_you_mainly_working_now": "work_location",
        "How_often_do_you_work_elsewhere": "work_not_from_home_days_per_week",
        "How_do_you_get_to_and_from_work_school": "transport_to_work_or_education",
        "Can_you_socially_distance_at_work": "ability_to_socially_distance_at_work_or_education",
        "Had_symptoms_in_the_last_7_days": "think_have_covid_symptom_any",
        "Which_symptoms_in_the_last_7_days": "which_symptoms_last_7_days",
        "Date_of_first_symptom_onset": "think_have_covid_onset_date",
        "Symptoms_7_Fever": "think_have_covid_symptom_fever",
        "Symptoms_7_Muscle_ache_myalgia": "think_have_covid_symptom_muscle_ache",
        "Symptoms_7_Fatigue_weakness": "think_have_covid_symptom_fatigue",
        "Symptoms_7_Sore_throat": "think_have_covid_symptom_sore_throat",
        "Symptoms_7_Cough": "think_have_covid_symptom_cough",
        "Symptoms_7_Shortness_of_breath": "think_have_covid_symptom_shortness_of_breath",
        "Symptoms_7_Headache": "think_have_covid_symptom_headache",
        "Symptoms_7_Nausea_vomiting": "think_have_covid_symptom_nausea_or_vomiting",
        "Symptoms_7_Abdominal_pain": "think_have_covid_symptom_abdominal_pain",
        "Symptoms_7_Diarrhoea": "think_have_covid_symptom_diarrhoea",
        "Symptoms_7_Loss_of_taste": "think_have_covid_symptom_loss_of_taste",
        "Symptoms_7_Loss_of_smell": "think_have_covid_symptom_loss_of_smell",
        "Symptoms_7_More_trouble_sleeping_than_usual": "think_have_covid_symptom_more_trouble_sleeping",
        "Symptoms_7_Runny_nose_sneezing": "think_have_covid_symptom_runny_nose_or_sneezing",
        "Symptoms_7_Noisy_breathing_wheezing": "think_have_covid_symptom_noisy_breathing",
        "Symptoms_7_Loss_of_appetite_or_eating_less_than_usual": "think_have_covid_symptom_loss_of_appetite",
        "Symptoms_7_Chest_pain": "think_have_covid_symptom_chest_pain",
        "Symptoms_7_Palpitations": "think_have_covid_symptom_palpitations",
        "Symptoms_7_Vertigo_dizziness": "think_have_covid_symptom_vertigo_or_dizziness",
        "Symptoms_7_Worry_anxiety": "think_have_covid_symptom_anxiety",
        "Symptoms_7_Low_mood_not_enjoying_anything": "think_have_covid_symptom_low_mood",
        "Symptoms_7_Memory_loss_or_confusion": "think_have_covid_symptom_memory_loss_or_confusion",
        "Symptoms_7_Difficulty_concentrating": "think_have_covid_symptom_difficulty_concentrating",
        "Are_you_self_Isolating_S2": "self_isolating_reason",
        "Do_you_think_you_have_Covid_Symptoms": "think_have_covid",
        "Contact_Known_Positive_COVID19_28_days": "contact_known_positive_covid_last_28_days",
        "If_Known_last_contact_date": "last_covid_contact_date",
        "If_Known_type_of_contact_S2": "last_covid_contact_type",
        "Contact_Suspect_Positive_COVID19_28_d": "contact_suspected_positive_covid_last_28_days",
        "If_suspect_last_contact_date": "last_suspected_covid_contact_date",
        "If_suspect_type_of_contact_S2": "last_suspected_covid_contact_type",
        "You_been_Hospital_last_28_days": "hospital_last_28_days",
        "OtherHouse_been_Hospital_last_28_days": "other_household_member_hospital_last_28_days",
        "Your_been_in_Care_Home_last_28_days": "care_home_last_28_days",
        "OtherHouse_been_in_Care_Home_last_28_days": "other_household_member_care_home_last_28_days",
        "Hours_a_day_with_someone_else": "hours_a_day_with_someone_else_at_home",
        "Physical_Contact_18yrs": "physical_contact_under_18_years",
        "Physical_Contact_18_to_69_yrs": "physical_contact_18_to_69_years",
        "Physical_Contact_70_yrs": "physical_contact_over_70_years",
        "Social_Distance_Contact_18yrs": "social_distance_contact_under_18_years",
        "Social_Distance_Contact_18_to_69_yrs": "social_distance_contact_18_to_69_years",
        "Social_Distance_Contact_70_yrs": "social_distance_contact_over_70_years",
        "1Hour_or_Longer_another_person_home": "times_hour_or_longer_another_home_last_7_days",
        "1Hour_or_Longer_another_person_yourhome": "times_hour_or_longer_another_person_your_home_last_7_days",
        "Times_Outside_Home_For_Shopping": "times_outside_shopping_or_socialising_last_7_days",
        "Shopping_last_7_days": "times_shopping_last_7_days",
        "Socialise_last_7_days": "times_socialising_last_7_days",
        "Regular_testing_COVID": "regularly_lateral_flow_testing",
        "Face_Covering_or_Mask_outside_of_home": "face_covering_outside_of_home",
        "Face_Mask_Work_Place": "face_covering_work_or_education",
        "Face_Mask_Other_Enclosed_Places": "face_covering_other_enclosed_places",
        "Do_you_think_you_have_had_Covid_19": "think_had_covid",
        "think_had_covid_19_any_symptoms": "think_had_covid_any_symptoms",
        "think_had_covid_19_which_symptoms": "think_had_covid_which_symptoms",
        "Previous_Symptoms_Fever": "think_had_covid_symptom_fever",
        "Previous_Symptoms_Muscle_ache_myalgia": "think_had_covid_symptom_muscle_ache",
        "Previous_Symptoms_Fatigue_weakness": "think_had_covid_symptom_fatigue",
        "Previous_Symptoms_Sore_throat": "think_had_covid_symptom_sore_throat",
        "Previous_Symptoms_Cough": "think_had_covid_symptom_cough",
        "Previous_Symptoms_Shortness_of_breath": "think_had_covid_symptom_shortness_of_breath",
        "Previous_Symptoms_Headache": "think_had_covid_symptom_headache",
        "Previous_Symptoms_Nausea_vomiting": "think_had_covid_symptom_nausea_or_vomiting",
        "Previous_Symptoms_Abdominal_pain": "think_had_covid_symptom_abdominal_pain",
        "Previous_Symptoms_Diarrhoea": "think_had_covid_symptom_diarrhoea",
        "Previous_Symptoms_Loss_of_taste": "think_had_covid_symptom_loss_of_taste",
        "Previous_Symptoms_Loss_of_smell": "think_had_covid_symptom_loss_of_smell",
        "Previous_Symptoms_More_trouble_sleeping_than_usual": "think_had_covid_symptom_more_trouble_sleeping",
        "Previous_Symptoms_Runny_nose_sneezing": "think_had_covid_symptom_runny_nose_or_sneezing",
        "Previous_Symptoms_Noisy_breathing_wheezing": "think_had_covid_symptom_noisy_breathing",
        "Previous_Symptoms_Loss_of_appetite_or_eating_less_than_usual": "think_had_covid_symptom_loss_of_appetite",
        "Previous_Symptoms_Chest_pain": "think_had_covid_symptom_chest_pain",
        "Previous_Symptoms_Palpitations": "think_had_covid_symptom_palpitations",
        "Previous_Symptoms_Vertigo_dizziness": "think_had_covid_symptom_vertigo_or_dizziness",
        "Previous_Symptoms_Worry_anxiety": "think_had_covid_symptom_anxiety",
        "Previous_Symptoms_Low_mood_not_enjoying_anything": "think_had_covid_symptom_low_mood",  # noqa: E501
        "Previous_Symptoms_Memory_loss_or_confusion": "think_had_covid_symptom_memory_loss_or_confusion",
        "Previous_Symptoms_Difficulty_concentrating": "think_had_covid_symptom_difficulty_concentrating",
        "If_yes_Date_of_first_symptoms": "think_had_covid_onset_date",
        "Did_you_contact_NHS": "think_had_covid_contacted_nhs",
        "Were_you_admitted_to_hospital": "think_had_covid_admitted_to_hospital",
        "Have_you_had_a_swab_test": "other_covid_infection_test",
        "If_Yes_What_was_result": "other_covid_infection_test_results",
        "If_positive_Date_of_1st_ve_test": "other_covid_infection_test_first_positive_date",
        "If_all_negative_Date_last_test": "other_covid_infection_test_last_negative_date",
        "Have_you_had_a_blood_test_for_Covid": "other_antibody_test",
        "What_was_the_result_of_the_blood_test": "other_antibody_test_results",
        "Where_was_the_test_done": "other_antibody_test_location",
        "If_ve_Blood_Date_of_1st_ve_test": "other_antibody_test_first_positive_date",
        "If_all_ve_blood_Date_last_ve_test": "other_antibody_test_last_negative_date",
        "Have_Long_Covid_Symptoms": "think_have_long_covid",
        "Long_Covid_Reduce_Activities": "think_have_long_covid_symptom_reduced_ability",  # noqa: E501
        "Long_Covid_Symptoms": "think_have_long_covid_symptoms",
        "Long_Covid_Fever": "think_have_long_covid_symptom_fever",
        "Long_Covid_Weakness_tiredness": "think_have_long_covid_symptom_fatigue",
        "Long_Covid_Diarrhoea": "think_have_long_covid_symptom_diarrhoea",
        "Long_Covid_Loss_of_smell": "think_have_long_covid_symptom_loss_of_smell",
        "Long_Covid_Shortness_of_breath": "think_have_long_covid_symptom_shortness_of_breath",
        "Long_Covid_Vertigo_dizziness": "think_have_long_covid_symptom_vertigo_or_dizziness",
        "Long_Covid_Trouble_sleeping": "think_have_long_covid_symptom_more_trouble_sleeping",
        "Long_Covid_Headache": "think_have_long_covid_symptom_headache",
        "Long_Covid_Nausea_vomiting": "think_have_long_covid_symptom_nausea_or_vomiting",
        "Long_Covid_Loss_of_appetite": "think_have_long_covid_symptom_loss_of_appetite",
        "Long_Covid_Sore_throat": "think_have_long_covid_symptom_sore_throat",
        "Long_Covid_Chest_pain": "think_have_long_covid_symptom_chest_pain",
        "Long_Covid_Worry_anxiety": "think_have_long_covid_symptom_anxiety",
        "Long_Covid_Memory_loss_or_confusion": "think_have_long_covid_symptom_memory_loss_or_confusion",  # noqa: E501
        "Long_Covid_Muscle_ache": "think_have_long_covid_symptom_muscle_ache",
        "Long_Covid_Abdominal_pain": "think_have_long_covid_symptom_abdominal_pain",
        "Long_Covid_Loss_of_taste": "think_have_long_covid_symptom_loss_of_taste",
        "Long_Covid_Cough": "think_have_long_covid_symptom_cough",
        "Long_Covid_Palpitations": "think_have_long_covid_symptom_palpitations",
        "Long_Covid_Low_mood_not_enjoying_anything": "think_have_long_covid_symptom_low_mood",
        "Long_Covid_Difficulty_concentrating": "think_have_long_covid_symptom_difficulty_concentrating",  # noqa: E501
        "Long_Covid_Runny_nose_sneezing": "think_have_long_covid_symptom_runny_nose_or_sneezing",
        "Long_Covid_Noisy_breathing": "think_have_long_covid_symptom_noisy_breathing",
        "Have_you_been_offered_a_vaccination": "cis_covid_vaccine_offered",
        "Vaccinated_Against_Covid": "cis_covid_vaccine_received",
        "Type_Of_Vaccination": "cis_covid_vaccine_type",
        "Vaccination_Other": "cis_covid_vaccine_type_other",
        "Number_Of_Doses": "cis_covid_vaccine_number_of_doses",
        "Date_Of_Vaccination": "cis_covid_vaccine_date",
        "Type_Of_Vaccination_1": "cis_covid_vaccine_type_1",
        "Vaccination_Other_1": "cis_covid_vaccine_type_other_1",
        "Date_Of_Vaccination_1": "cis_covid_vaccine_date_1",
        "Type_Of_Vaccination_2": "cis_covid_vaccine_type_2",
        "Vaccination_Other_2": "cis_covid_vaccine_type_other_2",
        "Date_Of_Vaccination_2": "cis_covid_vaccine_date_2",
        "Type_Of_Vaccination_3": "cis_covid_vaccine_type_3",
        "Vaccination_Other_3": "cis_covid_vaccine_type_other_3",
        "Date_Of_Vaccination_3": "cis_covid_vaccine_date_3",
        "Type_Of_Vaccination_4": "cis_covid_vaccine_type_4",
        "Vaccination_Other_4": "cis_covid_vaccine_type_other_4",
        "Date_Of_Vaccination_4": "cis_covid_vaccine_date_4",
        "Vaccinated_against_flu": "cis_flu_vaccine_received",
        "Have_you_been_outside_UK_since_April": "been_outside_uk_since_april_2020",
        "been_outside_uk_last_country": "been_outside_uk_last_country",
        "been_outside_uk_last_date": "been_outside_uk_last_return_date",
        "Have_you_been_outside_UK_Lastspoke": "been_outside_uk",
    },
    "household_population_variable_name_map": {
        "uprn": "uprn",
        "postcode": "postcode",
        "lsoa11cd": "lower_super_output_area_code_11",
        "cis20cd": "cis_area_code_20",
        "ctry12cd": "country_code_12",
        "ctry20nm": "country_name_12",
        "nhp_cis": "number_of_households_by_cis_area",
        "nhp_cc12": "number_of_households_by_country",
    },
    "tenure_group_variable_map": {
        "numAdult": "lfs_adults_in_household_count",
        "numChild": "lfs_children_in_household_count",
        "dvhsize": "lfs_people_in_household_count",
        "tenure_group": "lfs_tenure_group",
    },
    "address_column_map": {
        "UPRN": "unique_property_reference_code",
        "POSTCODE": "postcode",
        "TOWN_NAME": "town_name",
        "CTRY18NM": "country_name_18",
        "LA_CODE": "local_authority_code",
        "EW": "ew",
        "ADDRESS_TYPE": "address_type",
        "COUNCIL_TAX": "council_tax",
        "ADDRESSBASE_POSTAL": "addressbase_postal",
    },
    "postcode_column_map": {
        "pcd": "postcode",
        "lsoa11": "lower_super_output_area_code_11",
        "ctry": "country_code_12",
        "ru11ind": "rural_urban_classification_11",
        "oac11": "output_area_code_11",
    },
    "lsoa_cis_column_map": {
        "LSOA11CD": "lower_super_output_area_code_11",
        "CIS20CD": "cis_area_code_20",
        "LSOA11NM": "lower_super_output_area_name_11",
        "RGN19CD": "region_code_19",
    },
    "cis_phase_lookup_column_map": {
        "phase_sample": "sample_source_name",
        "country": "country_name_12",
        "issued_wc": "date_sample_created",
    },
    "country_column_map": {
        "CTRY20CD": "country_code_12",
        "CTRY20NM": "country_name_12",
        "LAD20CD": "local_authority_unitary_authority_code",
        "LAD20NM": "local_authority_unitary_authority_name",
    },
    "old_sample_file_column_map": {
        "UAC": "ons_household_id",
        # "lsoa_11": "lower_super_output_area_code_11",
        "lsoa11": "lower_super_output_area_code_11",
        # "ctry12": "country_code_12",
        # "ctry": "country_code_12",
        "sample": "sample_source_name",
        # "rgn/gor9d": "region_code",
        "rgn": "region_code",
        # "gor9d": "region_code",
        "laua": "local_authority_unity_authority_code",
        # "oa11oac11": "output_area_code_11_census_output_area_classification_11",
        # "oa11": "output_area_code_11_census_output_area_classification_11",
        "msoa11": "middle_super_output_area_code_11",
        # "ru11ind": "rural_urban_classification_11",
        "imd": "index_multiple_deprivation",
        # "hh_design_weight_swab": "scaled_design_weight_swab_non_adjusted",
        "dweight_HH": "scaled_design_weight_swab_non_adjusted",
        "dweight_hh_atb": "scaled_design_weight_antibodies_non_adjusted",
        # "hh_design_weight_atb": "scaled_design_weight_antibodies_non_adjusted",
        "tranche": "tranche",
    },
    "new_sample_file_column_map": {
        "UAC": "ons_household_id",
        # "lsoa_11": "lower_super_output_area_code_11",
        "lsoa11": "lower_super_output_area_code_11",
        "ctry": "country_code_12",
        # "rgn/gor9d": "region_code",
        "rgn": "region_code",
        # "gor9d": "region_code",
        "laua": "local_authority_unity_authority_code",
        # "oa11oac11": "output_area_code_11_census_output_area_classification_11",
        "oa11": "output_area_code_11_census_output_area_classification_11",
        "msoa11": "middle_super_output_area_code_11",
        "ru11ind": "rural_urban_classification_11",
        "imd": "index_multiple_deprivation",
    },
    "master_sample_file_column_map": {
        "ons_household_id": "ons_household_id",
        "POSTCODE": "postcode",
        "SAMPLE_TYPE": "sample_type",
    },
    "tranche_column_map": {
        "UAC": "ons_household_id",
        "lsoa_11": "lower_super_output_area_code_11",
        "cis20cd": "cis_area_code_20",
        "ctry12": "country_code_12",
        "ctry_name12": "country_name_12",
        "enrolment_date": "enrolment_date",
        "tranche": "tranche",
    },
    "population_projection_previous_column_map": {
        "laname_21": "local_authority_unitary_authority_name",
        "ladcode_21": "local_authority_unitary_authority_code",
        "region9charcode": "region_code",
        "regionname": "region_name",
        "country9charcode_09": "country_code_12",
        "countryname_09": "country_name_12",
    },
    "population_projection_current_column_map": {
        "laname_21": "local_authority_unitary_authority_name",
        "ladcode_21": "local_authority_unitary_authority_code",
        "region9charcode": "region_code",
        "regionname": "region_name",
        "country9charcode_09": "country_code_12",
        "countryname_09": "country_name_12",
    },
    "aps_column_map": {
        "caseno": "person_id_aps",
        "country": "country_name",
        "ethgbeul": "ethnicity_aps_england_wales_scotland",
        "eth11ni": "ethnicity_aps_northen_ireland",
        "pwta18": "person_level_weight_aps_18",
        "age": "age",
    },
}


survey_response_cast_to_double = [
    "infant_age_months_1",
    "infant_age_months_2",
    "infant_age_months_3",
    "infant_age_months_4",
    "infant_age_months_5",
    "infant_age_months_6",
    "infant_age_months_7",
    "infant_age_months_8",
    "person_not_present_age_1",
    "person_not_present_age_2",
    "person_not_present_age_3",
    "person_not_present_age_4",
    "person_not_present_age_5",
    "person_not_present_age_6",
    "person_not_present_age_7",
    "person_not_present_age_8",
    "person_not_consenting_age_1",
    "person_not_consenting_age_2",
    "person_not_consenting_age_3",
    "person_not_consenting_age_4",
    "person_not_consenting_age_5",
    "person_not_consenting_age_6",
    "person_not_consenting_age_7",
    "person_not_consenting_age_8",
    "person_not_consenting_age_9",
    "no_participants_not_present",
    "no_email_address",
    "bloods_taken",
    "swabs_taken",
]

survey_response_cisd_cast_to_double = [
    "infant_age_months_1",
    "infant_age_months_2",
    "infant_age_months_3",
    "infant_age_months_4",
    "infant_age_months_5",
    "infant_age_months_6",
    "infant_age_months_7",
    "infant_age_months_8",
    "person_not_present_age_1",
    "person_not_present_age_2",
    "person_not_present_age_3",
    "person_not_present_age_4",
    "person_not_present_age_5",
    "person_not_present_age_6",
    "person_not_present_age_7",
    "person_not_present_age_8",
    "person_not_consenting_age_1",
    "person_not_consenting_age_2",
    "person_not_consenting_age_3",
    "person_not_consenting_age_4",
    "person_not_consenting_age_5",
    "person_not_consenting_age_6",
    "person_not_consenting_age_7",
    "person_not_consenting_age_8",
    "person_not_consenting_age_9",
    "household_participants_not_consenting_count",
]
