survey_response_v0_columns_to_cast = [
    "Infant 1 age in Months",
    "Infant 2 age in Months",
    "Infant 3 age in Months",
    "Infant 4 age in Months",
    "Infant 5 age in Months",
    "Infant 6 age in Months",
    "Infant 7 age in Months",
    "Infant 8 age in Months",
    "Person 1 age in Years",
    "Person 2 age in Years",
    "Person 3 age in Years",
    "Person 4 age in Years",
    "Person 5 age in Years",
    "Person 6 age in Years",
    "Person 7 age in Years",
    "Person 8 age in Years",
    "Person 1 Not Consenting (Age in Years)",
    "Person 2 Not Consenting (Age in Years)",
    "Person 3 Not Consenting (Age in Years)",
    "Person 4 Not Consenting (Age in Years)",
    "Person 5 Not Consenting (Age in Years)",
    "Person 6 Not Consenting (Age in Years)",
    "Person 7 Not Consenting (Age in Years)",
    "Person 8 Not Consenting (Age in Years)",
    "Person 9 Not Consenting (Age in Years)",
]


survey_response_v1_columns_to_cast = [
    "Infant_1",
    "Infant_2",
    "Infant_3",
    "Infant_4",
    "Infant_5",
    "Infant_6",
    "Infant_7",
    "Infant_8",
    "Person_1",
    "Person_2",
    "Person_3",
    "Person_4",
    "Person_5",
    "Person_6",
    "Person_7",
    "Person_8",
    "Person_1_Not_Consenting_Age",
    "Person_2_Not_Consenting_Age",
    "Person_3_Not_Consenting_Age",
    "Person_4_Not_Consenting_Age",
    "Person_5_Not_Consenting_Age",
    "Person_6_Not_Consenting_Age",
    "Person_7_Not_Consenting_Age",
    "Person_8_Not_Consenting_Age",
    "Person_9_Not_Consenting_Age",
]


survey_response_v2_columns_to_cast = [
    "Infant_1",
    "Infant_2",
    "Infant_3",
    "Infant_4",
    "Infant_5",
    "Infant_6",
    "Infant_7",
    "Infant_8",
    "Person_1",
    "Person_2",
    "Person_3",
    "Person_4",
    "Person_5",
    "Person_6",
    "Person_7",
    "Person_8",
    "Person_1_Not_Consenting_Age",
    "Person_2_Not_Consenting_Age",
    "Person_3_Not_Consenting_Age",
    "Person_4_Not_Consenting_Age",
    "Person_5_Not_Consenting_Age",
    "Person_6_Not_Consenting_Age",
    "Person_7_Not_Consenting_Age",
    "Person_8_Not_Consenting_Age",
    "Person_9_Not_Consenting_Age",
]
