swab_variable_name_map = {
    "Sample": "swab_sample_barcode",
    "Result": "pcr_result_classification",
    "Date Tested": "pcr_datetime",
    "Lab ID": "pcr_lab_id",
    "testKit": "pcr_method",
    "CH1-Target": "orf1ab_gene_pcr_target",
    "CH1-Result": "orf1ab_gene_pcr_result_classification",
    "CH1-Cq": "orf1ab_gene_pcr_cq_value",
    "CH2-Target": "n_gene_pcr_target",
    "CH2-Result": "n_gene_pcr_result_classification",
    "CH2-Cq": "n_gene_pcr_cq_value",
    "CH3-Target": "s_gene_pcr_target",
    "CH3-Result": "s_gene_pcr_result_classification",
    "CH3-Cq": "s_gene_pcr_cq_value",
    "CH4-Target": "ms2_pcr_target",
    "CH4-Result": "ms2_pcr_result_classification",
    "CH4-Cq": "ms2_pcr_cq_value",
}
