swabs_validation_schema = {
    "swab_barcode": {"type": "string", "regex": r"ONS\d{8}"},
    "swab_result": {"type": "string"},
    "swab_tested_date": {"type": "timestamp"},
    "swab_lab_id": {"type": "string"},
    "test_kit": {"type": "string"},
    "orf1ab_gene_target": {"type": "string"},
    "orf1ab_gene_result": {"type": "string"},
    "orf1ab_gene_cq_value": {"type": "double"},
    "n_gene_target": {"type": "string"},
    "n_gene_result": {"type": "string"},
    "n_gene_cq_value": {"type": "double"},
    "s_gene_target": {"type": "string"},
    "s_gene_result": {"type": "string"},
    "s_gene_cq_value": {"type": "double"},
    "ms2_gene_target": {"type": "string"},
    "ms2_gene_result": {"type": "string"},
    "ms2_gene_cq_value": {"type": "double"},
}
