from typing import Any
from typing import Dict


validation_schemas: Dict[str, Dict[str, Any]]

string_dict = {"type": "string"}

integer_dict = {"type": "integer"}
swab_allowed_pcr_results = ["Inconclusive", "Negative", "Positive", "Rejected"]

projections_column_map = {
    "laname_21": string_dict,
    "ladcode_21": string_dict,
    "region9charcode": string_dict,
    "regionname": string_dict,
    "country9charcode_09": string_dict,
    "countryname_09": string_dict,
    "m0": integer_dict,
    "m1": integer_dict,
    "m2": integer_dict,
    "m3": integer_dict,
    "m4": integer_dict,
    "m5": integer_dict,
    "m6": integer_dict,
    "m7": integer_dict,
    "m8": integer_dict,
    "m9": integer_dict,
    "m10": integer_dict,
    "m11": integer_dict,
    "m12": integer_dict,
    "m13": integer_dict,
    "m14": integer_dict,
    "m15": integer_dict,
    "m16": integer_dict,
    "m17": integer_dict,
    "m18": integer_dict,
    "m19": integer_dict,
    "m20": integer_dict,
    "m21": integer_dict,
    "m22": integer_dict,
    "m23": integer_dict,
    "m24": integer_dict,
    "m25": integer_dict,
    "m26": integer_dict,
    "m27": integer_dict,
    "m28": integer_dict,
    "m29": integer_dict,
    "m30": integer_dict,
    "m31": integer_dict,
    "m32": integer_dict,
    "m33": integer_dict,
    "m34": integer_dict,
    "m35": integer_dict,
    "m36": integer_dict,
    "m37": integer_dict,
    "m38": integer_dict,
    "m39": integer_dict,
    "m40": integer_dict,
    "m41": integer_dict,
    "m42": integer_dict,
    "m43": integer_dict,
    "m44": integer_dict,
    "m45": integer_dict,
    "m46": integer_dict,
    "m47": integer_dict,
    "m48": integer_dict,
    "m49": integer_dict,
    "m50": integer_dict,
    "m51": integer_dict,
    "m52": integer_dict,
    "m53": integer_dict,
    "m54": integer_dict,
    "m55": integer_dict,
    "m56": integer_dict,
    "m57": integer_dict,
    "m58": integer_dict,
    "m59": integer_dict,
    "m60": integer_dict,
    "m61": integer_dict,
    "m62": integer_dict,
    "m63": integer_dict,
    "m64": integer_dict,
    "m65": integer_dict,
    "m66": integer_dict,
    "m67": integer_dict,
    "m68": integer_dict,
    "m69": integer_dict,
    "m70": integer_dict,
    "m71": integer_dict,
    "m72": integer_dict,
    "m73": integer_dict,
    "m74": integer_dict,
    "m75": integer_dict,
    "m76": integer_dict,
    "m77": integer_dict,
    "m78": integer_dict,
    "m79": integer_dict,
    "m80": integer_dict,
    "m81": integer_dict,
    "m82": integer_dict,
    "m83": integer_dict,
    "m84": integer_dict,
    "m85": integer_dict,
    "f0": integer_dict,
    "f1": integer_dict,
    "f2": integer_dict,
    "f3": integer_dict,
    "f4": integer_dict,
    "f5": integer_dict,
    "f6": integer_dict,
    "f7": integer_dict,
    "f8": integer_dict,
    "f9": integer_dict,
    "f10": integer_dict,
    "f11": integer_dict,
    "f12": integer_dict,
    "f13": integer_dict,
    "f14": integer_dict,
    "f15": integer_dict,
    "f16": integer_dict,
    "f17": integer_dict,
    "f18": integer_dict,
    "f19": integer_dict,
    "f20": integer_dict,
    "f21": integer_dict,
    "f22": integer_dict,
    "f23": integer_dict,
    "f24": integer_dict,
    "f25": integer_dict,
    "f26": integer_dict,
    "f27": integer_dict,
    "f28": integer_dict,
    "f29": integer_dict,
    "f30": integer_dict,
    "f31": integer_dict,
    "f32": integer_dict,
    "f33": integer_dict,
    "f34": integer_dict,
    "f35": integer_dict,
    "f36": integer_dict,
    "f37": integer_dict,
    "f38": integer_dict,
    "f39": integer_dict,
    "f40": integer_dict,
    "f41": integer_dict,
    "f42": integer_dict,
    "f43": integer_dict,
    "f44": integer_dict,
    "f45": integer_dict,
    "f46": integer_dict,
    "f47": integer_dict,
    "f48": integer_dict,
    "f49": integer_dict,
    "f50": integer_dict,
    "f51": integer_dict,
    "f52": integer_dict,
    "f53": integer_dict,
    "f54": integer_dict,
    "f55": integer_dict,
    "f56": integer_dict,
    "f57": integer_dict,
    "f58": integer_dict,
    "f59": integer_dict,
    "f60": integer_dict,
    "f61": integer_dict,
    "f62": integer_dict,
    "f63": integer_dict,
    "f64": integer_dict,
    "f65": integer_dict,
    "f66": integer_dict,
    "f67": integer_dict,
    "f68": integer_dict,
    "f69": integer_dict,
    "f70": integer_dict,
    "f71": integer_dict,
    "f72": integer_dict,
    "f73": integer_dict,
    "f74": integer_dict,
    "f75": integer_dict,
    "f76": integer_dict,
    "f77": integer_dict,
    "f78": integer_dict,
    "f79": integer_dict,
    "f80": integer_dict,
    "f81": integer_dict,
    "f82": integer_dict,
    "f83": integer_dict,
    "f84": integer_dict,
    "f85": integer_dict,
}
validation_schemas = {
    "address_schema": {
        "UPRN": string_dict,
        "ORGANISATION_NAME": string_dict,
        "ADDRESS_LINE1": string_dict,
        "ADDRESS_LINE2": string_dict,
        "ADDRESS_LINE3": string_dict,
        "TOWN_NAME": string_dict,
        "POSTCODE": string_dict,
        "ABP_CODE": string_dict,
        "ADDRESS_TYPE": string_dict,
        "COUNCIL_TAX": string_dict,
        "EXTRACT": string_dict,
        "CTRY18NM": string_dict,
        "CTRY18CD": string_dict,
        "EW": string_dict,
        "EPOCH": string_dict,
        "LA_CODE": string_dict,
        "UDPRN": string_dict,
        "LOGICAL_STATUS": string_dict,
        "ADDRESSBASE_POSTAL": string_dict,
    },
    "postcode_schema": {
        "pcd": string_dict,
        "pcd2": string_dict,
        "pcds": string_dict,
        "dointr": string_dict,
        "doterm": string_dict,
        "usertype": string_dict,
        "oseast1m": string_dict,
        "osnrth1m": string_dict,
        "osgrdind": string_dict,
        "oa11": string_dict,
        "cty": string_dict,
        "ced": string_dict,
        "laua": string_dict,
        "ward": string_dict,
        "hlthau": string_dict,
        "nhser": string_dict,
        "ctry": string_dict,
        "rgn": string_dict,
        "pcon": string_dict,
        "eer": string_dict,
        "teclec": string_dict,
        "ttwa": string_dict,
        "pct": string_dict,
        "itl": string_dict,
        "park": string_dict,
        "lsoa11": string_dict,
        "msoa11": string_dict,
        "wz11": string_dict,
        "ccg": string_dict,
        "bua11": string_dict,
        "buasd11": string_dict,
        "ru11ind": string_dict,
        "oac11": string_dict,
        "lat": string_dict,
        "long": string_dict,
        "lep1": string_dict,
        "lep2": string_dict,
        "pfa": string_dict,
        "imd": string_dict,
        "calncv": string_dict,
        "stp": string_dict,
    },
    "lsoa_cis_schema": {
        "LSOA11CD": string_dict,
        "LSOA11NM": string_dict,
        "CIS20CD": string_dict,
        "RGN19CD": string_dict,
    },
    "cis_phase_schema": {  # check
        "phase_name": string_dict,
        "phase_visits": string_dict,
        "phase_sample": string_dict,
        "country": string_dict,
        "source": string_dict,
        "issued_wc": string_dict,
        "fieldwork_wc": string_dict,
    },
    "country_schema": {
        "LAD20CD": string_dict,
        "LAD20NM": string_dict,
        "CTRY20CD": string_dict,
        "CTRY20NM": string_dict,
    },
    "old_sample_file_schema": {
        "sample": string_dict,
        "UAC": string_dict,
        "GOR9D": string_dict,
        "DVHSize": string_dict,
        "UA19NM": string_dict,
        "LHB19CD": string_dict,
        "LHB19NM": string_dict,
        "country_sample": string_dict,
        "laua": string_dict,
        "rgn": string_dict,
        "lsoa11": string_dict,
        "msoa11": string_dict,
        "imd": string_dict,
        "sample_direct": string_dict,
        "tranche": string_dict,
        "interim_id": string_dict,
        "dweight_HH": string_dict,
        "dweight_hh_atb": string_dict,
    },
    "new_sample_file_schema": {
        "UAC": string_dict,
        "sample": string_dict,
        "LA_CODE": string_dict,
        "Bloods": string_dict,
        "oa11": string_dict,
        "laua": string_dict,
        "ctry": string_dict,
        "CUSTODIAN_REGION_CODE": string_dict,
        "lsoa11": string_dict,
        "msoa11": string_dict,
        "ru11ind": string_dict,
        "oac11": string_dict,
        "rgn": string_dict,
        "imd": string_dict,
        "interim_id": string_dict,
    },
    "master_sample_file_schema": {
        "ons_household_id": string_dict,
        "FULL_NAME": string_dict,
        "ADDRESS_LINE_1": string_dict,
        "ADDRESS_LINE_2": string_dict,
        "ADDRESS_LINE_3": string_dict,
        "POSTCODE": string_dict,
        "REGION": string_dict,
        "COUNTRY": string_dict,
        "BLOODS": string_dict,
        "WEEK": string_dict,
        "SAMPLE_TYPE": string_dict,
        "UPRN": string_dict,
        "UDPRN": string_dict,
        "TOWN_NAME": string_dict,
    },
    "tranche_schema": {
        "enrolment_date": string_dict,
        "UAC": integer_dict,
        "lsoa_11": string_dict,
        "cis20cd": string_dict,
        "ctry12": string_dict,
        "ctry_name12": string_dict,
        "tranche": integer_dict,
    },
    "aps_schema": {
        "caseno": integer_dict,
        "age": integer_dict,
        "country": integer_dict,
        "ethgbeul": integer_dict,
        "eth11ni": string_dict,  # double check
        "pwta18": integer_dict,
    },
    "csv_lookup_schema": {
        "id": string_dict,
        "dataset_name": string_dict,
        "target_column_name": string_dict,
        "old_value": string_dict,
        "new_value": string_dict,
    },
    "swab_validation_schema": {
        "Sample": {"type": "string", "regex": r"ONS\d{8}"},
        "Result": {"type": "string", "allowed": ["Negative", "Positive", "Void"]},
        "Date Tested": {"type": "string", "nullable": True},
        "Lab ID": string_dict,
        "CH1-Target": {"type": "string", "allowed": ["ORF1ab"]},
        "CH1-Result": {"type": "string", "allowed": swab_allowed_pcr_results},
        "CH1-Cq": {"type": "double", "nullable": True, "min": 0},
        "CH2-Target": {"type": "string", "allowed": ["N gene"]},
        "CH2-Result": {"type": "string", "allowed": swab_allowed_pcr_results},
        "CH2-Cq": {"type": "double", "nullable": True, "min": 0},
        "CH3-Target": {"type": "string", "allowed": ["S gene"]},
        "CH3-Result": {"type": "string", "allowed": swab_allowed_pcr_results},
        "CH3-Cq": {"type": "double", "nullable": True, "min": 0},
        "CH4-Target": {"type": "string", "allowed": ["MS2"]},
        "CH4-Result": {"type": "string", "allowed": swab_allowed_pcr_results},
        "CH4-Cq": {"type": "double", "nullable": True, "min": 0},
    },
    "swab_validation_schema_testKit": {
        "Sample": {"type": "string", "regex": r"ONS\d{8}"},
        "Result": {"type": "string", "allowed": ["Negative", "Positive", "Void"]},
        "Date Tested": {"type": "string", "nullable": True},
        "Lab ID": string_dict,
        "testKit": string_dict,
        "CH1-Target": {"type": "string", "allowed": ["ORF1ab"]},
        "CH1-Result": {"type": "string", "allowed": swab_allowed_pcr_results},
        "CH1-Cq": {"type": "double", "nullable": True, "min": 0},
        "CH2-Target": {"type": "string", "allowed": ["N gene"]},
        "CH2-Result": {"type": "string", "allowed": swab_allowed_pcr_results},
        "CH2-Cq": {"type": "double", "nullable": True, "min": 0},
        "CH3-Target": {"type": "string", "allowed": ["S gene"]},
        "CH3-Result": {"type": "string", "allowed": swab_allowed_pcr_results},
        "CH3-Cq": {"type": "double", "nullable": True, "min": 0},
        "CH4-Target": {"type": "string", "allowed": ["MS2"]},
        "CH4-Result": {"type": "string", "allowed": swab_allowed_pcr_results},
        "CH4-Cq": {"type": "double", "nullable": True, "min": 0},
    },
    "blood_validation_schema": {
        "Serum Source ID": {"type": "string", "regex": r"ONS\d{8}"},
        "Blood Sample Type": {"type": "string", "allowed": ["Venous", "Capillary"]},
        "Plate Barcode": {"type": "string", "regex": r"(ON[BS]|MIX)_[0-9]{6}[C|V]S(-[0-9]+)"},
        "Well ID": {"type": "string", "regex": r"[A-Z][0-9]{2}"},
        "Detection": {"type": "string", "allowed": ["DETECTED", "NOT detected", "failed"]},
        "Monoclonal quantitation (Colourimetric)": {"type": "double", "nullable": True, "min": 0},
        "Monoclonal bounded quantitation (Colourimetric)": {"type": "float"},
        "Monoclonal undiluted quantitation (Colourimetric)": {"type": "float"},
        "Date ELISA Result record created": {"type": "string", "nullable": True},
        "Date Samples Arrayed Oxford": {"type": "string", "nullable": True},
        "Date Samples Received Oxford": {"type": "string", "nullable": True},
        "Voyager Date Created": {"type": "string", "nullable": True},
    },
    "unassayed_blood_validation_schema": {
        "Date Received": string_dict,
        "Sample ID": string_dict,
        "Rejection Code": integer_dict,
        "Reason for rejection": string_dict,
        "Sample Type V/C": string_dict,
    },
    "historical_blood_validation_schema": {
        "blood_barcode_OX": string_dict,
        "received_ox_date": string_dict,
        "result_tdi": string_dict,
        "result_siemens": string_dict,
        "result_tdi_date": string_dict,
        "assay_tdi": {"type": "float"},
        "assay_category": string_dict,
        "assay_siemens": {"type": "float"},
        "plate_tdi": string_dict,
        "well_tdi": string_dict,
        "lims_id": string_dict,
        "blood_sample_type": string_dict,
        "voyager_blood_dt_time": string_dict,
        "arrayed_ox_date": string_dict,
        "assay_mabs": {"type": "float"},
        "platestorage": string_dict,
    },
    "sample_direct_eng_wc_schema": {
        "unique_access_code": {"type": "string", "regex": r"^\d{12}"},
        "local_authority_code": {"type": "string", "regex": r"^[E,W,S]\d{8}"},
        "in_blood_cohort": {"type": "integer", "min": 0, "max": 1},
        "output_area_code": {"type": "string", "regex": r"^[E,W,S]00\d{6}"},
        "local_authority_unity_authority_code": {"type": "string", "regex": r"^[E,W,S]\d{8}"},
        "country_code": {"type": "string", "regex": r"^[E,W,S]\d{8}"},
        "custodian_region_code": {"type": "string", "regex": r"^[E,W,S]\d{8}"},
        "lower_super_output_area_code": {"type": "string", "regex": r"^[E,W,S]\d{8}"},
        "middle_super_output_area_code": {"type": "string", "regex": r"^[E,W,S]\d{8}"},
        "rural_urban_classification": {"type": "string", "regex": r"^([a-zA-Z]\d{1}|\d{1})"},
        "census_output_area_classification": {"type": "string", "regex": r"^\d{1}[a-zA-Z]\d{1}"},
        "region_code": {"type": "string", "regex": r"^[E,W,S]\d{8}"},
        "index_multiple_deprivation": {"type": "integer", "min": 0, "max": 32844},
        "cis_area_indicator": {"type": "integer", "min": 1, "max": 128},
    },
    "sample_northern_ireland_schema": {
        "unique_access_code": {"type": "string", "regex": r"^\d{12}"},
        "sample_week_indicator": {"type": "string", "regex": r"^\d{1}[a-zA-Z]{3}"},
        "output_area_code": {"type": "string", "regex": r"^N00\d{6}"},
        "local_authority_unity_authority_code": {"type": "string", "regex": r"^N\d{8}"},
        "country_code": {"type": "string", "regex": r"^N\d{8}"},
        "custodian_region_code": {"type": "string", "regex": r"^N\d{8}"},
        "lower_super_output_area_code": {"type": "string", "regex": r"^N\d{8}"},
        "middle_super_output_area_code": {"type": "string", "regex": r"^N\d{8}"},
        "census_output_area_classification": {"type": "string", "regex": r"^\d{1}[a-zA-Z]\d{1}"},
        "lower_super_output_area_name": {"type": "string", "regex": r"[a-zA-Z]{2,}}"},
        "cis_area_code": {"type": "string", "regex": r"^J\d{8}"},
        "region_code": {"type": "string", "regex": r"^N\d{8}"},
        "index_multiple_deprivation": {"type": "integer", "min": 1, "max": 890},
        "cis_area_indicator": {"type": "integer", "min": 999, "max": 999},
    },
    "survey_responses_v0_validation_schema": {
        "ONS Household ID": string_dict,
        "Visit ID": string_dict,
        "Type of Visit": string_dict,
        "Participant_Visit_status": string_dict,
        "Withdrawal_reason": string_dict,
        "Visit Date/Time": string_dict,
        "Street": string_dict,
        "City": string_dict,
        "County": string_dict,
        "Postcode": string_dict,
        "Phase": string_dict,
        "No. Paticicpants not Consented": string_dict,
        "Reason Participants not Consented": string_dict,
        "No. Participants not present for Visit": string_dict,
        "Reason Participants not present on Visit": string_dict,
        "Any Household Members Under 2 Years": string_dict,
        "Infant 1 age in Months": string_dict,
        "Infant 2 age in Months": string_dict,
        "Infant 3 age in Months": string_dict,
        "Infant 4 age in Months": string_dict,
        "Infant 5 age in Months": string_dict,
        "Infant 6 age in Months": string_dict,
        "Infant 7 age in Months": string_dict,
        "Infant 8 age in Months": string_dict,
        "Any Household Members Over 2 Not Present": string_dict,
        "Person 1 age in Years": string_dict,
        "Person 2 age in Years": string_dict,
        "Person 3 age in Years": string_dict,
        "Person 4 age in Years": string_dict,
        "Person 5 age in Years": string_dict,
        "Person 6 age in Years": string_dict,
        "Person 7 age in Years": string_dict,
        "Person 8 age in Years": string_dict,
        "Person 1 Not Consenting (Age in Years)": string_dict,
        "Reason for Not Consenting (Person 1)": string_dict,
        "Person 2 Not Consenting (Age in Years)": string_dict,
        "Reason for Not Consenting (Person 2)": string_dict,
        "Person 3 Not Consenting (Age in Years)": string_dict,
        "Reason for Not Consenting (Person 3)": string_dict,
        "Person 4 Not Consenting (Age in Years)": string_dict,
        "Reason for Not Consenting (Person 4)": string_dict,
        "Person 5 Not Consenting (Age in Years)": string_dict,
        "Reason for Not Consenting (Person 5)": string_dict,
        "Person 6 Not Consenting (Age in Years)": string_dict,
        "Reason for Not Consenting (Person 6)": string_dict,
        "Person 7 Not Consenting (Age in Years)": string_dict,
        "Reason for Not Consenting (Person 7)": string_dict,
        "Person 8 Not Consenting (Age in Years)": string_dict,
        "Reason for Not Consenting (Person 8)": string_dict,
        "Person 9 Not Consenting (Age in Years)": string_dict,
        "Reason for Not Consenting (Person 9)": string_dict,
        "Participant ID": string_dict,
        "Suffix": string_dict,
        "Full Name": string_dict,
        "DoB": string_dict,
        "Email": string_dict,
        "No Email Address": string_dict,
        "Bloods Taken": string_dict,
        "Bloods Barcode 1": string_dict,
        "Swab Taken": string_dict,
        "Swab Barcode 1": string_dict,
        "Date/Time Samples Taken": string_dict,
        "Sex": string_dict,
        "Gender": string_dict,
        "Ethnicity": string_dict,
        "Consent to First Visit": string_dict,
        "Consent to Five Visits": string_dict,
        "Consent to Sixteen Visits": string_dict,
        "Consent to be Contacted Extra Research": string_dict,
        "Consent to Blood Samples": string_dict,
        "Consent to Surplus Blood Sample": string_dict,
        "Working Status (Main Job)": string_dict,
        "Job Title": string_dict,
        "Main Job Responsibilities": string_dict,
        "Working Location": string_dict,
        "No. days a week working outside of home?": string_dict,
        "Do you work in healthcare?": string_dict,
        "Do you work in social care?": string_dict,
        "Do you have any of these symptoms Today?": string_dict,
        "Symptoms today": string_dict,
        "Symptoms today- Fever": string_dict,
        "Symptoms today- Muscle ache (myalgia)": string_dict,
        "Symptoms today- Fatigue (weakness)": string_dict,
        "Symptoms today- Sore throat": string_dict,
        "Symptoms today- Cough": string_dict,
        "Symptoms today- Shortness of breath": string_dict,
        "Symptoms today- Headache": string_dict,
        "Symptoms today- Nausea/vomiting": string_dict,
        "Symptoms today- Abdominal pain": string_dict,
        "Symptoms today- Diarrhoea": string_dict,
        "Symptoms today- Loss of taste": string_dict,
        "Symptoms today- Loss of smell": string_dict,
        "Are you self Isolating?": string_dict,
        "Received shielding letter from NHS?": string_dict,
        "Do you think you have Covid Symptoms?": string_dict,
        "Contact with Known Positive COVID19 Case": string_dict,
        "If Known; Last contact date": string_dict,
        "If Known; Type of contact": string_dict,
        "Contact with Suspected Covid19 Case": string_dict,
        "If Suspect; Last contact date": string_dict,
        "If Suspect; Type of contact": string_dict,
        "Household been Hospital last 2 wks": string_dict,
        "Household been in Care home last 2 wks": string_dict,
        "Do you think you have had Covid 19?": string_dict,
        "Which symptoms did you have?": string_dict,
        "Previous Symptoms-Fever": string_dict,
        "Previous Symptoms-Muscle ache (myalgia)": string_dict,
        "Previous Symptoms-Fatigue (weakness)": string_dict,
        "Previous Symptoms-Sore throat": string_dict,
        "Previous Symptoms-Cough": string_dict,
        "Previous Symptoms-Shortness of breath": string_dict,
        "Previous Symptoms-Headache": string_dict,
        "Previous Symptoms-Nausea/vomiting": string_dict,
        "Previous Symptoms-Abdominal pain": string_dict,
        "Previous Symptoms-Diarrhoea": string_dict,
        "Previous Symptoms-Loss of taste": string_dict,
        "Previous Symptoms-Loss of smell": string_dict,
        "If Yes; Date of first symptoms": string_dict,
        "Did you contact NHS?": string_dict,
        "If Yes; Were you tested": string_dict,
        "If Yes;Test Result": string_dict,
        "Were you admitted to hospital?": string_dict,
    },
    "survey_responses_v1_validation_schema": {
        "ons_household_id": string_dict,
        "Visit_ID": string_dict,
        "Type_of_Visit": string_dict,
        "Participant_Visit_status": string_dict,
        "Withdrawal_reason": string_dict,
        "Visit_Date_Time": string_dict,
        "Street": string_dict,
        "City": string_dict,
        "County": string_dict,
        "Postcode": string_dict,
        "Cohort": string_dict,
        "No_Paticicpants_not_Consented": string_dict,
        "Reason_Participants_not_Consented": string_dict,
        "No_Participants_not_present_for_Visit": string_dict,
        "Reason_Participants_not_present_on_Visit": string_dict,
        "Household_Members_Under_2_Years": string_dict,
        "Infant_1": string_dict,
        "Infant_2": string_dict,
        "Infant_3": string_dict,
        "Infant_4": string_dict,
        "Infant_5": string_dict,
        "Infant_6": string_dict,
        "Infant_7": string_dict,
        "Infant_8": string_dict,
        "Household_Members_Over_2_and_Not_Present": string_dict,
        "Person_1": string_dict,
        "Person_2": string_dict,
        "Person_3": string_dict,
        "Person_4": string_dict,
        "Person_5": string_dict,
        "Person_6": string_dict,
        "Person_7": string_dict,
        "Person_8": string_dict,
        "Person_1_Not_Consenting_Age": string_dict,
        "Person1_Reason_for_Not_Consenting": string_dict,
        "Person_2_Not_Consenting_Age": string_dict,
        "Person2_Reason_for_Not_Consenting": string_dict,
        "Person_3_Not_Consenting_Age": string_dict,
        "Person3_Reason_for_Not_Consenting": string_dict,
        "Person_4_Not_Consenting_Age": string_dict,
        "Person4_Reason_for_Not_Consenting": string_dict,
        "Person_5_Not_Consenting_Age": string_dict,
        "Person5_Reason_for_Not_Consenting": string_dict,
        "Person_6_Not_Consenting_Age": string_dict,
        "Person6_Reason_for_Not_Consenting": string_dict,
        "Person_7_Not_Consenting_Age": string_dict,
        "Person7_Reason_for_Not_Consenting": string_dict,
        "Person_8_Not_Consenting_Age": string_dict,
        "Person8_Reason_for_Not_Consenting": string_dict,
        "Person_9_Not_Consenting_Age": string_dict,
        "Person9_Reason_for_Not_Consenting": string_dict,
        "Participant_id": string_dict,
        "Title": string_dict,
        "First_Name": string_dict,
        "Last_Name": string_dict,
        "DoB": string_dict,
        "Email": string_dict,
        "No_Email_address": string_dict,
        "Bloods_Taken": string_dict,
        "bloods_barcode_1": string_dict,
        "Swab_Taken": string_dict,
        "Swab_Barcode_1": string_dict,
        "Date_Time_Samples_Taken": string_dict,
        "Sex": string_dict,
        "Gender": string_dict,
        "Ethnicity": string_dict,
        "Ethnicity_Other": string_dict,
        "Consent_to_First_Visit": string_dict,
        "Consent_to_Five_Visits": string_dict,
        "Consent_to_Sixteen_Visits": string_dict,
        "Consent_to_Blood_Test": string_dict,
        "Consent_to_be_Contacted_Extra_Research": string_dict,
        "Consent_to_use_of_Surplus_Blood_Samples": string_dict,
        "What_is_the_title_of_your_main_job": string_dict,
        "What_do_you_do_in_your_main_job_business": string_dict,
        "Occupations_sectors_do_you_work_in": string_dict,
        "occupation_sector_other": string_dict,
        "Work_in_a_nursing_residential_care_home": string_dict,
        "Do_you_currently_work_in_healthcare": string_dict,
        "Direct_contact_patients_clients_resid": string_dict,
        "Have_physical_mental_health_or_illnesses": string_dict,
        "physical_mental_health_or_illness_reduces_activity_ability": string_dict,
        "Have_you_ever_smoked_regularly": string_dict,
        "Do_you_currently_smoke_or_vape": string_dict,
        "Smoke_Yes_cigarettes": string_dict,
        "Smoke_Yes_cigar": string_dict,
        "Smoke_Yes_pipe": string_dict,
        "Smoke_Yes_vape_e_cigarettes": string_dict,
        "Smoke_No": string_dict,
        "Smoke_Hookah_shisha pipes": string_dict,
        "What_is_your_current_working_status": string_dict,
        "Where_are_you_mainly_working_now": string_dict,
        "How_often_do_you_work_elsewhere": string_dict,
        "Can_you_socially_distance_at_work": string_dict,
        "How_do_you_get_to_and_from_work_school": string_dict,
        "Had_symptoms_in_the_last_7_days": string_dict,
        "Which_symptoms_in_the_last_7_days": string_dict,
        "Date_of_first_symptom_onset": string_dict,
        "Symptoms_7_Fever": string_dict,
        "Symptoms_7_Muscle_ache_myalgia": string_dict,
        "Symptoms_7_Fatigue_weakness": string_dict,
        "Symptoms_7_Sore_throat": string_dict,
        "Symptoms_7_Cough": string_dict,
        "Symptoms_7_Shortness_of_breath": string_dict,
        "Symptoms_7_Headache": string_dict,
        "Symptoms_7_Nausea_vomiting": string_dict,
        "Symptoms_7_Abdominal_pain": string_dict,
        "Symptoms_7_Diarrhoea": string_dict,
        "Symptoms_7_Loss_of_taste": string_dict,
        "Symptoms_7_Loss_of_smell": string_dict,
        "Are_you_self_Isolating_S2": string_dict,
        "Do_you_think_you_have_Covid_Symptoms": string_dict,
        "Contact_Known_Positive_COVID19_28_days": string_dict,
        "If_Known_last_contact_date": string_dict,
        "If_Known_type_of_contact_S2": string_dict,
        "Contact_Suspect_Positive_COVID19_28_d": string_dict,
        "If_suspect_last_contact_date": string_dict,
        "If_suspect_type_of_contact_S2": string_dict,
        "Household_been_Hospital_last_28_days": string_dict,
        "Household_been_in_Care_Home_last_28_days": string_dict,
        "Hours_a_day_with_someone_else": string_dict,
        "Physical_Contact_18yrs": string_dict,
        "Physical_Contact_18_to_69_yrs": string_dict,
        "Physical_Contact_70_yrs": string_dict,
        "Social_Distance_Contact_18yrs": string_dict,
        "Social_Distance_Contact_18_to_69_yrs": string_dict,
        "Social_Distance_Contact_70_yrs": string_dict,
        "1Hour_or_Longer_another_person_home": string_dict,
        "1Hour_or_Longer_another_person_yourhome": string_dict,
        "Times_Outside_Home_For_Shopping": string_dict,
        "Face_Covering_or_Mask_outside_of_home": string_dict,
        "Do_you_think_you_have_had_Covid_19": string_dict,
        "think_had_covid_19_any_symptoms": string_dict,
        "think_had_covid_19_which_symptoms": string_dict,
        "Previous_Symptoms_Fever": string_dict,
        "Previous_Symptoms_Muscle_ache_myalgia": string_dict,
        "Previous_Symptoms_Fatigue_weakness": string_dict,
        "Previous_Symptoms_Sore_throat": string_dict,
        "Previous_Symptoms_Cough": string_dict,
        "Previous_Symptoms_Shortness_of_breath": string_dict,
        "Previous_Symptoms_Headache": string_dict,
        "Previous_Symptoms_Nausea_vomiting": string_dict,
        "Previous_Symptoms_Abdominal_pain": string_dict,
        "Previous_Symptoms_Diarrhoea": string_dict,
        "Previous_Symptoms_Loss_of_taste": string_dict,
        "Previous_Symptoms_Loss_of_smell": string_dict,
        "If_yes_Date_of_first_symptoms": string_dict,
        "Did_you_contact_NHS": string_dict,
        "Were_you_admitted_to_hospital": string_dict,
        "Have_you_had_a_swab_test": string_dict,
        "If_Yes_What_was_result": string_dict,
        "If_positive_Date_of_1st_ve_test": string_dict,
        "If_all_negative_Date_last_test": string_dict,
        "Have_you_had_a_blood_test_for_Covid": string_dict,
        "What_was_the_result_of_the_blood_test": string_dict,
        "Where_was_the_test_done": string_dict,
        "If_ve_Blood_Date_of_1st_ve_test": string_dict,
        "If_all_ve_blood_Date_last_ve_test": string_dict,
        "Have_you_been_outside_UK_since_April": string_dict,
        "been_outside_uk_last_country": string_dict,
        "been_outside_uk_last_date": string_dict,
        "Vaccinated_Against_Covid": string_dict,
        "Date_Of_Vaccination": string_dict,
    },
    "survey_responses_v2_validation_schema": {
        "ons_household_id": string_dict,
        "Visit_ID": string_dict,
        "Visit Status": string_dict,
        "Participant_Visit_status": string_dict,
        "Participant_status": string_dict,
        "Withdrawal_reason": string_dict,
        "Withdrawn_Type": string_dict,
        "NotAttendReason": string_dict,
        "Type_of_Visit": string_dict,
        "Visit_Order": string_dict,
        "Work_Type_Picklist": string_dict,
        "Visit_Date_Time": string_dict,
        "Visit_Date_type": string_dict,
        "actual_visit_date": string_dict,
        "Deferred": string_dict,
        "Street": string_dict,
        "City": string_dict,
        "County": string_dict,
        "Postcode": string_dict,
        "Cohort": string_dict,
        "Fingerprick_Status": string_dict,
        "Household_Members_Under_2_Years": string_dict,
        "Infant_1": string_dict,
        "Infant_2": string_dict,
        "Infant_3": string_dict,
        "Infant_4": string_dict,
        "Infant_5": string_dict,
        "Infant_6": string_dict,
        "Infant_7": string_dict,
        "Infant_8": string_dict,
        "Household_Members_Over_2_and_Not_Present": string_dict,
        "Person_1": string_dict,
        "Person_2": string_dict,
        "Person_3": string_dict,
        "Person_4": string_dict,
        "Person_5": string_dict,
        "Person_6": string_dict,
        "Person_7": string_dict,
        "Person_8": string_dict,
        "Person_1_Not_Consenting_Age": string_dict,
        "Person1_Reason_for_Not_Consenting": string_dict,
        "Person_2_Not_Consenting_Age": string_dict,
        "Person2_Reason_for_Not_Consenting": string_dict,
        "Person_3_Not_Consenting_Age": string_dict,
        "Person3_Reason_for_Not_Consenting": string_dict,
        "Person_4_Not_Consenting_Age": string_dict,
        "Person4_Reason_for_Not_Consenting": string_dict,
        "Person_5_Not_Consenting_Age": string_dict,
        "Person5_Reason_for_Not_Consenting": string_dict,
        "Person_6_Not_Consenting_Age": string_dict,
        "Person6_Reason_for_Not_Consenting": string_dict,
        "Person_7_Not_Consenting_Age": string_dict,
        "Person7_Reason_for_Not_Consenting": string_dict,
        "Person_8_Not_Consenting_Age": string_dict,
        "Person8_Reason_for_Not_Consenting": string_dict,
        "Person_9_Not_Consenting_Age": string_dict,
        "Person9_Reason_for_Not_Consenting": string_dict,
        "Participant_id": string_dict,
        "Title": string_dict,
        "First_Name": string_dict,
        "Middle_Name": string_dict,
        "Last_Name": string_dict,
        "DoB": string_dict,
        "Email": string_dict,
        "Have_landline_number": string_dict,
        "Have_mobile_number": string_dict,
        "Have_email_address": string_dict,
        "Prefer_receive_vouchers": string_dict,
        "Confirm_receive_vouchers": string_dict,
        "No_Email_address": string_dict,
        "Able_to_take_blood": string_dict,
        "No_Blood_reason_fingerprick": string_dict,
        "No_Blood_reason_venous": string_dict,
        "bloods_barcode_1": string_dict,
        "Swab_Barcode_1": string_dict,
        "Date_Time_Samples_Taken": string_dict,
        "Sex": string_dict,
        "Gender": string_dict,
        "Ethnic_group": string_dict,
        "Ethnicity": string_dict,
        "Ethnicity_Other": string_dict,
        "Consent_to_First_Visit": string_dict,
        "Consent_to_Five_Visits": string_dict,
        "Consent_to_April_22": string_dict,
        "Consent_to_Sixteen_Visits": string_dict,
        "Consent_to_Blood_Test": string_dict,
        "Consent_to_Finger_prick_A1_A3": string_dict,
        "Consent_to_extend_study_under_16_B1_B3": string_dict,
        "Consent_to_be_Contacted_Extra_Research": string_dict,
        "Consent_to_be_Contacted_Extra_ResearchYN": string_dict,
        "Consent_to_use_of_Surplus_Blood_Samples": string_dict,
        "Consent_to_use_of_Surplus_Blood_SamplesYN": string_dict,
        "Approached_for_blood_samples?": string_dict,
        "Consent_to_blood_samples_if_positive": string_dict,
        "Consent_to_blood_samples_if_positiveYN": string_dict,
        "Consent_to_fingerprick_blood_samples": string_dict,
        "Accepted_invite_to_fingerprick": string_dict,
        "Re_consented_for_blood": string_dict,
        "Agreed_to_additional_consent_visit": string_dict,
        "Additional_Consent_Requirement": string_dict,
        "What_is_the_title_of_your_main_job": string_dict,
        "What_do_you_do_in_your_main_job_business": string_dict,
        "Occupations_sectors_do_you_work_in": string_dict,
        "occupation_sector_other": string_dict,
        "Work_in_a_nursing_residential_care_home": string_dict,
        "Do_you_currently_work_in_healthcare": string_dict,
        "Direct_contact_patients_clients_resid": string_dict,
        "Have_physical_mental_health_or_illnesses": string_dict,
        "physical_mental_health_or_illness_reduces_activity_ability": string_dict,
        "Have_you_ever_smoked_regularly": string_dict,
        "Do_you_currently_smoke_or_vape": string_dict,
        "Do_you_currently_smoke_or_vape_at_all": string_dict,
        "Smoke_Yes_cigarettes": string_dict,
        "Smoke_Yes_cigar": string_dict,
        "Smoke_Yes_pipe": string_dict,
        "Smoke_Yes_vape_e_cigarettes": string_dict,
        "Smoke_Hookah/shisha pipes": string_dict,
        "What_is_your_current_working_status": string_dict,
        "Paid_employment": string_dict,
        "Main_Job_Changed": string_dict,
        "Where_are_you_mainly_working_now": string_dict,
        "How_often_do_you_work_elsewhere": string_dict,
        "How_do_you_get_to_and_from_work_school": string_dict,
        "Can_you_socially_distance_at_work": string_dict,
        "Had_symptoms_in_the_last_7_days": string_dict,
        "Which_symptoms_in_the_last_7_days": string_dict,
        "Date_of_first_symptom_onset": string_dict,
        "Symptoms_7_Fever": string_dict,
        "Symptoms_7_Muscle_ache_myalgia": string_dict,
        "Symptoms_7_Fatigue_weakness": string_dict,
        "Symptoms_7_Sore_throat": string_dict,
        "Symptoms_7_Cough": string_dict,
        "Symptoms_7_Shortness_of_breath": string_dict,
        "Symptoms_7_Headache": string_dict,
        "Symptoms_7_Nausea_vomiting": string_dict,
        "Symptoms_7_Abdominal_pain": string_dict,
        "Symptoms_7_Diarrhoea": string_dict,
        "Symptoms_7_Loss_of_taste": string_dict,
        "Symptoms_7_Loss_of_smell": string_dict,
        "Symptoms_7_More_trouble_sleeping_than_usual": string_dict,
        "Symptoms_7_Runny_nose_sneezing": string_dict,
        "Symptoms_7_Noisy_breathing_wheezing": string_dict,
        "Symptoms_7_Loss_of_appetite_or_eating_less_than_usual": string_dict,
        "Symptoms_7_Chest_pain": string_dict,
        "Symptoms_7_Palpitations": string_dict,
        "Symptoms_7_Vertigo_dizziness": string_dict,
        "Symptoms_7_Worry_anxiety": string_dict,
        "Symptoms_7_Low_mood_not_enjoying_anything": string_dict,
        "Symptoms_7_Memory_loss_or_confusion": string_dict,
        "Symptoms_7_Difficulty_concentrating": string_dict,
        "Are_you_self_Isolating_S2": string_dict,
        "Do_you_think_you_have_Covid_Symptoms": string_dict,
        "Contact_Known_Positive_COVID19_28_days": string_dict,
        "If_Known_last_contact_date": string_dict,
        "If_Known_type_of_contact_S2": string_dict,
        "Contact_Suspect_Positive_COVID19_28_d": string_dict,
        "If_suspect_last_contact_date": string_dict,
        "If_suspect_type_of_contact_S2": string_dict,
        "You_been_Hospital_last_28_days": string_dict,
        "OtherHouse_been_Hospital_last_28_days": string_dict,
        "Your_been_in_Care_Home_last_28_days": string_dict,
        "OtherHouse_been_in_Care_Home_last_28_days": string_dict,
        "Hours_a_day_with_someone_else": string_dict,
        "Physical_Contact_18yrs": string_dict,
        "Physical_Contact_18_to_69_yrs": string_dict,
        "Physical_Contact_70_yrs": string_dict,
        "Social_Distance_Contact_18yrs": string_dict,
        "Social_Distance_Contact_18_to_69_yrs": string_dict,
        "Social_Distance_Contact_70_yrs": string_dict,
        "1Hour_or_Longer_another_person_home": string_dict,
        "1Hour_or_Longer_another_person_yourhome": string_dict,
        "Times_Outside_Home_For_Shopping": string_dict,
        "Shopping_last_7_days": string_dict,
        "Socialise_last_7_days": string_dict,
        "Regular_testing_COVID": string_dict,
        "Face_Covering_or_Mask_outside_of_home": string_dict,
        "Face_Mask_Work_Place": string_dict,
        "Face_Mask_Other_Enclosed_Places": string_dict,
        "Do_you_think_you_have_had_Covid_19": string_dict,
        "think_had_covid_19_any_symptoms": string_dict,
        "think_had_covid_19_which_symptoms": string_dict,
        "Previous_Symptoms_Fever": string_dict,
        "Previous_Symptoms_Muscle_ache_myalgia": string_dict,
        "Previous_Symptoms_Fatigue_weakness": string_dict,
        "Previous_Symptoms_Sore_throat": string_dict,
        "Previous_Symptoms_Cough": string_dict,
        "Previous_Symptoms_Shortness_of_breath": string_dict,
        "Previous_Symptoms_Headache": string_dict,
        "Previous_Symptoms_Nausea_vomiting": string_dict,
        "Previous_Symptoms_Abdominal_pain": string_dict,
        "Previous_Symptoms_Diarrhoea": string_dict,
        "Previous_Symptoms_Loss_of_taste": string_dict,
        "Previous_Symptoms_Loss_of_smell": string_dict,
        "Previous_Symptoms_More_trouble_sleeping_than_usual": string_dict,
        "Previous_Symptoms_Runny_nose_sneezing": string_dict,
        "Previous_Symptoms_Noisy_breathing_wheezing": string_dict,
        "Previous_Symptoms_Loss_of_appetite_or_eating_less_than_usual": string_dict,
        "Previous_Symptoms_Chest_pain": string_dict,
        "Previous_Symptoms_Palpitations": string_dict,
        "Previous_Symptoms_Vertigo_dizziness": string_dict,
        "Previous_Symptoms_Worry_anxiety": string_dict,
        "Previous_Symptoms_Low_mood_not_enjoying_anything": string_dict,
        "Previous_Symptoms_Memory_loss_or_confusion": string_dict,
        "Previous_Symptoms_Difficulty_concentrating": string_dict,
        "If_yes_Date_of_first_symptoms": string_dict,
        "Did_you_contact_NHS": string_dict,
        "Were_you_admitted_to_hospital": string_dict,
        "Have_you_had_a_swab_test": string_dict,
        "If_Yes_What_was_result": string_dict,
        "If_positive_Date_of_1st_ve_test": string_dict,
        "If_all_negative_Date_last_test": string_dict,
        "Have_you_had_a_blood_test_for_Covid": string_dict,
        "What_was_the_result_of_the_blood_test": string_dict,
        "Where_was_the_test_done": string_dict,
        "If_ve_Blood_Date_of_1st_ve_test": string_dict,
        "If_all_ve_blood_Date_last_ve_test": string_dict,
        "Have_Long_Covid_Symptoms": string_dict,
        "Long_Covid_Reduce_Activities": string_dict,
        "Long_Covid_Symptoms": string_dict,
        "Long_Covid_Fever": string_dict,
        "Long_Covid_Weakness_tiredness": string_dict,
        "Long_Covid_Diarrhoea": string_dict,
        "Long_Covid_Loss_of_smell": string_dict,
        "Long_Covid_Shortness_of_breath": string_dict,
        "Long_Covid_Vertigo_dizziness": string_dict,
        "Long_Covid_Trouble_sleeping": string_dict,
        "Long_Covid_Headache": string_dict,
        "Long_Covid_Nausea_vomiting": string_dict,
        "Long_Covid_Loss_of_appetite": string_dict,
        "Long_Covid_Sore_throat": string_dict,
        "Long_Covid_Chest_pain": string_dict,
        "Long_Covid_Worry_anxiety": string_dict,
        "Long_Covid_Memory_loss_or_confusion": string_dict,
        "Long_Covid_Muscle_ache": string_dict,
        "Long_Covid_Abdominal_pain": string_dict,
        "Long_Covid_Loss_of_taste": string_dict,
        "Long_Covid_Cough": string_dict,
        "Long_Covid_Palpitations": string_dict,
        "Long_Covid_Low_mood_not_enjoying_anything": string_dict,
        "Long_Covid_Difficulty_concentrating": string_dict,
        "Long_Covid_Runny_nose_sneezing": string_dict,
        "Long_Covid_Noisy_breathing": string_dict,
        "Have_you_been_offered_a_vaccination": string_dict,
        "Vaccinated_Against_Covid": string_dict,
        "Type_Of_Vaccination": string_dict,
        "Vaccination_Other": string_dict,
        "Number_Of_Doses": string_dict,
        "Date_Of_Vaccination": string_dict,
        "Type_Of_Vaccination_1": string_dict,
        "Vaccination_Other_1": string_dict,
        "Date_Of_Vaccination_1": string_dict,
        "Type_Of_Vaccination_2": string_dict,
        "Vaccination_Other_2": string_dict,
        "Date_Of_Vaccination_2": string_dict,
        "Type_Of_Vaccination_3": string_dict,
        "Vaccination_Other_3": string_dict,
        "Date_Of_Vaccination_3": string_dict,
        "Type_Of_Vaccination_4": string_dict,
        "Vaccination_Other_4": string_dict,
        "Date_Of_Vaccination_4": string_dict,
        "Vaccinated_against_flu": string_dict,
        "Have_you_been_outside_UK_since_April": string_dict,
        "been_outside_uk_last_country": string_dict,
        "been_outside_uk_last_date": string_dict,
        "Have_you_been_outside_UK_Lastspoke": string_dict,
    },
    "cis_digital_validation_schema": {
        "ons_household_id": string_dict,
        "household_invited_to_digital": string_dict,
        "household_digital_enrolment_invited_datetime": string_dict,
        "existing_participant_digital_opt_in_window_start_datetime": string_dict,
        "existing_participant_digital_opt_in_window_end_datetime": string_dict,
        "existing_participant_digital_opted_in_datetime": string_dict,
        "household_digital_enrolment_datetime": string_dict,
        "street": string_dict,
        "city": string_dict,
        "county": string_dict,
        "postcode": string_dict,
        "household_members_under_2_years_count": string_dict,  # TODO Check this has changed to count rather than choice
        "infant_age_months_1": string_dict,
        "infant_age_months_2": string_dict,
        "infant_age_months_3": string_dict,
        "infant_age_months_4": string_dict,
        "infant_age_months_5": string_dict,
        "infant_age_months_6": string_dict,
        "infant_age_months_7": string_dict,
        "infant_age_months_8": string_dict,
        "household_members_over_2_years_and_not_present_count": string_dict,  # TODO Check if count
        "person_not_present_age_1": string_dict,
        "person_not_present_age_2": string_dict,
        "person_not_present_age_3": string_dict,
        "person_not_present_age_4": string_dict,
        "person_not_present_age_5": string_dict,
        "person_not_present_age_6": string_dict,
        "person_not_present_age_7": string_dict,
        "person_not_present_age_8": string_dict,
        "person_not_consenting_age_1": string_dict,
        "reason_for_not_consenting_1": string_dict,
        "person_not_consenting_age_2": string_dict,
        "reason_for_not_consenting_2": string_dict,
        "person_not_consenting_age_3": string_dict,
        "reason_for_not_consenting_3": string_dict,
        "person_not_consenting_age_4": string_dict,
        "reason_for_not_consenting_4": string_dict,
        "person_not_consenting_age_5": string_dict,
        "reason_for_not_consenting_5": string_dict,
        "person_not_consenting_age_6": string_dict,
        "reason_for_not_consenting_6": string_dict,
        "person_not_consenting_age_7": string_dict,
        "reason_for_not_consenting_7": string_dict,
        "person_not_consenting_age_8": string_dict,
        "reason_for_not_consenting_8": string_dict,
        "person_not_consenting_age_9": string_dict,
        "reason_for_not_consenting_9": string_dict,
        "household_participants_not_consenting_count": string_dict,
        "participant_survey_status": string_dict,
        "participant_withdrawal_reason": string_dict,
        "participant_withdrawal_type": string_dict,
        "participant_id": string_dict,
        "title": string_dict,
        "first_name": string_dict,
        "middle_name": string_dict,
        "last_name": string_dict,
        "date_of_birth": string_dict,
        "email_address": string_dict,
        "sex": string_dict,
        "ethnic_group": string_dict,
        "ethnicity": string_dict,
        "ethnicity_other": string_dict,
        "consent_nhs_data_share_yn": string_dict,
        "consent_contact_extra_research_yn": string_dict,
        "consent_use_of_surplus_blood_samples_yn": string_dict,
        "consent_blood_samples_if_positive_yn": string_dict,
        "participant_invited_to_digital": string_dict,
        "participant_enrolled_digital": string_dict,
        "participant_digital_enrolment_datetime": string_dict,
        "existing_participant_digital_opt_in_status": string_dict,
        "existing_participant_digital_opt_in_datetime": string_dict,
        "digital_survey_mode_preference": string_dict,
        "digital_communication_preference": string_dict,
        "sample_return_preference": string_dict,
        "language_preference": string_dict,
        "study_cohort": string_dict,
        "voucher_type_preference": string_dict,
        "digital_entry_pack_sent_datetime": string_dict,
        "digital_entry_pack_status": string_dict,
        "existing_participant_digital_opt_in_reminder_1_due_datetime": string_dict,
        "existing_participant_digital_opt_in_reminder_1_sent_datetime": string_dict,
        "existing_participant_digital_opt_in_reminder_1_status": string_dict,
        "existing_participant_digital_opt_in_reminder_2_due_datetime": string_dict,
        "existing_participant_digital_opt_in_reminder_2_sent_datetime": string_dict,
        "existing_participant_digital_opt_in_reminder_2_status": string_dict,
        "household_completion_window_id": string_dict,
        "household_completion_window_status": string_dict,
        "completion_window_cadence": string_dict,
        "participant_completion_window_id": string_dict,
        "participant_completion_window_status": string_dict,
        "participant_completion_window_start_datetime": string_dict,
        "participant_completion_window_end_datetime": string_dict,
        "survey_response_type": string_dict,
        "opted_out_of_next_window": string_dict,
        "opted_out_of_next_window_datetime": string_dict,
        "opted_out_of_blood_next_window": string_dict,
        "opted_out_of_blood_next_window_datetime": string_dict,
        "blood_sample_transport_status": string_dict,
        "swab_sample_transport_status": string_dict,
        "sample_kit_dispatched_datetime": string_dict,
        "sample_kit_not_dispatched_code": string_dict,  # Commented out in Dummy Data
        "sample_collection_courier_datetime": string_dict,
        "sample_collection_kit_received_delivery_partner_datetime": string_dict,
        "survey_completion_status": string_dict,
        "survey_last_modified_datetime": string_dict,
        "survey_completed_datetime": string_dict,
        "survey_not_completed_reason_code": string_dict,
        "swab_sample_barcode": string_dict,
        "blood_sample_barcode": string_dict,
        "swab_sample_barcode_user_entered": string_dict,
        "blood_sample_barcode_user_entered": string_dict,
        "allocated_swab_barcode_not_used_reason": string_dict,  # Previously Swab_Barcode_Status_Error
        "allocated_blood_barcode_not_used_reason": string_dict,  # Previously Blood_Barcode_Status_Error
        "swab_sample_received_consolidation_point_datetime": string_dict,
        "blood_sample_received_consolidation_point_datetime": string_dict,
        "swab_sample_received_lab_datetime": string_dict,
        "blood_sample_received_lab_datetime": string_dict,
        "digital_survey_collection_mode": string_dict,
        "swab_taken": string_dict,
        "swab_not_taken_reason": string_dict,
        "swab_not_taken_damage_description": string_dict,
        "swab_not_taken_missing_parts": string_dict,
        "swab_not_taken_other": string_dict,
        "questionnaire_started_no_incentive": string_dict,
        "swab_taken_datetime": string_dict,
        "swab_returned": string_dict,
        "swab_return_date": string_dict,
        "swab_return_future_date": string_dict,
        "blood_taken": string_dict,
        "blood_not_taken_reason": string_dict,
        "blood_not_taken_damage_description": string_dict,
        "blood_not_taken_missing_parts": string_dict,
        "blood_not_taken_other": string_dict,
        "blood_not_taken_could_not_reason": string_dict,
        "blood_not_taken_could_not_other": string_dict,
        "blood_taken_datetime": string_dict,
        "blood_returned": string_dict,
        "blood_return_date": string_dict,
        "blood_return_future_date": string_dict,
        "work_status_digital": string_dict,
        "work_status_employment": string_dict,
        "work_status_unemployment": string_dict,
        "work_status_education": string_dict,
        "work_in_additional_paid_employment": string_dict,
        "work_main_job_title": string_dict,
        "work_main_job_role": string_dict,
        "work_sector": string_dict,
        "work_sector_other": string_dict,
        "work_health_care_area": string_dict,
        "work_nursing_or_residential_care_home": string_dict,
        "work_direct_contact_patients_or_clients": string_dict,
        "work_location": string_dict,
        "work_not_from_home_days_per_week": string_dict,
        "education_in_person_days_per_week": string_dict,
        "transport_to_work_or_education": string_dict,
        "ability_to_socially_distance_at_work_or_education": string_dict,
        "think_have_covid_symptom_fever": string_dict,
        "think_have_covid_symptom_headache": string_dict,
        "think_have_covid_symptom_muscle_ache": string_dict,
        "think_have_covid_symptom_fatigue": string_dict,
        "think_have_covid_symptom_nausea_or_vomiting": string_dict,
        "think_have_covid_symptom_abdominal_pain": string_dict,
        "think_have_covid_symptom_diarrhoea": string_dict,
        "think_have_covid_symptom_sore_throat": string_dict,
        "think_have_covid_symptom_cough": string_dict,
        "think_have_covid_symptom_shortness_of_breath": string_dict,
        "think_have_covid_symptom_loss_of_taste": string_dict,
        "think_have_covid_symptom_loss_of_smell": string_dict,
        "think_have_covid_symptom_more_trouble_sleeping": string_dict,
        "think_have_covid_symptom_loss_of_appetite": string_dict,
        "think_have_covid_symptom_runny_nose_or_sneezing": string_dict,
        "think_have_covid_symptom_noisy_breathing": string_dict,
        "think_have_covid_symptom_chest_pain": string_dict,
        "think_have_covid_symptom_palpitations": string_dict,
        "think_have_covid_symptom_vertigo_or_dizziness": string_dict,
        "think_have_covid_symptom_anxiety": string_dict,
        "think_have_covid_symptom_low_mood": string_dict,
        "think_have_covid_symptom_memory_loss_or_confusion": string_dict,
        "think_have_covid_symptom_difficulty_concentrating": string_dict,
        "think_have_covid_onset_date": string_dict,
        "self_isolating": string_dict,
        "self_isolating_reason": string_dict,
        "think_have_covid": string_dict,
        "illness_lasting_over_12_months": string_dict,
        "illness_reduces_activity_or_ability": string_dict,
        "ever_smoked_regularly": string_dict,
        "currently_smokes_or_vapes": string_dict,
        "currently_smokes_or_vapes_description": string_dict,
        "cis_covid_vaccine_received": string_dict,
        "cis_covid_vaccine_number_of_doses": string_dict,
        "cis_covid_vaccine_type_1": string_dict,
        "cis_covid_vaccine_type_other_1": string_dict,
        "cis_covid_vaccine_date_1": string_dict,
        "cis_covid_vaccine_type_2": string_dict,
        "cis_covid_vaccine_type_other_2": string_dict,
        "cis_covid_vaccine_date_2": string_dict,
        "cis_covid_vaccine_type_3": string_dict,
        "cis_covid_vaccine_type_other_3": string_dict,
        "cis_covid_vaccine_date_3": string_dict,
        "cis_covid_vaccine_type_4": string_dict,
        "cis_covid_vaccine_type_other_4": string_dict,
        "cis_covid_vaccine_date_4": string_dict,
        "cis_covid_vaccine_type_5": string_dict,
        "cis_covid_vaccine_type_other_5": string_dict,
        "cis_covid_vaccine_date_5": string_dict,
        "cis_covid_vaccine_type_6": string_dict,
        "cis_covid_vaccine_type_other_6": string_dict,
        "cis_covid_vaccine_date_6": string_dict,
        "cis_flu_vaccine_received": string_dict,
        "been_outside_uk": string_dict,
        "been_outside_uk_last_country": string_dict,
        "been_outside_uk_last_return_date": string_dict,
        "think_had_covid": string_dict,
        "think_had_covid_onset_date": string_dict,
        "think_had_covid_any_symptoms": string_dict,
        "think_had_covid_symptom_fever": string_dict,
        "think_had_covid_symptom_headache": string_dict,
        "think_had_covid_symptom_muscle_ache": string_dict,
        "think_had_covid_symptom_fatigue": string_dict,
        "think_had_covid_symptom_nausea_or_vomiting": string_dict,
        "think_had_covid_symptom_abdominal_pain": string_dict,
        "think_had_covid_symptom_diarrhoea": string_dict,
        "think_had_covid_symptom_sore_throat": string_dict,
        "think_had_covid_symptom_cough": string_dict,
        "think_had_covid_symptom_shortness_of_breath": string_dict,
        "think_had_covid_symptom_loss_of_taste": string_dict,
        "think_had_covid_symptom_loss_of_smell": string_dict,
        "think_had_covid_symptom_more_trouble_sleeping": string_dict,
        "think_had_covid_symptom_loss_of_appetite": string_dict,
        "think_had_covid_symptom_runny_nose_or_sneezing": string_dict,
        "think_had_covid_symptom_noisy_breathing": string_dict,
        "think_had_covid_symptom_chest_pain": string_dict,
        "think_had_covid_symptom_palpitations": string_dict,
        "think_had_covid_symptom_vertigo_or_dizziness": string_dict,
        "think_had_covid_symptom_anxiety": string_dict,
        "think_had_covid_symptom_low_mood": string_dict,
        "think_had_covid_symptom_memory_loss_or_confusion": string_dict,
        "think_had_covid_symptom_difficulty_concentrating": string_dict,
        "think_had_covid_contacted_nhs": string_dict,
        "think_had_covid_admitted_to_hospital": string_dict,
        "other_covid_infection_test": string_dict,
        "other_covid_infection_test_results": string_dict,
        "other_covid_infection_test_first_positive_date": string_dict,
        "other_covid_infection_test_last_negative_date": string_dict,
        "regularly_lateral_flow_testing": string_dict,
        "other_antibody_test": string_dict,
        "other_antibody_test_results": string_dict,
        "other_antibody_test_first_positive_date": string_dict,
        "other_antibody_test_last_negative_date": string_dict,
        "think_have_long_covid": string_dict,
        "think_have_long_covid_symptom_reduced_ability": string_dict,
        "think_have_long_covid_symptom_fever": string_dict,
        "think_have_long_covid_symptom_headache": string_dict,
        "think_have_long_covid_symptom_muscle_ache": string_dict,
        "think_have_long_covid_symptom_fatigue": string_dict,
        "think_have_long_covid_symptom_nausea_or_vomiting": string_dict,
        "think_have_long_covid_symptom_abdominal_pain": string_dict,
        "think_have_long_covid_symptom_diarrhoea": string_dict,
        "think_have_long_covid_symptom_loss_of_taste": string_dict,
        "think_have_long_covid_symptom_loss_of_smell": string_dict,
        "think_have_long_covid_symptom_sore_throat": string_dict,
        "think_have_long_covid_symptom_cough": string_dict,
        "think_have_long_covid_symptom_shortness_of_breath": string_dict,
        "think_have_long_covid_symptom_loss_of_appetite": string_dict,
        "think_have_long_covid_symptom_chest_pain": string_dict,
        "think_have_long_covid_symptom_palpitations": string_dict,
        "think_have_long_covid_symptom_vertigo_or_dizziness": string_dict,
        "think_have_long_covid_symptom_anxiety": string_dict,
        "think_have_long_covid_symptom_low_mood": string_dict,
        "think_have_long_covid_symptom_more_trouble_sleeping": string_dict,
        "think_have_long_covid_symptom_memory_loss_or_confusion": string_dict,
        "think_have_long_covid_symptom_difficulty_concentrating": string_dict,
        "think_have_long_covid_symptom_runny_nose_or_sneezing": string_dict,
        "think_have_long_covid_symptom_noisy_breathing": string_dict,
        "contact_known_positive_covid_last_28_days": string_dict,
        "last_covid_contact_date": string_dict,
        "last_covid_contact_type": string_dict,
        "contact_suspected_positive_covid_last_28_days": string_dict,
        "last_suspected_covid_contact_date": string_dict,
        "last_suspected_covid_contact_type": string_dict,
        "hospital_last_28_days": string_dict,
        "other_household_member_hospital_last_28_days": string_dict,
        "care_home_last_28_days": string_dict,
        "other_household_member_care_home_last_28_days": string_dict,
        "hours_a_day_with_someone_else_at_home": string_dict,
        "physical_contact_under_18_years": string_dict,
        "physical_contact_18_to_69_years": string_dict,
        "physical_contact_over_70_years": string_dict,
        "social_distance_contact_under_18_years": string_dict,
        "social_distance_contact_18_to_69_years": string_dict,
        "social_distance_contact_over_70_years": string_dict,
        "times_hour_or_longer_another_home_last_7_days": string_dict,
        "times_hour_or_longer_another_person_your_home_last_7_days": string_dict,
        "times_shopping_last_7_days": string_dict,
        "times_socialising_last_7_days": string_dict,
        "face_covering_work_or_education": string_dict,
        "face_covering_other_enclosed_places": string_dict,
        "work_main_job_changed": string_dict,
        "cis_covid_vaccine_type": string_dict,
        "cis_covid_vaccine_type_other": string_dict,
        "cis_covid_vaccine_date": string_dict,
        "swab_sample_barcode_correct": string_dict,
        "blood_sample_barcode_correct": string_dict,
        "think_have_covid_symptom_onset_date": string_dict,
        "think_have_covid_symptoms": string_dict,
        "other_covid_infection_test_positive_date": string_dict,
        "other_covid_infection_test_negative_date": string_dict,
        "other_antibody_test_positive_date": string_dict,
        "other_antibody_test_negative_date": string_dict,
    },
}
