# A list of positive test cases which need to be interpreted as Attending University &
# negative test cases which shouldn't.
# Please append new cases to the appropriate list below
test_data = {
    "positive": [
        "STUDYING SOCIAL POLICY",
        "STUDYING AT UNIVERSITY",
        "STUDENT",
        "STUDYING",
        "FULL TIME STUDENT",
        "FULL TIME EDUCATION",
        "PHD STUDENT",
        "STUDENT FULL TIME",
        "STUDY",
        "AT COLLEGE",
        "STUDYING SOCIAL POLICY",
        "STUDYING AT UNIVERSITY",
        "STUDYING SOCIAL POLICY",
        "STUDENT",
        "STUDYING",
        "STUDWNY",
        "N/A (STUDENT)",
        "UNIVERSITY STUDENT",
        "PHD STUDENT",
        "STUDENT ONLY",
        "STUDYING",
        "STUDY",
        "STUDENT",
        "STUDYING MECHANICAL ENGINEERING",
        "STUDT",
        "STIDY",
        "UNIVERSITY STUDENT",
        "STUDENT UNIVERSITY",
        "STUDENT",
        "STUDYING",
        "FULL TIME STUDENT",
        "FULL TIME EDUCATION",
        "PHD STUDENT",
        "STUDENT FULL TIME",
        "STUDY",
        "AT COLLEGE",
        "STUDYING SOCIAL POLICY",
    ],
    "negative": ["LEARNING OFFICER"],
}
