# This is a basic workflow to help you get started with Actions

name: Integration testing

# Controls when the action will run.
on:
  pull_request: # And on all Pull Requests

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.6.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.6.8"

      - name: Check package build
        run: |
          python -m pip install --upgrade pip
          pip install wheel==0.29.0
          python setup.py sdist bdist_wheel
  test:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: "3.6.8"
          cache: 'pip'

      - uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Cache spark
        id: cache-spark
        uses: actions/cache@v3
        with:
          path: ../../spark-2.4.0-bin-hadoop2.6
          key: ${{ runner.os }}-spark-2.4.0

      - name: Download spark
        if: steps.cache-spark.outputs.cache-hit != 'true'
        run: |
          cd ../../ &&
          wget -q -O spark.tgz https://archive.apache.org/dist/spark/spark-2.4.0/spark-2.4.0-bin-hadoop2.6.tgz &&
          tar xzvf spark.tgz &&
          rm "spark.tgz"

      - name: Configure spark
        run: (cd ../../spark-2.4.0-bin-hadoop2.6 &&
          export SPARK_HOME=`pwd` &&
          export PYTHONPATH=$(ZIPS=("$SPARK_HOME"/python/lib/*.zip); IFS=:; echo "${ZIPS[*]}"):$PYTHONPATH
          )

      - name: Install Python dependencies
        # Wheel is specific here because of conflicts on this Python version
        run: |
          python -m pip install --upgrade pip
          pip install pypandoc==1.5
          pip install -e .[ci]

      - name: Run pytest
        run: |
          pytest -v -m integration
